import type { NexusTheme } from "@nexus/core/foundation/theme";

export const probeTheme: NexusTheme = {
  "space.xs": "0.5rem",
  "space.sm": "1rem",
  "space.md": "1.5rem",
  "space.lg": "3rem",
  "space.xl": "6rem",
  "container.sm": "36rem",
  "container.md": "52rem",
  "container.lg": "72rem",
  "container.xl": "92rem",
  "focus.ring": "#5b3dd6",
  "focus.offset": "3px",
  "motion.duration.instant": "0ms",
  "motion.duration.fast": "160ms",
  "motion.duration.base": "360ms",
  "motion.duration.slow": "760ms",
  "motion.easing.standard": "ease",
  "motion.easing.decelerate": "cubic-bezier(0.16,1,0.3,1)",
  "motion.easing.accelerate": "cubic-bezier(0.7,0,0.84,0)",
  "motion.easing.linear": "linear",
  "surface.base": "#efe7f5",
  "surface.elevated": "#f9f4fc",
  "surface.inverse": "#281d31",
  "surface.overlay": "rgba(40,29,49,.25)",
  "content.primary": "#281d31",
  "content.secondary": "#6f5d7a",
  "content.inverse": "#f9f4fc",
  "content.disabled": "#aa9bb2",
  "accent.default": "#5b3dd6",
  "accent.emphasis": "#4023b8",
  "accent.muted": "#c2b7ef",
  "border.subtle": "rgba(40,29,49,.14)",
  "border.strong": "rgba(40,29,49,.48)",
  "radius.sm": "0px",
  "radius.md": "18px",
  "radius.lg": "48px",
  "radius.full": "999px",
};
