//! Offline-first edge journal with explicit reconciliation and conflict surfacing.
#![forbid(unsafe_code)]
use std::collections::BTreeMap;
#[derive(Debug,Clone,PartialEq,Eq)]pub struct OfflineOp{pub op_id:String,pub stream:String,pub sequence:u64,pub base_revision:u64,pub payload_hash:String,pub created_at_ms:u64}
#[derive(Debug,Clone,Copy,PartialEq,Eq)]pub enum ReconcileOutcome{Accepted,Duplicate,Conflict,RejectedStale}
#[derive(Debug,Default)]pub struct OfflineJournal{ops:BTreeMap<u64,OfflineOp>,seen:BTreeMap<String,String>,acked:u64}
impl OfflineJournal{pub fn append(&mut self,op:OfflineOp)->Result<(),String>{if op.sequence<=self.acked{return Err("operation older than acknowledged watermark".into())}if let Some(existing)=self.seen.get(&op.op_id){if existing==&op.payload_hash{return Ok(())}return Err("offline op id reused with different payload hash".into())}if let Some((_,last))=self.ops.iter().next_back(){if op.sequence<=last.sequence{return Err("offline sequence must increase".into())}}self.seen.insert(op.op_id.clone(),op.payload_hash.clone());self.ops.insert(op.sequence,op);Ok(())}pub fn pending(&self)->Vec<&OfflineOp>{self.ops.range((self.acked.saturating_add(1))..).map(|(_,v)|v).collect()}pub fn acknowledge(&mut self,sequence:u64)->Result<(),String>{if sequence<self.acked{return Err("acknowledgement moved backwards".into())}let max_known=self.ops.keys().next_back().copied().unwrap_or(self.acked);if sequence>max_known{return Err("acknowledgement exceeds known journal sequence".into())}self.acked=sequence;self.ops.retain(|seq,_|*seq>sequence);Ok(())}}
pub trait Reconciler:Send+Sync{fn reconcile(&self,op:&OfflineOp,current_revision:u64)->Result<ReconcileOutcome,String>;}

#[cfg(test)]mod repair_tests{use super::*;fn op(seq:u64,id:&str,hash:&str)->OfflineOp{OfflineOp{op_id:id.into(),stream:"s".into(),sequence:seq,base_revision:0,payload_hash:hash.into(),created_at_ms:0}}#[test]fn op_id_collision_rejected(){let mut j=OfflineJournal::default();j.append(op(1,"x","a")).unwrap();assert!(j.append(op(2,"x","b")).is_err());}#[test]fn ack_cannot_skip_unknown_sequence(){let mut j=OfflineJournal::default();j.append(op(1,"x","a")).unwrap();assert!(j.acknowledge(2).is_err());j.acknowledge(1).unwrap();assert!(j.pending().is_empty());}}
