import type { NexusTheme } from "@nexus/core/foundation/theme";

export const probeTheme: NexusTheme = {
  "space.xs": "0.5rem",
  "space.sm": "1rem",
  "space.md": "1.5rem",
  "space.lg": "3rem",
  "space.xl": "6rem",
  "container.sm": "36rem",
  "container.md": "52rem",
  "container.lg": "72rem",
  "container.xl": "92rem",
  "focus.ring": "#ff5d3a",
  "focus.offset": "3px",
  "motion.duration.instant": "0ms",
  "motion.duration.fast": "160ms",
  "motion.duration.base": "360ms",
  "motion.duration.slow": "760ms",
  "motion.easing.standard": "ease",
  "motion.easing.decelerate": "cubic-bezier(0.16,1,0.3,1)",
  "motion.easing.accelerate": "cubic-bezier(0.7,0,0.84,0)",
  "motion.easing.linear": "linear",
  "surface.base": "#07080b",
  "surface.elevated": "#10131a",
  "surface.inverse": "#f3f5fb",
  "surface.overlay": "rgba(0,0,0,.62)",
  "content.primary": "#f3f5fb",
  "content.secondary": "#9ca4b7",
  "content.inverse": "#07080b",
  "content.disabled": "#5a6273",
  "accent.default": "#ff5d3a",
  "accent.emphasis": "#ffb7a7",
  "accent.muted": "#5e2c25",
  "border.subtle": "rgba(243,245,251,.14)",
  "border.strong": "rgba(243,245,251,.42)",
  "radius.sm": "2px",
  "radius.md": "4px",
  "radius.lg": "8px",
  "radius.full": "999px",
};
