import { join } from "node:path";
import { describe, expect, it, vi } from "vitest";
import { createWorkspaceClientRuntimeAdapters } from "../scripts/nexus-client-runtime.mjs";

const SHA = "a".repeat(40);
const project = {
  slug: "client",
  path: "apps/client",
  packageName: "@nexus/client",
  workspaceMember: true,
  kind: "CLIENT",
  clientProject: true,
  evidence: { packageJsonPath: "apps/client/package.json", clientProjectDeclaration: true, classificationRule: "test" },
};

function spec(root: string) {
  return {
    projectId: "client",
    sourceRevision: SHA,
    outputDir: join(root, "apps/client"),
    runtime: { target: "client" },
  };
}

function artifact(capability: string, browser: string, viewport: string, index: number) {
  return {
    artifactId: `${capability}-${browser}-${viewport}`,
    runId: "run-1",
    scope: { tenantId: "nexus-mcp", brandId: "client" },
    capability,
    mediaType: capability === "SCREENSHOT" ? "image/png" : "application/json",
    digest: `sha256:${String(index).padStart(64, "0")}`,
    byteLength: 10,
    capturedAt: "2026-09-01T00:00:00.000Z",
    uri: `/tmp/${capability}-${browser}-${viewport}`,
    metadata: { browser, viewport },
  };
}

function captureEvidence() {
  const artifacts = [] as any[];
  let index = 1;
  for (const browser of ["chromium", "webkit"]) {
    for (const viewport of ["mobile-390", "tablet-768", "desktop-1440"]) {
      artifacts.push(artifact("SCREENSHOT", browser, viewport, index++));
      artifacts.push(artifact("ACCESSIBILITY", browser, viewport, index++));
      artifacts.push(artifact("DESIGN_GENOME", browser, viewport, index++));
    }
  }
  return { requestId: "capture-1", runId: "run-1", targetUrl: "http://127.0.0.1:3000", artifacts, samples: [] };
}

function options(root: string, overrides: Record<string, unknown> = {}) {
  return {
    root,
    projects: async () => [project],
    git: async () => ({ branch: "audit", headSha: SHA, detached: false, clean: true, changedPaths: [], remoteUrl: null }),
    readOnly: async () => "",
    build: async () => ({
      target: { slug: "client", path: "apps/client", packageName: "@nexus/client" },
      command: "node scripts/build-target-manifest.mjs",
      exitCode: 0,
      durationMs: 1,
      logPath: "/tmp/build.log",
      manifestPath: "/tmp/manifest.json",
      manifest: { manifestSha256: "b".repeat(64), outputDigest: "c".repeat(64) },
    }),
    buildValidator: async () => true,
    prepareCapture: async () => undefined,
    capture: async () => captureEvidence(),
    ...overrides,
  };
}

describe("workspace client runtime adapters", () => {
  it("reuses exact-SHA build and browser evidence for render, capture and design genome", async () => {
    const root = "/repo";
    const adapters: any = await createWorkspaceClientRuntimeAdapters(spec(root), options(root));
    const generation = { generationDigest: `sha256:${"d".repeat(64)}` };
    const render = await adapters.render({ generation });
    expect(render.gate).toMatchObject({ gateId: "RENDER", verdict: "PASS" });
    expect(render.gate.evidenceIds).toContain(`sha256:${"b".repeat(64)}`);

    const capture = await adapters.capture({ generation, render });
    expect(capture.gate).toMatchObject({ gateId: "CAPTURE", verdict: "PASS" });
    expect(capture.evidence.artifacts.filter((item: any) => item.capability === "SCREENSHOT")).toHaveLength(6);

    const genome = await adapters.designGenome({ capture });
    expect(genome.gate).toMatchObject({ gateId: "DESIGN_GENOME", verdict: "PASS" });
    expect(genome.artifacts).toHaveLength(6);
  });

  it("fails render instead of binding generated dirty bytes to the declared source SHA", async () => {
    const root = "/repo";
    const build = vi.fn();
    const adapters: any = await createWorkspaceClientRuntimeAdapters(spec(root), options(root, { readOnly: async () => " M apps/client/src/app/page.tsx", build }));
    const render = await adapters.render({ generation: { generationDigest: `sha256:${"d".repeat(64)}` } });
    expect(render.gate.verdict).toBe("FAIL");
    expect(render.gate.detail).toContain("commit the generated bytes and rerun");
    expect(build).not.toHaveBeenCalled();
  });

  it("does not invent production adapters when runtime target is absent", async () => {
    await expect(createWorkspaceClientRuntimeAdapters({ projectId: "client", sourceRevision: SHA }, { root: "/repo" })).resolves.toEqual({});
  });
});
