"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { site } from "./site-data";
import { features } from "./features-data";

export function SiteNav(){const pathname=usePathname();return <header className="siteHeader"><nav className="nav" aria-label="Menú"><Link className="brand" href="/">{site.brand}</Link><div className="navLinks">{site.routes.map((route)=><Link key={route.path} href={route.path} aria-current={pathname===route.path?"page":undefined}>{route.navLabel}</Link>)}</div></nav></header>}

export function ExperiencePage({routePath}:{routePath:string}){const route=site.routeContent.find((item)=>item.path===routePath)??site.routeContent[0];if(!route)return null;const headline=route.copy.find((item)=>item.role==="headline")??site.copy.find((item)=>item.role==="headline");const lede=route.copy.find((item)=>item.role==="value-proposition")??site.copy.find((item)=>item.role==="value-proposition");const body=route.copy.filter((item)=>!["headline","value-proposition","primary-cta"].includes(item.role));const showMap=Boolean(features.location&&(route.path==="/visit"||route.capabilityIds.includes("map")||route.capabilityIds.includes("location")));const showReviews=features.reviews.length>0&&(route.path==="/proof"||route.capabilityIds.includes("reviews")||route.capabilityIds.includes("social-proof"));return <><a className="skip" href="#main">Saltar al contenido</a><SiteNav/><main id="main" className="page"><div className="opening"><div className="eyebrow">{route.navLabel}</div>{headline&&<h1>{headline.text}</h1>}{lede&&<p className="lede">{lede.text}</p>}<div className="actions">{route.actions.map((action)=>{const tone=features.greenCapabilities.includes(action.capabilityId)?"green":undefined;return <a className="action" data-semantic-tone={tone} data-emphasis={action.emphasis??"secondary"} data-capability={action.capabilityId} key={action.href} href={action.href}>{action.label}</a>})}</div></div><div className="sections">{body.map((item,index)=><section className="section" key={item.role}><div className="copyBlock"><div className="eyebrow">{item.role.replaceAll("-"," ")}</div><h2>{item.text.split(/[.!?]/)[0]}</h2><p>{item.text}</p></div>{route.media[index]&&<figure className="mediaBlock"><img src={route.media[index].publicPath} alt={route.media[index].alt}/></figure>}</section>)}{route.media.slice(body.length).map((media)=><section className="section" key={media.assetId}><div className="copyBlock"><div className="eyebrow">{media.role.replaceAll("-"," ")}</div></div><figure className="mediaBlock"><img src={media.publicPath} alt={media.alt}/></figure></section>)}{showMap&&features.location&&<section className="section" aria-label="Mapa de ubicación"><div className="mapWrap"><iframe className="mapFrame" title="Mapa de ubicación" loading="lazy" referrerPolicy="no-referrer-when-downgrade" src={features.location.embedUrl}/></div></section>}{showReviews&&<section className="section" aria-label="Reseñas verificadas en Google Maps"><div className="copyBlock"><div className="eyebrow">Reseñas verificadas en Google Maps</div></div><div className="reviewsGrid">{features.reviews.map((review)=><article className="reviewCard" key={review.sourceId}><p>{review.text}</p><div className="reviewMeta">{review.author??"Google Maps"}{review.rating!==undefined?` · ${review.rating}/5`:""}</div></article>)}</div></section>}</div></main><footer className="footer">{site.brand}</footer></>}
