import assert from 'node:assert/strict';
import test from 'node:test';
import {BATCH_500_NUMBER_SEQUENCE_OPERATORS,lucasNumber,pellNumber,pellLucasNumber,jacobsthalNumber,jacobsthalLucasNumber,tribonacciNumber,tetranacciNumber,catalanNumber,motzkinNumber,derangementNumber,bellNumber,orderedBellNumber,partitionIntoDistinctParts,partitionIntoOddParts,stirlingSecondKind,stirlingFirstKindUnsigned,eulerianNumber,derangementInclusionExclusion,centralBinomialCoefficient,narayanaNumber} from '../core/batch-500-number-sequences.mjs';
const value=(fn,args)=>BigInt(fn(args).value);
function factorial(n){let r=1n;for(let i=2;i<=n;i++)r*=BigInt(i);return r;}
function choose(n,k){if(k<0||k>n)return 0n;let r=1n;for(let i=1;i<=k;i++)r=r*BigInt(n-k+i)/BigInt(i);return r;}
function recurrence(seed,coeff,n){const a=seed.map(BigInt);for(let i=a.length;i<=n;i++){let x=0n;for(let j=0;j<coeff.length;j++)x+=BigInt(coeff[j])*a[i-j-1];a.push(x);}return a[n];}
function partitions(n,predicate=()=>true,distinct=false){let count=0n;function go(rem,max){if(rem===0){count++;return;}for(let p=Math.min(rem,max);p>=1;p--)if(predicate(p))go(rem-p,distinct?p-1:p);}go(n,n);return count;}
function stirling2(n,k){if(n===0)return k===0?1n:0n;if(k===0)return 0n;return stirling2(n-1,k-1)+BigInt(k)*stirling2(n-1,k);}
function stirling1(n,k){if(n===0)return k===0?1n:0n;if(k===0)return 0n;return stirling1(n-1,k-1)+BigInt(n-1)*stirling1(n-1,k);}
function eulerian(n,k){if(n===0)return k===0?1n:0n;if(k<0||k>=n)return 0n;return BigInt(k+1)*eulerian(n-1,k)+BigInt(n-k)*eulerian(n-1,k-1);}
test('201-220 expose 20 unique executable contracts',()=>{assert.equal(BATCH_500_NUMBER_SEQUENCE_OPERATORS.length,20);assert.equal(new Set(BATCH_500_NUMBER_SEQUENCE_OPERATORS.map(x=>x.id)).size,20);assert.equal(new Set(BATCH_500_NUMBER_SEQUENCE_OPERATORS.map(x=>x.execute)).size,20);});
test('linear recurrences match independent recurrence oracle',()=>{for(let n=0;n<=12;n++){assert.equal(value(lucasNumber,{n}),recurrence([2,1],[1,1],n));assert.equal(value(pellNumber,{n}),recurrence([0,1],[2,1],n));assert.equal(value(pellLucasNumber,{n}),recurrence([2,2],[2,1],n));assert.equal(value(jacobsthalNumber,{n}),recurrence([0,1],[1,2],n));assert.equal(value(jacobsthalLucasNumber,{n}),recurrence([2,1],[1,2],n));assert.equal(value(tribonacciNumber,{n}),recurrence([0,0,1],[1,1,1],n));assert.equal(value(tetranacciNumber,{n}),recurrence([0,0,0,1],[1,1,1,1],n));}});
test('combinatorial sequences match independent formulas/enumeration',()=>{for(let n=0;n<=9;n++){assert.equal(value(catalanNumber,{n}),choose(2*n,n)/BigInt(n+1));assert.equal(value(derangementNumber,{n}),value(derangementInclusionExclusion,{n}));assert.equal(value(centralBinomialCoefficient,{n}),choose(2*n,n));assert.equal(value(partitionIntoDistinctParts,{n}),partitions(n,()=>true,true));assert.equal(value(partitionIntoOddParts,{n}),partitions(n,p=>p%2===1,false));}assert.deepEqual([0,1,2,3,4,5,6,7,8].map(n=>value(motzkinNumber,{n})),[1n,1n,2n,4n,9n,21n,51n,127n,323n]);assert.deepEqual([0,1,2,3,4,5,6].map(n=>value(bellNumber,{n})),[1n,1n,2n,5n,15n,52n,203n]);assert.deepEqual([0,1,2,3,4,5].map(n=>value(orderedBellNumber,{n})),[1n,1n,3n,13n,75n,541n]);});
test('triangle operators match recursive independent oracles',()=>{for(let n=1;n<=8;n++)for(let k=1;k<=n;k++){assert.equal(value(stirlingSecondKind,{n,k}),stirling2(n,k));assert.equal(value(stirlingFirstKindUnsigned,{n,k}),stirling1(n,k));assert.equal(value(narayanaNumber,{n,k}),choose(n,k)*choose(n,k-1)/BigInt(n));if(k<n)assert.equal(value(eulerianNumber,{n,k:k-1}),eulerian(n,k-1));}});
test('strict bounds reject malformed/adversarial inputs',()=>{for(const fn of [lucasNumber,pellNumber,catalanNumber,bellNumber,centralBinomialCoefficient]){assert.throws(()=>fn({n:-1}),RangeError);assert.throws(()=>fn({n:1.5}),RangeError);assert.throws(()=>fn({n:Number.NaN}),RangeError);}assert.throws(()=>narayanaNumber({n:4,k:0}),RangeError);assert.throws(()=>stirlingSecondKind({n:4,k:5}),RangeError);assert.throws(()=>eulerianNumber({n:4,k:4}),RangeError);});
test('derangement inclusion-exclusion independently equals rounded n!/e for small n',()=>{const expected=[1n,0n,1n,2n,9n,44n,265n,1854n,14833n,133496n];for(let n=0;n<expected.length;n++){assert.equal(value(derangementInclusionExclusion,{n}),expected[n]);assert.ok(value(derangementNumber,{n})<=factorial(n));}});
