//! Optimistic-concurrency registry for all V5 resources.
#![forbid(unsafe_code)]
use std::{collections::BTreeMap,sync::RwLock};
use nexus_control_model::{ResourceRecord,ResourceRef};
pub trait ResourceRegistry: Send+Sync { fn get(&self,r:&ResourceRef)->Option<ResourceRecord>; fn put(&self,record:ResourceRecord,expected_version:Option<u64>)->Result<ResourceRecord,String>; }
#[derive(Default)] pub struct MemoryRegistry{inner:RwLock<BTreeMap<ResourceRef,ResourceRecord>>}
impl ResourceRegistry for MemoryRegistry { fn get(&self,r:&ResourceRef)->Option<ResourceRecord>{self.inner.read().ok()?.get(r).cloned()} fn put(&self,record:ResourceRecord,expected:Option<u64>)->Result<ResourceRecord,String>{record.validate()?;let mut g=self.inner.write().map_err(|_|"registry lock poisoned")?;match expected{Some(v)=>{let cur=g.get(&record.reference).map(|x|x.version).ok_or("resource absent")?;if cur!=v{return Err("optimistic concurrency conflict".into())}let next=v.checked_add(1).ok_or("resource version exhausted")?;if record.version!=next{return Err("resource version must advance exactly once".into())}},None=>{if g.contains_key(&record.reference){return Err("resource already exists".into())}if record.version!=1{return Err("new resource version must be 1".into())}}}g.insert(record.reference.clone(),record.clone());Ok(record)} }

#[cfg(test)]mod repair_tests{use super::*;use nexus_control_model::{Lifecycle,OrganizationId,ResourceId,ResourceKind};fn r(v:u64)->ResourceRecord{ResourceRecord{reference:ResourceRef{organization:OrganizationId("o".into()),kind:ResourceKind::Agent,id:ResourceId("a".into())},version:v,lifecycle:Lifecycle::Active,labels:Default::default(),created_at_ms:0,updated_at_ms:0}}#[test]fn create_cannot_overwrite(){let x=MemoryRegistry::default();x.put(r(1),None).unwrap();assert!(x.put(r(1),None).is_err());}#[test]fn update_must_advance_one_version(){let x=MemoryRegistry::default();x.put(r(1),None).unwrap();assert!(x.put(r(1),Some(1)).is_err());assert!(x.put(r(2),Some(1)).is_ok());}}
