from __future__ import annotations

import re
import unicodedata
from typing import Dict, Tuple

SOURCE_SPEC_SHA256 = "sha256:16dc5dd3c0834c1e3306add2bb79b00aac072fd5767ce352c31725d2d024e9d1"
SOURCE_SPEC_RANGE = ("M1201", "M1400")

SOURCE_NAMES = (
    'Router de Fragmentos Condicionales',
    'Inyector de Atributos ARIA Semánticos',
    'Normalizador de Paths con rstrip Dinámico',
    'Balanceador de CSS Crítico Inline',
    'Optimizador de Atributos Decoding/Loading',
    'Rewrite de Enlaces Internos Relativos',
    'Sanitizador de Entity-Encoding HTML',
    'Transformador de Tablas a Bloques Semánticos',
    'Inyector de Resource Hints Predictivos',
    'Evaluador de Tamaño de DOM en Edge',
    'Reescritor de Clases CSS Ofuscadas',
    'Minificador de JS Embebido al Vuelo',
    'Reorganizador de Orden de Head Tags',
    'Purger Local de Estilos No Utilizados',
    'Generador de Micro-Formatos de Breadcrumbs',
    'Inyector de Datos de Autoría Estructural',
    'Normalizador de Enlaces Anchor',
    'Optimizador de Fuentes Locales Preload',
    'Evaluador de Ratio de Texto/HTML',
    'Reescritor de URLs de Imágenes Semánticas',
    'Controlador de Cache-Control Aguas Abajo',
    'Agrupador de Peticiones Estáticas inline',
    'Modificador de Atributos Target Seguros',
    'Filtro de Comentarios de Desarrollo',
    'Distribuidor de Atributos de Idioma',
    'Enlazador Cruzado de Entidades Relacionadas',
    'Agrupador de Conceptos por Co-ocurrencia',
    'Filtro de Ambigüedad Semántica',
    'Generador de Grafos JSON-LD Nested',
    'Evaluador de Relevancia Salience Score',
    'Extractor de Atributos Numéricos Cardinales',
    'Detector de Entidades de Ubicación Geográfica',
    'Mapeador de Taxonomías Jerárquicas',
    'Buscador de Sinónimos Deterministas',
    'Validador de Tipos de Datos de Esquema',
    'Extractor de Entidades Organizacionales',
    'Indexador de Propiedades de Entidades',
    'Generador de IDs Únicos Corporativos',
    'Normalizador de Variantes Lingüísticas',
    'Constructor de Contexto de Entidad Externa',
    'Puntuador de Diversidad Semántica',
    'Analizador de Densidad de Frases Cortas',
    'Extractor de Definiciones Clave',
    'Generador de Anclas Temáticas Automatizadas',
    'Compilador de Perfiles de Entidades Frecuentes',
    'Validador de Jerarquía de Headings',
    'Detector de Entidades de Eventos Temporales',
    'Mapeador de Entidades de Productos',
    'Agrupador por Intención de Búsqueda',
    'Consolidador de Grafos de Sitio Completo',
    'Garbage Collector de Rutas Huérfanas',
    'Monitor de Concurrencia de Jobs',
    'Agrupador Atómico de Transacciones SQL',
    'Calculador de Hash Total de Sitio',
    'Analizador de Volatilidad de Vectores',
    'Gestor de Tiempos de Expiración de Trabajos',
    'Compresor de Estructuras JSON vectorizadas',
    'Particionador de Datos Históricos de Ruta',
    'Validador de Integridad de la Clave Primaria',
    'Mapeador de Relaciones entre Secciones',
    'Evaluador de Coincidencia de Esquemas de Tablas',
    'Filtro de Deduplicación en Cola de Entrada',
    'Indexador de Coincidencias de Grounding',
    'Contador de Vectores por Estado de Publicación',
    'Gestor de Reintentos Exponenciales Internos',
    'Normalizador de Cadenas UTF-8 en Base de Datos',
    'Agrupador de Jobs por Prioridad Estructural',
    'Rastreador de Modificaciones en Sitemaps',
    'Verificador de Consistencia de Snapshots',
    'Limpiador de Espacio en Tablas Temporales',
    'Monitor de Tamaño de Cache Grounding',
    'Historial de Versiones de Configuración de Sitio',
    'Optimizador de Consultas de Lectura de Rutas',
    'Re-enlazador de Referencias Rotas Internas',
    'Inspector Interno de Estado de Tablas',
    'Validador de Formato de Payload Edge',
    'Gestor de Tokens en Cabeceras Seguras',
    'Interceptor de Errores de API de Cloudflare',
    'Comparador de Firmas Digitales en Edge',
    'Verificador de Headers de Éxito Aplicados',
    'Controlador de fallback Dinámico por URL',
    'Analizador de Latencia de Publicación Edge',
    'Generador de Prefijos de Clave Dinámicos',
    'Normalizador de Esquemas JSON del Worker',
    'Monitor de Cuotas de Escritura KV',
    'Validador de Endpoint Publisher Seguro',
    'Re-sincronizador de Emergencia en Bloque',
    'Inspector de Estado Inmediato Fail-Open',
    'Comprobador de Respuestas HTTP No-200 Base',
    'Inyector de Tags de Control de Compresión',
    'Detector de Bucles de Redirección Estructural',
    'Compilador de Métricas de Exclusión',
    'Verificador de Coincidencia de Dominio Target',
    'Mapeador de Respuestas en Memoria Caché',
    'Sanitizador de Cabeceras HTTP Personalizadas',
    'Gestor de Despliegue de Snapshots Incrementales',
    'Validador de Cumplimiento de Políticas',
    'Evaluador de Peso Crítico de Respuestas',
    'Distribuidor de Firma Digital de Suite',
    'Conector de Health-Check Unificado',
    'Analizador de Modificadores Transaccionales',
    'Detector de Brechas de Información',
    'Clasificador de Intención Comercial Directa',
    'Extractor de Entidades Conectadas por Preposiciones',
    'Generador de Clústeres Semánticos',
    'Optimizador de Snippets para Comparativas',
    'Filtro de Intención Informativa Pura',
    'Mapeador de Sinónimos de Conversión Elevada',
    'Extractor de Estructuras Semánticas de Listas',
    'Generador de Micro-Secciones de FAQ',
    'Indexador de Coincidencias Exactas de Búsqueda',
    'Puntuador de Legibilidad Dinámica',
    'Detector de Coincidencias Lógicas Cruzadas',
    'Analizador de Densidad de Respuestas Directas',
    'Generador de Identificadores Semánticos Imagen',
    'Optimizador de Títulos Ricos en Entidades',
    'Reestructurador de Meta-Descriptions',
    'Filtro de Adjetivos Redundantes Anti-Spam',
    'Rastreador de Vigencia de Contenido Temporizado',
    'Agrupador Lógico de Entidades por Nicho',
    'Evaluador de Relevancia de Enlaces Salientes',
    'Optimizador de Anclajes de Enlaces Internos',
    'Detector de Entidades Huérfanas de Navegación',
    'Constructor de Architecturas Web en Silo',
    'Consolidador de Autoridad Temática Global',
    'Inyector de Conexión Anticipada Preconnect',
    'Minificador de Atributos HTML Innecesarios',
    'Compresor de Estructuras SVG Embebidas',
    'Optimizador de Prioridad de Descarga FetchPriority',
    'Controlador de Lazy-Loading de Bloques',
    'Gestor de Cabeceras de Compresión Avanzada',
    'Eliminador de JS de Bloqueo de Renderizado',
    'Inline-izador de Micro-Scripts Críticos',
    'Administrador de Estado de Cache Inmune',
    'Filtro de Parámetros de URL Basura',
    'Optimizador de Relación de Aspecto en Imágenes',
    'Gestor de Cabeceras de Seguridad Avanzada',
    'Reescritor de Fuentes Web a Formatos Modernos',
    'Purgador de Fragmentos de Código Muerto',
    'Controlador de Variaciones de Agente de Usuario',
    'Inyector de Tags No-Translate',
    'Normalizador de Redirecciones Internas Directas',
    'Validador de Tamaño de Carga Útil HTML',
    'Inyector de Datos de Geolocalización Cabeceras',
    'Optimizador de Tiempos de Respuesta Servidor',
    'Detector de Elementos Ocultos por CSS',
    'Controlador de Cabeceras Vary Mobile',
    'Reductor de Anidación Excesiva de Divs',
    'Programador de Precarga de Secciones Críticas',
    'Validador End-to-End de Velocidad de Salida',
    'Matriz de Coincidencia de Palabras Clave y URLs',
    'Detector de Conflicto de Vectores Semánticos',
    'Gestor Atómico de Enlaces de Consolidación',
    'Consolidador de Historial de Slugs Cambiados',
    'Calculador de Peso de Página por Enlaces',
    'Filtro de Exclusión de Páginas Bajo Valor',
    'Indexador de Variaciones de Idioma por Región',
    'Monitor de Modificaciones Estructurales Caliente',
    'Validador de Unicidad de Títulos H1',
    'Agrupador de Metadatos de Autoría Conectada',
    'Gestor de Bloqueos de Concurrencia Escritura',
    'Limpiador de Registros Inactivos por Desuso',
    'Verificador de Consistencia entre Sitemaps y DB',
    'Agrupador de Consultas Semánticas Masivas',
    'Evaluador de Estabilidad de Base de Datos',
    'Indexador de Coincidencias de Entidades Marca',
    'Analizador de Longitud de Cadenas de URL',
    'Gestor de Variaciones de Contenido Estacional',
    'Validador de Codificación Segura de Slugs',
    'Controlador de Estado de Verificación Integridad',
    'Puntuador de Crecimiento de Grafo Interno',
    'Agrupador de Categorías por Intención Compra',
    'Monitor de Transacciones Saint-Lock en Colas',
    'Extractor de Entidades Relevantes E-commerce',
    'Generador de Firmas Únicas Estructuras Schema',
    'Validador Estricto de Directrices de Googlebot',
    'Detector de Patrones de Cloaking Automatizado',
    'Controlador de Respuestas de Error Seguras',
    'Verificador de Coincidencia de Tokens Edge',
    'Generador de Respuestas HTTP 503 Limpias',
    'Sanitizador de Cabeceras HTTP Expuestas',
    'Monitor de Tiempos de Respuesta Transformación',
    'Evaluador de Respuestas de Servidores Origen',
    'Validador de Dominios Autorizados Destino',
    'Inyector de Cabecera de Suite Certificada',
    'Filtro de Parámetros Duplicados Peticiones',
    'Analizador de Respuestas de Redirección Limpias',
    'Validador de Esquemas JSON-LD Homologados',
    'Gestor de Exclusiones por Directivas Robots',
    'Detector de Contenido de Relleno Artificial',
    'Controlador de Respuestas en Formato Flujo',
    'Verificador de Consistencia Estricta ID Sitio',
    'Filtro de Caracteres no Válidos Marcados',
    'Evaluador de Duplicidad Contenido Encabezados',
    'Monitor de Cuotas de Almacenamiento KV',
    'Inyector de Cabecera de Control Depuración',
    'Automatismo de Normalización de Barras Ruta',
    'Validador de Paridad de Renderizado Dispositivos',
    'Filtro de Inyecciones Semánticas Maliciosas',
    'Orquestador y Certificador de Cierre Ciclo',
)
FAMILIES = (
    ("EDGE_STRUCTURAL", "edge_html_records", 1201, 1225),
    ("SEMANTIC_GRAPH", "semantic_text_records", 1226, 1250),
    ("PERSISTENCE_STATE", "persistence_state_records", 1251, 1275),
    ("EDGE_GATEWAY", "edge_gateway_records", 1276, 1300),
    ("SEARCH_INTENT", "search_intent_records", 1301, 1325),
    ("CORE_WEB_VITALS", "cwv_edge_records", 1326, 1350),
    ("CANONICALIZATION", "canonicalization_records", 1351, 1375),
    ("POLICY_COMPLIANCE", "policy_audit_records", 1376, 1400),
)
TARGET_NUMBERS = tuple(range(215, 301)) + tuple(range(317, 401)) + tuple(range(409, 439))

def _slug(value: str) -> str:
    ascii_value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii").lower()
    return re.sub(r"[^a-z0-9]+", "_", ascii_value).strip("_")

def _family_for(source_number: int) -> Tuple[str, str]:
    for family, dataset_key, start, end in FAMILIES:
        if start <= source_number <= end:
            return family, dataset_key
    raise ValueError(source_number)

MASS_LOT_SPECS: Dict[str, Tuple[str, str, str, str, str]] = {}
for offset, (target_number, source_name) in enumerate(zip(TARGET_NUMBERS, SOURCE_NAMES)):
    source_number = 1201 + offset
    family, dataset_key = _family_for(source_number)
    target_id = f"M{target_number}"
    source_id = f"M{source_number}"
    MASS_LOT_SPECS[target_id] = (source_id, source_name, family, dataset_key, _slug(source_name))

MASS_LOT_TARGET_MODULES = frozenset(MASS_LOT_SPECS)
MASS_LOT_SOURCE_MODULES = tuple(spec[0] for spec in MASS_LOT_SPECS.values())

def source_to_target_map() -> Dict[str, str]:
    return {source_id: target_id for target_id, (source_id, *_rest) in MASS_LOT_SPECS.items()}
