export const MAX_ORIGINALITY_MANIFOLD_POINTS = 256;
export const MAX_ORIGINALITY_K_NEIGHBORS = 32;
export const MAX_ORIGINALITY_COUNTERFACTUAL_ALTERNATIVES = 64;
export const MAX_ORIGINALITY_GEODESIC_NODES = MAX_ORIGINALITY_MANIFOLD_POINTS + 1;
export const MAX_ORIGINALITY_GEODESIC_EDGES = 32_768;
