export const MAX_ORIGINALITY_MANIFOLD_POINTS = 512;
export const MAX_ORIGINALITY_K_NEIGHBORS = 64;
export const MAX_ORIGINALITY_COUNTERFACTUAL_ALTERNATIVES = 128;
export const MAX_ORIGINALITY_GEODESIC_NODES = MAX_ORIGINALITY_MANIFOLD_POINTS + 1;
export const MAX_ORIGINALITY_GEODESIC_EDGES = 65_536;
