import type { NexusTheme } from "@nexus/core/foundation/theme";

export const probeTheme: NexusTheme = {
  "space.xs": "0.5rem",
  "space.sm": "1rem",
  "space.md": "1.5rem",
  "space.lg": "3rem",
  "space.xl": "6rem",
  "container.sm": "36rem",
  "container.md": "52rem",
  "container.lg": "72rem",
  "container.xl": "92rem",
  "focus.ring": "#b34d2f",
  "focus.offset": "3px",
  "motion.duration.instant": "0ms",
  "motion.duration.fast": "160ms",
  "motion.duration.base": "360ms",
  "motion.duration.slow": "760ms",
  "motion.easing.standard": "ease",
  "motion.easing.decelerate": "cubic-bezier(0.16,1,0.3,1)",
  "motion.easing.accelerate": "cubic-bezier(0.7,0,0.84,0)",
  "motion.easing.linear": "linear",
  "surface.base": "#f2efe8",
  "surface.elevated": "#fffdf7",
  "surface.inverse": "#171713",
  "surface.overlay": "rgba(23,23,19,.25)",
  "content.primary": "#171713",
  "content.secondary": "#625e54",
  "content.inverse": "#f2efe8",
  "content.disabled": "#aaa397",
  "accent.default": "#b34d2f",
  "accent.emphasis": "#7d2e1d",
  "accent.muted": "#dfb8aa",
  "border.subtle": "rgba(23,23,19,.16)",
  "border.strong": "rgba(23,23,19,.55)",
  "radius.sm": "0px",
  "radius.md": "0px",
  "radius.lg": "0px",
  "radius.full": "999px",
};
