import { Buffer } from "node:buffer";
import { canonicalJson, digest } from "./index";
import { requestPinnedPublicUrl, resolvePublicAddress, type LookupPublic } from "./competitive-public-http";
import { validateCompetitiveScope, type CompetitiveScope } from "./competitive-intelligence";

const MAX_QUOTES = 100;
const MAX_BODY_BYTES = 2_000_000;
const MAX_TIMEOUT_MS = 30_000;
const MAX_REDIRECTS = 3;
const livePricingObservations = new WeakSet<object>();

type FetchLike = (input: string | URL | Request, init?: RequestInit) => Promise<Response>;
export type PricingAuthority = "PUBLIC_HTTP_CAPTURE" | "CONTROLLED_TEST";
export interface PricingQuote { readonly amountMinor: number; readonly currency: string; readonly evidence: string }
export interface PricingObservation { readonly scope: CompetitiveScope; readonly url: string; readonly finalUrl: string; readonly observedAt: string; readonly authority: PricingAuthority; readonly quotes: readonly PricingQuote[]; readonly bodyDigest: string; readonly observationDigest: string }
export interface PricingReport { readonly formatVersion: "nexus-pricing-intelligence-v1"; readonly scope: CompetitiveScope; readonly subjectId: string; readonly evidenceState: "OBSERVED_PUBLIC_HTTP" | "SYNTHETIC"; readonly nonClaim: "PUBLIC_PRICE_OBSERVATION_NOT_TRANSACTION_MARKET_PRICE_OR_BUSINESS_OUTCOME"; readonly quotes: readonly PricingQuote[]; readonly sourceDigest: string; readonly reportDigest: string }

function clean(label: string, value: string, max: number): string { if (typeof value !== "string") throw new Error(`${label} must be a string`); const out = value.normalize("NFKC").replace(/\s+/gu, " ").trim(); if (!out || out.length > max) throw new Error(`${label} must be non-empty and <= ${max} characters`); return out; }
function canonicalTime(value: string): string { const date = new Date(value); if (!Number.isFinite(date.getTime()) || date.toISOString() !== value) throw new Error("observedAt must be canonical ISO-8601 UTC"); return value; }
function normalizeUrl(value: string): string { const parsed = new URL(clean("URL", value, 4096)); if (!/^https?:$/u.test(parsed.protocol) || parsed.username || parsed.password || parsed.hostname === "localhost" || parsed.hostname.endsWith(".localhost")) throw new Error("pricing URL must be public HTTP(S) without credentials"); parsed.hash = ""; return parsed.toString(); }
function normalizeQuote(input: PricingQuote): PricingQuote { if (!Number.isSafeInteger(input.amountMinor) || input.amountMinor < 0 || input.amountMinor > 1_000_000_000_000) throw new Error("amountMinor must be a bounded non-negative safe integer"); const currency = clean("currency", input.currency, 3).toUpperCase(); if (!/^[A-Z]{3}$/u.test(currency)) throw new Error("currency must be ISO-4217 shaped"); return Object.freeze({ amountMinor: input.amountMinor, currency, evidence: clean("evidence", input.evidence, 240) }); }
function buildObservation(input: Omit<PricingObservation, "observationDigest">): PricingObservation { const scope = validateCompetitiveScope(input.scope); if (input.authority !== "PUBLIC_HTTP_CAPTURE" && input.authority !== "CONTROLLED_TEST") throw new Error("unknown pricing authority"); if (!Array.isArray(input.quotes) || input.quotes.length > MAX_QUOTES) throw new Error(`quotes must contain at most ${MAX_QUOTES} entries`); const quotes = Object.freeze(input.quotes.map(normalizeQuote).sort((a,b)=>a.currency.localeCompare(b.currency,"en")||a.amountMinor-b.amountMinor||a.evidence.localeCompare(b.evidence,"en"))); if (!/^[a-f0-9]{64}$/u.test(input.bodyDigest)) throw new Error("bodyDigest must be sha256 hex"); const core = { scope, url: normalizeUrl(input.url), finalUrl: normalizeUrl(input.finalUrl), observedAt: canonicalTime(input.observedAt), authority: input.authority, quotes, bodyDigest: input.bodyDigest }; return Object.freeze({ ...core, observationDigest: digest(core) }); }
export function createControlledPricingObservation(input: Omit<PricingObservation,"authority"|"observationDigest">): PricingObservation { return buildObservation({ ...input, authority: "CONTROLLED_TEST" }); }
export function validatePricingObservation(observation: PricingObservation): void { const { observationDigest, ...core } = observation; const rebuilt = buildObservation(core); if (rebuilt.observationDigest !== observationDigest || canonicalJson(rebuilt) !== canonicalJson(observation)) throw new Error("pricing observation replay mismatch"); if (observation.authority === "PUBLIC_HTTP_CAPTURE" && !livePricingObservations.has(observation)) throw new Error("public pricing observation is not live-attested in this process"); }
function extractQuotes(html: string): readonly PricingQuote[] { const text = html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/giu," ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/giu," ").replace(/<[^>]+>/gu," ").replace(/\s+/gu," "); const regex = /(?:\b(USD|EUR|MXN|GBP|CAD)\b\s*|([$€£])\s*)(\d{1,9}(?:[.,]\d{1,2})?)/giu; const seen = new Set<string>(); const out: PricingQuote[] = []; for (const match of text.matchAll(regex)) { if (out.length >= MAX_QUOTES) break; const currency = (match[1]?.toUpperCase() ?? ({"$":"USD","€":"EUR","£":"GBP"}[match[2] ?? ""])); if (!currency) continue; const raw = match[3]!.replace(",", "."); const value = Number(raw); if (!Number.isFinite(value) || value < 0) continue; const amountMinor = Math.round(value * 100); const evidence = match[0]!.slice(0,240).normalize("NFKC"); const key = `${currency}:${amountMinor}:${evidence}`; if (!seen.has(key)) { seen.add(key); out.push({ amountMinor, currency, evidence }); } } return Object.freeze(out); }
async function readBody(response: Response, signal: AbortSignal): Promise<string> { const length = Number(response.headers.get("content-length") ?? "0"); if (Number.isFinite(length) && length > MAX_BODY_BYTES) throw new Error("pricing capture body exceeds byte budget"); const reader = response.body?.getReader(); if (!reader) throw new Error("pricing capture response has no body"); const chunks: Uint8Array[] = []; let total = 0; while (true) { if (signal.aborted) throw signal.reason instanceof Error ? signal.reason : new Error("pricing capture cancelled"); const part = await reader.read(); if (part.done) break; total += part.value.byteLength; if (total > MAX_BODY_BYTES) { await reader.cancel(); throw new Error("pricing capture body exceeds byte budget"); } chunks.push(part.value); } return Buffer.concat(chunks.map((chunk)=>Buffer.from(chunk))).toString("utf8"); }
export async function capturePublicPricing(url: string, observedAt: string, options: Readonly<{ scope: CompetitiveScope; timeoutMs?: number; signal?: AbortSignal; fetchImpl?: FetchLike; lookup?: LookupPublic }>): Promise<PricingObservation> { const scope = validateCompetitiveScope(options.scope); const timeoutMs = options.timeoutMs ?? 10_000; if (!Number.isInteger(timeoutMs) || timeoutMs < 100 || timeoutMs > MAX_TIMEOUT_MS) throw new Error("timeoutMs must be an integer from 100 to 30000"); const initialUrl = normalizeUrl(url); canonicalTime(observedAt); const controller = new AbortController(); const forward = () => controller.abort(options.signal?.reason); if (options.signal?.aborted) controller.abort(options.signal.reason); else options.signal?.addEventListener("abort", forward, { once:true }); const timer = setTimeout(()=>controller.abort(new Error("pricing capture timeout")), timeoutMs); const controlled = Boolean(options.fetchImpl || options.lookup); let current = initialUrl; try { for (let redirect=0; redirect<=MAX_REDIRECTS; redirect+=1) { if (controller.signal.aborted) throw controller.signal.reason instanceof Error ? controller.signal.reason : new Error("pricing capture cancelled"); let response: Response; if (controlled) { await resolvePublicAddress(current, options.lookup, controller.signal); response = await (options.fetchImpl ?? fetch)(current,{method:"GET",redirect:"manual",signal:controller.signal}); } else response = await requestPinnedPublicUrl(current, controller.signal); if (response.status >= 300 && response.status < 400) { const location = response.headers.get("location"); if (!location || redirect === MAX_REDIRECTS) throw new Error("pricing redirect rejected"); current = normalizeUrl(new URL(location,current).toString()); continue; } if (response.status < 200 || response.status > 299) throw new Error(`pricing capture returned HTTP ${response.status}`); const body = await readBody(response, controller.signal); const observation = buildObservation({ scope, url: initialUrl, finalUrl: current, observedAt, authority: controlled ? "CONTROLLED_TEST" : "PUBLIC_HTTP_CAPTURE", quotes: extractQuotes(body), bodyDigest: digest(body) }); if (!controlled) livePricingObservations.add(observation); return observation; } throw new Error("unreachable pricing redirect state"); } finally { clearTimeout(timer); options.signal?.removeEventListener("abort", forward); } }
export function analyzePricingIntelligence(scopeInput: CompetitiveScope, subjectIdInput: string, observation: PricingObservation): PricingReport { const scope = validateCompetitiveScope(scopeInput); const subjectId = clean("subjectId",subjectIdInput,200); validatePricingObservation(observation); if (canonicalJson(scope) !== canonicalJson(observation.scope)) throw new Error("pricing observation scope mismatch"); const core = { formatVersion:"nexus-pricing-intelligence-v1" as const, scope, subjectId, evidenceState: observation.authority === "PUBLIC_HTTP_CAPTURE" ? "OBSERVED_PUBLIC_HTTP" as const : "SYNTHETIC" as const, nonClaim:"PUBLIC_PRICE_OBSERVATION_NOT_TRANSACTION_MARKET_PRICE_OR_BUSINESS_OUTCOME" as const, quotes: observation.quotes, sourceDigest: observation.observationDigest }; return Object.freeze({ ...core, reportDigest:digest(core) }); }
export function verifyPricingIntelligence(scope: CompetitiveScope, subjectId: string, observation: PricingObservation, report: PricingReport): boolean { try { return canonicalJson(analyzePricingIntelligence(scope,subjectId,observation)) === canonicalJson(report); } catch { return false; } }
