import { timingSafeEqual } from "node:crypto";
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import type { OntologyScope } from "@nexus/ontology";
import type { OntologyTransactionPort } from "@nexus/ontology/transaction";
import {
  ProgrammaticSeoEngine,
  ProgrammaticSeoError,
  createProgrammaticSeoPolicy,
  validateProgrammaticSeoBundle,
  type CreateProgrammaticSeoPolicyInput,
  type ProgrammaticSeoBundle,
  type ProgrammaticSeoBundleRef,
  type ProgrammaticSeoCatalogProvider,
  type ProgrammaticSeoMode,
  type ProgrammaticSeoPolicy,
  type ProgrammaticSeoPublishAction,
  type ProgrammaticSeoPublisher,
  type ProgrammaticSeoResult,
} from "./index";
import { ProgrammaticSeoRuntimeControlError, ProgrammaticSeoRuntimeController } from "./runtime-control";

const MAX_BODY_BYTES = 16_384;
const IDENTIFIER = /^[A-Za-z0-9](?:[A-Za-z0-9._:-]{0,127})$/u;
const POLICY_KEYS = new Set(["policyId","version","maxCatalogAgeMs","maxPages","minDistinctiveStatements","maxPairwiseShingleSimilarity","maxRouteDepth","maxWriteRetries","mode"]);

export interface ProgrammaticSeoProductionConfig { readonly version: 1; readonly scope: OntologyScope; readonly intervalMs: number; readonly siteId: string; readonly baseUrl: string; readonly policy: CreateProgrammaticSeoPolicyInput }
export interface ProgrammaticSeoRuntimeTelemetryEvent { readonly operation: "CYCLE"|"ROLLBACK"|"CONTROL_READ"|"CONTROL_WRITE"|"BUNDLE_READ"|"HEALTH"; readonly status: "OK"|"FAILED"; readonly trigger: "STARTUP"|"SCHEDULED"|"MANUAL"|null; readonly mode: ProgrammaticSeoMode|null; readonly reason: string|null; readonly durationMs: number; readonly errorCode: string|null }
export interface ProgrammaticSeoProductionRuntimeOptions { readonly transactions: OntologyTransactionPort; readonly config: ProgrammaticSeoProductionConfig; readonly catalog: ProgrammaticSeoCatalogProvider; readonly publisher: ProgrammaticSeoPublisher; readonly runToken: string; readonly controlToken: string; readonly bundleToken: string; readonly now?:()=>number; readonly onTelemetry?:(event:ProgrammaticSeoRuntimeTelemetryEvent)=>void; readonly onTelemetryError?:(error:unknown)=>void }
export interface ProgrammaticSeoProductionRuntime { readonly server: Server; readonly policy: ProgrammaticSeoPolicy; runOnce(trigger:"STARTUP"|"SCHEDULED"|"MANUAL"):Promise<ProgrammaticSeoResult>; start(runImmediately?:boolean):void; close():Promise<void> }

class HttpError extends Error { constructor(readonly status:number,readonly code:string){super(code);this.name="ProgrammaticSeoProductionHttpError";} }
function object(value:unknown,label:string):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error(`${label} must be an object`);const proto=Object.getPrototypeOf(value);if(proto!==Object.prototype&&proto!==null)throw new Error(`${label} must be a plain object`);return value as Record<string,unknown>;}
function exact(value:Record<string,unknown>,allowed:ReadonlySet<string>,label:string):void{for(const key of Object.keys(value))if(!allowed.has(key))throw new Error(`${label} contains unknown field ${key}`);}
function id(value:unknown,label:string):string{if(typeof value!=="string"||!IDENTIFIER.test(value.trim()))throw new Error(`${label} is malformed`);return value.trim();}
function httpsBase(value:unknown,label:string):string{if(typeof value!=="string")throw new Error(`${label} must be a string`);let url:URL;try{url=new URL(value);}catch{throw new Error(`${label} must be an absolute URL`);}if(url.protocol!=="https:"||url.username||url.password||url.search||url.hash)throw new Error(`${label} must be clean HTTPS`);url.pathname=url.pathname.replace(/\/+$/u,"")+"/";return url.toString();}
function scopeFrom(value:unknown):OntologyScope{const raw=object(value,"scope");exact(raw,new Set(["tenantId","organizationId","brandId"]),"scope");const tenantId=id(raw.tenantId,"scope.tenantId");const organizationId=id(raw.organizationId,"scope.organizationId");return Object.freeze({tenantId,organizationId,...(raw.brandId===undefined?{}:{brandId:id(raw.brandId,"scope.brandId")})});}
function policyFrom(value:unknown):CreateProgrammaticSeoPolicyInput{const raw=object(value,"policy");exact(raw,POLICY_KEYS,"policy");const input=raw as unknown as CreateProgrammaticSeoPolicyInput;createProgrammaticSeoPolicy(input);return input;}
export function parseProgrammaticSeoProductionConfig(value:unknown):ProgrammaticSeoProductionConfig{const raw=object(value,"programmatic SEO production config");exact(raw,new Set(["version","scope","intervalMs","siteId","baseUrl","policy"]),"programmatic SEO production config");if(raw.version!==1)throw new Error("programmatic SEO production config version must be 1");if(!Number.isSafeInteger(raw.intervalMs)||(raw.intervalMs as number)<300_000||(raw.intervalMs as number)>86_400_000)throw new Error("intervalMs must be 300000..86400000");return Object.freeze({version:1,scope:scopeFrom(raw.scope),intervalMs:raw.intervalMs as number,siteId:id(raw.siteId,"siteId"),baseUrl:httpsBase(raw.baseUrl,"baseUrl"),policy:policyFrom(raw.policy)});}
function token(value:string,label:string):Buffer{if(typeof value!=="string"||value.trim().length<32||value.trim().length>4096)throw new Error(`${label} must contain 32..4096 characters`);return Buffer.from(value.trim(),"utf8");}
function auth(request:IncomingMessage,expected:Buffer):boolean{const raw=request.headers.authorization;if(typeof raw!=="string"||!raw.startsWith("Bearer "))return false;const candidate=Buffer.from(raw.slice(7),"utf8");return candidate.length===expected.length&&timingSafeEqual(candidate,expected);}
async function body(request:IncomingMessage):Promise<Record<string,unknown>>{if(request.headers["content-type"]?.split(";",1)[0]?.trim().toLowerCase()!=="application/json")throw new HttpError(415,"JSON_REQUIRED");let bytes=0;const chunks:Buffer[]=[];for await(const part of request){const chunk=Buffer.isBuffer(part)?part:Buffer.from(part);bytes+=chunk.byteLength;if(bytes>MAX_BODY_BYTES){request.resume();throw new HttpError(413,"BODY_TOO_LARGE");}chunks.push(chunk);}if(!bytes)throw new HttpError(400,"BODY_REQUIRED");let parsed:unknown;try{parsed=JSON.parse(Buffer.concat(chunks).toString("utf8")) as unknown;}catch{throw new HttpError(400,"INVALID_JSON");}try{return object(parsed,"request body");}catch{throw new HttpError(400,"INVALID_BODY");}}
function requestExact(value:Record<string,unknown>,allowed:readonly string[]):void{for(const key of Object.keys(value))if(!allowed.includes(key))throw new HttpError(400,"INVALID_BODY");}
function write(response:ServerResponse,status:number,value:unknown):void{const raw=JSON.stringify(value);response.statusCode=status;response.setHeader("content-type","application/json; charset=utf-8");response.setHeader("cache-control","no-store");response.setHeader("content-length",Buffer.byteLength(raw));response.end(raw);}
function statusFor(error:unknown):number{if(error instanceof HttpError)return error.status;if(error instanceof ProgrammaticSeoRuntimeControlError)return error.code==="CONFLICT"?409:error.code==="PERSISTENCE_FAILURE"||error.code==="INTEGRITY_FAILURE"?503:400;if(error instanceof ProgrammaticSeoError)return error.code==="CONFLICT"?409:error.code==="PERSISTENCE_FAILURE"||error.code==="INTEGRITY_FAILURE"||error.code==="REMOTE_FAILURE"?503:400;return 500;}
function codeFor(error:unknown):string{if(error instanceof HttpError)return error.code;if(error instanceof ProgrammaticSeoRuntimeControlError||error instanceof ProgrammaticSeoError)return error.code;return "UNEXPECTED";}

export function createProgrammaticSeoProductionRuntime(options:ProgrammaticSeoProductionRuntimeOptions):ProgrammaticSeoProductionRuntime{
  const runToken=token(options.runToken,"runToken");const controlToken=token(options.controlToken,"controlToken");const bundleToken=token(options.bundleToken,"bundleToken");for(const [left,right,label] of [[runToken,controlToken,"runToken/controlToken"],[runToken,bundleToken,"runToken/bundleToken"],[controlToken,bundleToken,"controlToken/bundleToken"]] as const){if(left.length===right.length&&timingSafeEqual(left,right))throw new Error(`${label} must be distinct`);}
  const now=options.now??Date.now;const policy=createProgrammaticSeoPolicy(options.config.policy);const control=new ProgrammaticSeoRuntimeController(options.transactions,options.config.scope,policy.digest,policy.mode,now);let rollbackAuthorized=false;let safetyOperation=false;let cycle:Promise<ProgrammaticSeoResult>|null=null;let interval:ReturnType<typeof setInterval>|null=null;
  const emit=(event:ProgrammaticSeoRuntimeTelemetryEvent)=>{try{options.onTelemetry?.(Object.freeze(event));}catch(error){try{options.onTelemetryError?.(error);}catch{/* telemetry is non-authoritative */}}};
  const guardedPublisher:ProgrammaticSeoPublisher=Object.freeze({stage:(bundle:ProgrammaticSeoBundle)=>options.publisher.stage(bundle),load:(ref:ProgrammaticSeoBundleRef)=>options.publisher.load(ref),read:(siteId:string)=>options.publisher.read(siteId),apply:async(action:ProgrammaticSeoPublishAction)=>{const effective=control.effectiveMode();if(!rollbackAuthorized&&effective!=="ACTIVE")throw new ProgrammaticSeoError("POLICY_VIOLATION",`${effective} blocks bundle publish`);return options.publisher.apply(action);}});
  const engine=new ProgrammaticSeoEngine(options.transactions,options.config.scope,policy,options.catalog,guardedPublisher,now);
  const runCycle=async(trigger:"STARTUP"|"SCHEDULED"|"MANUAL"):Promise<ProgrammaticSeoResult>=>{if(safetyOperation)throw new ProgrammaticSeoError("CONFLICT","rollback safety operation is running");if(cycle)return cycle;const started=now();const bucket=Math.floor(now()/options.config.intervalMs);const promise=engine.build({runId:`programmatic-${options.config.siteId}-${bucket}`,siteId:options.config.siteId,mode:control.effectiveMode()});cycle=promise;try{const result=await promise;emit({operation:"CYCLE",status:"OK",trigger,mode:result.mode,reason:result.reason,durationMs:Math.max(0,now()-started),errorCode:null});return result;}catch(error){emit({operation:"CYCLE",status:"FAILED",trigger,mode:control.effectiveMode(),reason:null,durationMs:Math.max(0,now()-started),errorCode:codeFor(error)});throw error;}finally{cycle=null;}};
  const rollback=async(runIdValue:string):Promise<ProgrammaticSeoResult>=>{if(cycle||safetyOperation)throw new ProgrammaticSeoError("CONFLICT","another programmatic SEO operation is running");safetyOperation=true;rollbackAuthorized=true;const started=now();try{const result=await engine.rollbackLastMutation({runId:id(runIdValue,"runId"),siteId:options.config.siteId});emit({operation:"ROLLBACK",status:"OK",trigger:null,mode:control.effectiveMode(),reason:result.reason,durationMs:Math.max(0,now()-started),errorCode:null});return result;}catch(error){emit({operation:"ROLLBACK",status:"FAILED",trigger:null,mode:control.effectiveMode(),reason:null,durationMs:Math.max(0,now()-started),errorCode:codeFor(error)});throw error;}finally{rollbackAuthorized=false;safetyOperation=false;}};
  const server=createServer(async(request,response)=>{const started=now();try{const method=request.method??"GET";const url=new URL(request.url??"/","http://cortex.invalid");if(method==="GET"&&url.pathname==="/healthz"){const state=control.current();write(response,200,{ok:true,mode:control.effectiveMode(),revision:state.revision});emit({operation:"HEALTH",status:"OK",trigger:null,mode:control.effectiveMode(),reason:null,durationMs:Math.max(0,now()-started),errorCode:null});return;}
    if(method==="POST"&&url.pathname==="/v1/programmatic-seo/run"){if(!auth(request,runToken))throw new HttpError(401,"UNAUTHORIZED");const input=await body(request);requestExact(input,[]);write(response,200,{result:await runCycle("MANUAL")});return;}
    if(method==="GET"&&url.pathname==="/v1/programmatic-seo/control"){if(!auth(request,controlToken))throw new HttpError(401,"UNAUTHORIZED");write(response,200,{state:control.current(),effectiveMode:control.effectiveMode(),configuredMode:control.configuredMode,currentPolicyDigest:control.policyDigest,history:control.history(64)});emit({operation:"CONTROL_READ",status:"OK",trigger:null,mode:control.effectiveMode(),reason:null,durationMs:Math.max(0,now()-started),errorCode:null});return;}
    if(method==="POST"&&url.pathname==="/v1/programmatic-seo/control"){if(!auth(request,controlToken))throw new HttpError(401,"UNAUTHORIZED");const input=await body(request);requestExact(input,["expectedRevision","mode","reason","changedAt"]);if(typeof input.expectedRevision!=="number"||typeof input.mode!=="string"||typeof input.reason!=="string"||(input.changedAt!==undefined&&typeof input.changedAt!=="string"))throw new HttpError(400,"INVALID_BODY");const state=control.set({expectedRevision:input.expectedRevision,mode:input.mode as ProgrammaticSeoMode,reason:input.reason,...(input.changedAt===undefined?{}:{changedAt:input.changedAt})});write(response,200,{state,effectiveMode:control.effectiveMode()});emit({operation:"CONTROL_WRITE",status:"OK",trigger:null,mode:state.mode,reason:state.reason,durationMs:Math.max(0,now()-started),errorCode:null});return;}
    if(method==="POST"&&url.pathname==="/v1/programmatic-seo/rollback"){if(!auth(request,controlToken))throw new HttpError(401,"UNAUTHORIZED");const input=await body(request);requestExact(input,["runId"]);if(typeof input.runId!=="string")throw new HttpError(400,"INVALID_BODY");write(response,200,{result:await rollback(input.runId)});return;}
    if(method==="GET"&&url.pathname==="/v1/programmatic-seo/bundle"){if(!auth(request,bundleToken))throw new HttpError(401,"UNAUTHORIZED");for(const key of url.searchParams.keys())if(key!=="siteId")throw new HttpError(400,"INVALID_QUERY");if(url.searchParams.get("siteId")!==options.config.siteId)throw new HttpError(400,"INVALID_QUERY");const current=await options.publisher.read(options.config.siteId);if(!current){write(response,404,{error:"NO_BUNDLE"});return;}const bundle:ProgrammaticSeoBundle=await options.publisher.load(current.bundleRef);validateProgrammaticSeoBundle(bundle);if(bundle.siteId!==options.config.siteId||bundle.baseUrl!==options.config.baseUrl||bundle.digest!==current.bundleRef.bundleDigest)throw new ProgrammaticSeoError("INTEGRITY_FAILURE","published bundle identity mismatch");write(response,200,{siteId:options.config.siteId,published:current,bundle});emit({operation:"BUNDLE_READ",status:"OK",trigger:null,mode:control.effectiveMode(),reason:null,durationMs:Math.max(0,now()-started),errorCode:null});return;}write(response,404,{error:"NOT_FOUND"});
  }catch(error){const status=statusFor(error);if(!response.headersSent&&!response.writableEnded)write(response,status,{error:codeFor(error)});}});
  return Object.freeze({server,policy,runOnce:runCycle,start:(runImmediately=true)=>{if(interval)return;if(runImmediately)void runCycle("STARTUP").catch(()=>undefined);interval=setInterval(()=>{void runCycle("SCHEDULED").catch(()=>undefined);},options.config.intervalMs);interval.unref?.();},close:()=>new Promise<void>((resolve,reject)=>{if(interval){clearInterval(interval);interval=null;}if(!server.listening){resolve();return;}server.close(error=>error?reject(error):resolve());})});
}