import { timingSafeEqual } from "node:crypto";
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import type { OntologyScope } from "@nexus/ontology";
import type { OntologyTransactionPort } from "@nexus/ontology/transaction";
import {
  SerpMetadataOptimizer,
  SerpMetadataOptimizerError,
  createSerpMetadataPolicy,
  type CreateSerpMetadataPolicyInput,
  type MetadataPublishAction,
  type MetadataPublisher,
  type PageInventoryProvider,
  type SearchPerformanceProvider,
  type SerpMetadataMode,
  type SerpMetadataPolicy,
  type SerpMetadataResult,
} from "./index";
import { SerpRuntimeController, SerpRuntimeControlError } from "./runtime-control";

const MAX_BODY_BYTES = 16_384;
const IDENTIFIER = /^[A-Za-z0-9](?:[A-Za-z0-9._:-]{0,127})$/u;
const POLICY_KEYS = new Set(["policyId","version","maxInventoryAgeMs","maxPerformanceAgeMs","cooldownMs","maxWindowDays","minImpressions","minExpectedClicksGain","minPeerPages","peerPositionTolerance","minDescriptionQueryCoverageDelta","maxGeneratedTitleCharacters","maxGeneratedDescriptionCharacters","maxInventoryPages","maxSearchRows","maxWriteRetries","mode"]);

export interface SerpProductionPage { readonly pageId: string; readonly pageUrl: string }
export interface SerpProductionConfig { readonly version: 1; readonly scope: OntologyScope; readonly intervalMs: number; readonly observationWindowDays: number; readonly reportingLagDays: number; readonly siteUrl: string; readonly policy: CreateSerpMetadataPolicyInput; readonly pages: readonly SerpProductionPage[] }
export interface SerpRuntimeTelemetryEvent { readonly operation: "CYCLE"|"PAGE"|"ROLLBACK"|"CONTROL_READ"|"CONTROL_WRITE"|"METADATA_READ"|"HEALTH"; readonly status: "OK"|"FAILED"|"SKIPPED"|"REJECTED"; readonly trigger: "STARTUP"|"SCHEDULED"|"MANUAL"|null; readonly pageId: string|null; readonly mode: SerpMetadataMode|null; readonly reason: string|null; readonly durationMs: number; readonly errorCode: string|null }
export interface SerpProductionRuntimeOptions { readonly transactions: OntologyTransactionPort; readonly config: SerpProductionConfig; readonly inventory: PageInventoryProvider; readonly performance: SearchPerformanceProvider; readonly publisher: MetadataPublisher; readonly runToken: string; readonly controlToken: string; readonly metadataToken: string; readonly now?:()=>number; readonly onTelemetry?:(event:SerpRuntimeTelemetryEvent)=>void; readonly onTelemetryError?:(error:unknown)=>void }
export interface SerpProductionRuntime { readonly server: Server; readonly policy: SerpMetadataPolicy; runOnce(trigger:"STARTUP"|"SCHEDULED"|"MANUAL", pageId?:string):Promise<readonly SerpMetadataResult[]>; start(runImmediately?:boolean):void; close():Promise<void> }

class HttpError extends Error { constructor(readonly status:number,readonly code:string){super(code);this.name="SerpProductionHttpError";} }
function object(value:unknown,label:string):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error(`${label} must be an object`);const proto=Object.getPrototypeOf(value);if(proto!==Object.prototype&&proto!==null)throw new Error(`${label} must be a plain object`);return value as Record<string,unknown>;}
function exact(value:Record<string,unknown>,allowed:ReadonlySet<string>,label:string):void{for(const key of Object.keys(value))if(!allowed.has(key))throw new Error(`${label} contains unknown field ${key}`);}
function id(value:unknown,label:string):string{if(typeof value!=="string"||!IDENTIFIER.test(value.trim()))throw new Error(`${label} is malformed`);return value.trim();}
function httpsUrl(value:unknown,label:string):string{if(typeof value!=="string")throw new Error(`${label} must be a string`);let url:URL;try{url=new URL(value);}catch{throw new Error(`${label} must be an absolute URL`);}if(url.protocol!=="https:"||url.username||url.password||url.hash)throw new Error(`${label} must be credential-free HTTPS`);return url.toString();}
function scopeFrom(value:unknown):OntologyScope{const raw=object(value,"scope");exact(raw,new Set(["tenantId","organizationId","brandId"]),"scope");const tenantId=id(raw.tenantId,"scope.tenantId");const organizationId=id(raw.organizationId,"scope.organizationId");return Object.freeze({tenantId,organizationId,...(raw.brandId===undefined?{}:{brandId:id(raw.brandId,"scope.brandId")})});}
function policyFrom(value:unknown):CreateSerpMetadataPolicyInput{const raw=object(value,"policy");exact(raw,POLICY_KEYS,"policy");const input=raw as unknown as CreateSerpMetadataPolicyInput;createSerpMetadataPolicy(input);return input;}
export function parseSerpProductionConfig(value:unknown):SerpProductionConfig{const raw=object(value,"SERP production config");exact(raw,new Set(["version","scope","intervalMs","observationWindowDays","reportingLagDays","siteUrl","policy","pages"]),"SERP production config");if(raw.version!==1)throw new Error("SERP production config version must be 1");if(!Number.isSafeInteger(raw.intervalMs)||(raw.intervalMs as number)<300_000||(raw.intervalMs as number)>86_400_000)throw new Error("intervalMs must be 300000..86400000");if(!Number.isSafeInteger(raw.observationWindowDays)||(raw.observationWindowDays as number)<1||(raw.observationWindowDays as number)>180)throw new Error("observationWindowDays must be 1..180");if(!Number.isSafeInteger(raw.reportingLagDays)||(raw.reportingLagDays as number)<1||(raw.reportingLagDays as number)>14)throw new Error("reportingLagDays must be 1..14");const siteUrl=httpsUrl(raw.siteUrl,"siteUrl");if(!Array.isArray(raw.pages)||raw.pages.length<1||raw.pages.length>2000)throw new Error("pages must contain 1..2000 entries");const pages=Object.freeze(raw.pages.map((entry,index)=>{const item=object(entry,`pages[${index}]`);exact(item,new Set(["pageId","pageUrl"]),`pages[${index}]`);const pageId=id(item.pageId,`pages[${index}].pageId`);const pageUrl=httpsUrl(item.pageUrl,`pages[${index}].pageUrl`);if(!pageUrl.startsWith(siteUrl))throw new Error(`pages[${index}].pageUrl is outside siteUrl`);return Object.freeze({pageId,pageUrl});}));if(new Set(pages.map(page=>page.pageId)).size!==pages.length||new Set(pages.map(page=>page.pageUrl)).size!==pages.length)throw new Error("pages must have unique pageId and pageUrl");const policy=policyFrom(raw.policy);if((raw.observationWindowDays as number)>policy.maxWindowDays)throw new Error("observationWindowDays exceeds policy maxWindowDays");return Object.freeze({version:1,scope:scopeFrom(raw.scope),intervalMs:raw.intervalMs as number,observationWindowDays:raw.observationWindowDays as number,reportingLagDays:raw.reportingLagDays as number,siteUrl,policy,pages});}
function token(value:string,label:string):Buffer{if(typeof value!=="string"||value.trim().length<32||value.trim().length>4096)throw new Error(`${label} must contain 32..4096 characters`);return Buffer.from(value.trim(),"utf8");}
function auth(request:IncomingMessage,expected:Buffer):boolean{const raw=request.headers.authorization;if(typeof raw!=="string"||!raw.startsWith("Bearer "))return false;const candidate=Buffer.from(raw.slice(7),"utf8");return candidate.length===expected.length&&timingSafeEqual(candidate,expected);}
async function body(request:IncomingMessage):Promise<Record<string,unknown>>{if(request.headers["content-type"]?.split(";",1)[0]?.trim().toLowerCase()!=="application/json")throw new HttpError(415,"JSON_REQUIRED");let bytes=0;const chunks:Buffer[]=[];for await(const part of request){const chunk=Buffer.isBuffer(part)?part:Buffer.from(part);bytes+=chunk.byteLength;if(bytes>MAX_BODY_BYTES){request.resume();throw new HttpError(413,"BODY_TOO_LARGE");}chunks.push(chunk);}if(!bytes)throw new HttpError(400,"BODY_REQUIRED");let parsed:unknown;try{parsed=JSON.parse(Buffer.concat(chunks).toString("utf8")) as unknown;}catch{throw new HttpError(400,"INVALID_JSON");}try{return object(parsed,"request body");}catch{throw new HttpError(400,"INVALID_BODY");}}
function requestExact(value:Record<string,unknown>,allowed:readonly string[]):void{for(const key of Object.keys(value))if(!allowed.includes(key))throw new HttpError(400,"INVALID_BODY");}
function write(response:ServerResponse,status:number,value:unknown):void{const raw=JSON.stringify(value);response.statusCode=status;response.setHeader("content-type","application/json; charset=utf-8");response.setHeader("cache-control","no-store");response.setHeader("content-length",Buffer.byteLength(raw));response.end(raw);}
function statusFor(error:unknown):number{if(error instanceof HttpError)return error.status;if(error instanceof SerpRuntimeControlError)return error.code==="CONFLICT"?409:error.code==="PERSISTENCE_FAILURE"||error.code==="INTEGRITY_FAILURE"?503:400;if(error instanceof SerpMetadataOptimizerError)return error.code==="CONFLICT"?409:error.code==="PERSISTENCE_FAILURE"||error.code==="INTEGRITY_FAILURE"||error.code==="REMOTE_FAILURE"?503:400;return 500;}
function codeFor(error:unknown):string{if(error instanceof HttpError)return error.code;if(error instanceof SerpRuntimeControlError||error instanceof SerpMetadataOptimizerError)return error.code;return "UNEXPECTED";}
function dateAt(ms:number):string{return new Date(ms).toISOString().slice(0,10);}
function windowFor(nowMs:number,observationWindowDays:number,reportingLagDays:number):Readonly<{startDate:string;endDate:string}>{const dayMs=86_400_000;const endDayStart=Date.parse(`${dateAt(nowMs)}T00:00:00.000Z`)-reportingLagDays*dayMs;const startDayStart=endDayStart-(observationWindowDays-1)*dayMs;return Object.freeze({startDate:dateAt(startDayStart),endDate:dateAt(endDayStart)});}

export function createSerpProductionRuntime(options:SerpProductionRuntimeOptions):SerpProductionRuntime{
  const runToken=token(options.runToken,"runToken");const controlToken=token(options.controlToken,"controlToken");const metadataToken=token(options.metadataToken,"metadataToken");for(const [left,right,label] of [[runToken,controlToken,"runToken/controlToken"],[runToken,metadataToken,"runToken/metadataToken"],[controlToken,metadataToken,"controlToken/metadataToken"]] as const){if(left.length===right.length&&timingSafeEqual(left,right))throw new Error(`${label} must be distinct`);}
  const now=options.now??Date.now;const policy=createSerpMetadataPolicy(options.config.policy);const control=new SerpRuntimeController(options.transactions,options.config.scope,policy.digest,policy.mode,now);let rollbackAuthorized=false;let safetyOperation=false;let cycle:Promise<readonly SerpMetadataResult[]>|null=null;let interval:ReturnType<typeof setInterval>|null=null;
  const emit=(event:SerpRuntimeTelemetryEvent)=>{try{options.onTelemetry?.(Object.freeze(event));}catch(error){try{options.onTelemetryError?.(error);}catch{/* telemetry is non-authoritative */}}};
  const guardedPublisher:MetadataPublisher=Object.freeze({read:(siteUrl:string,pageId:string,pageUrl:string)=>options.publisher.read(siteUrl,pageId,pageUrl),apply:async(action:MetadataPublishAction)=>{const effective=control.effectiveMode();if(!rollbackAuthorized&&effective!=="ACTIVE")throw new SerpMetadataOptimizerError("POLICY_VIOLATION",`${effective} blocks metadata publish`);return options.publisher.apply(action);}});
  const engine=new SerpMetadataOptimizer(options.transactions,options.config.scope,policy,options.inventory,options.performance,guardedPublisher,now);
  const pages=new Map(options.config.pages.map(page=>[page.pageId,page] as const));
  const runCycle=async(trigger:"STARTUP"|"SCHEDULED"|"MANUAL",only?:string):Promise<readonly SerpMetadataResult[]>=>{if(safetyOperation)throw new SerpMetadataOptimizerError("CONFLICT","rollback safety operation is running");if(cycle)return cycle;const selected=only===undefined?options.config.pages:[pages.get(id(only,"pageId"))].filter((entry):entry is SerpProductionPage=>entry!==undefined);if(only!==undefined&&selected.length===0)throw new SerpMetadataOptimizerError("POLICY_VIOLATION","pageId is not configured for SERP optimization");const started=now();const promise=(async()=>{const period=windowFor(now(),options.config.observationWindowDays,options.config.reportingLagDays);const results:SerpMetadataResult[]=[];let firstError:unknown=null;for(const page of selected){const pageStarted=now();const mode=control.effectiveMode();try{const result=await engine.optimize({runId:`serp-${page.pageId}-${period.startDate}-${period.endDate}`,siteUrl:options.config.siteUrl,pageId:page.pageId,startDate:period.startDate,endDate:period.endDate,mode});results.push(result);emit({operation:"PAGE",status:"OK",trigger,pageId:page.pageId,mode:result.mode,reason:result.reason,durationMs:Math.max(0,now()-pageStarted),errorCode:null});}catch(error){if(firstError===null)firstError=error;emit({operation:"PAGE",status:"FAILED",trigger,pageId:page.pageId,mode,reason:null,durationMs:Math.max(0,now()-pageStarted),errorCode:codeFor(error)});}}if(firstError!==null)throw firstError;return Object.freeze(results);})();cycle=promise;try{const result=await promise;emit({operation:"CYCLE",status:"OK",trigger,pageId:only??null,mode:control.effectiveMode(),reason:null,durationMs:Math.max(0,now()-started),errorCode:null});return result;}catch(error){emit({operation:"CYCLE",status:"FAILED",trigger,pageId:only??null,mode:control.effectiveMode(),reason:null,durationMs:Math.max(0,now()-started),errorCode:codeFor(error)});throw error;}finally{cycle=null;}};
  const rollback=async(pageIdValue:string,runIdValue:string):Promise<SerpMetadataResult>=>{const pageId=id(pageIdValue,"pageId");if(!pages.has(pageId))throw new SerpMetadataOptimizerError("POLICY_VIOLATION","pageId is not configured for SERP optimization");if(cycle||safetyOperation)throw new SerpMetadataOptimizerError("CONFLICT","another SERP operation is running");safetyOperation=true;rollbackAuthorized=true;const started=now();try{const result=await engine.rollbackLastMutation({runId:id(runIdValue,"runId"),siteUrl:options.config.siteUrl,pageId});emit({operation:"ROLLBACK",status:"OK",trigger:null,pageId,mode:control.effectiveMode(),reason:result.reason,durationMs:Math.max(0,now()-started),errorCode:null});return result;}catch(error){emit({operation:"ROLLBACK",status:"FAILED",trigger:null,pageId,mode:control.effectiveMode(),reason:null,durationMs:Math.max(0,now()-started),errorCode:codeFor(error)});throw error;}finally{rollbackAuthorized=false;safetyOperation=false;}};
  const server=createServer(async(request,response)=>{const started=now();try{const method=request.method??"GET";const url=new URL(request.url??"/","http://cortex.invalid");if(method==="GET"&&url.pathname==="/healthz"){const state=control.current();write(response,200,{ok:true,mode:control.effectiveMode(),revision:state.revision});emit({operation:"HEALTH",status:"OK",trigger:null,pageId:null,mode:control.effectiveMode(),reason:null,durationMs:Math.max(0,now()-started),errorCode:null});return;}
    if(method==="POST"&&url.pathname==="/v1/serp/run"){if(!auth(request,runToken))throw new HttpError(401,"UNAUTHORIZED");const input=await body(request);requestExact(input,["pageId"]);if(input.pageId!==undefined&&typeof input.pageId!=="string")throw new HttpError(400,"INVALID_BODY");const results=await runCycle("MANUAL",input.pageId as string|undefined);write(response,200,{results});return;}
    if(method==="GET"&&url.pathname==="/v1/serp/control"){if(!auth(request,controlToken))throw new HttpError(401,"UNAUTHORIZED");write(response,200,{state:control.current(),effectiveMode:control.effectiveMode(),configuredMode:control.configuredMode,currentPolicyDigest:control.policyDigest,history:control.history(64)});emit({operation:"CONTROL_READ",status:"OK",trigger:null,pageId:null,mode:control.effectiveMode(),reason:null,durationMs:Math.max(0,now()-started),errorCode:null});return;}
    if(method==="POST"&&url.pathname==="/v1/serp/control"){if(!auth(request,controlToken))throw new HttpError(401,"UNAUTHORIZED");const input=await body(request);requestExact(input,["expectedRevision","mode","reason","changedAt"]);if(typeof input.expectedRevision!=="number"||typeof input.mode!=="string"||typeof input.reason!=="string"||(input.changedAt!==undefined&&typeof input.changedAt!=="string"))throw new HttpError(400,"INVALID_BODY");const state=control.set({expectedRevision:input.expectedRevision,mode:input.mode as SerpMetadataMode,reason:input.reason,...(input.changedAt===undefined?{}:{changedAt:input.changedAt})});write(response,200,{state,effectiveMode:control.effectiveMode()});emit({operation:"CONTROL_WRITE",status:"OK",trigger:null,pageId:null,mode:state.mode,reason:state.reason,durationMs:Math.max(0,now()-started),errorCode:null});return;}
    if(method==="POST"&&url.pathname==="/v1/serp/rollback"){if(!auth(request,controlToken))throw new HttpError(401,"UNAUTHORIZED");const input=await body(request);requestExact(input,["pageId","runId"]);if(typeof input.pageId!=="string"||typeof input.runId!=="string")throw new HttpError(400,"INVALID_BODY");write(response,200,{result:await rollback(input.pageId,input.runId)});return;}
    if(method==="GET"&&url.pathname==="/v1/serp/metadata"){if(!auth(request,metadataToken))throw new HttpError(401,"UNAUTHORIZED");const allowed=new Set(["siteUrl","pageId","pageUrl"]);for(const key of url.searchParams.keys())if(!allowed.has(key))throw new HttpError(400,"INVALID_QUERY");const siteUrl=url.searchParams.get("siteUrl");const pageId=url.searchParams.get("pageId");const pageUrl=url.searchParams.get("pageUrl");if(siteUrl!==options.config.siteUrl||!pageId||!pageUrl)throw new HttpError(400,"INVALID_QUERY");const page=pages.get(pageId);if(!page||page.pageUrl!==pageUrl)throw new HttpError(404,"NOT_CONFIGURED");const snapshot=await options.publisher.read(siteUrl,pageId,pageUrl);if(!snapshot){write(response,404,{error:"NO_OVERRIDE"});return;}write(response,200,{siteUrl,pageId,pageUrl,metadata:snapshot.metadata,revision:snapshot.revision,digest:snapshot.digest});emit({operation:"METADATA_READ",status:"OK",trigger:null,pageId,mode:control.effectiveMode(),reason:null,durationMs:Math.max(0,now()-started),errorCode:null});return;}write(response,404,{error:"NOT_FOUND"});
  }catch(error){const status=statusFor(error);if(!response.headersSent&&!response.writableEnded)write(response,status,{error:codeFor(error)});}});
  return Object.freeze({server,policy,runOnce:runCycle,start:(runImmediately=true)=>{if(interval)return;if(runImmediately)void runCycle("STARTUP").catch(()=>undefined);interval=setInterval(()=>{void runCycle("SCHEDULED").catch(()=>undefined);},options.config.intervalMs);interval.unref?.();},close:()=>new Promise<void>((resolve,reject)=>{if(interval){clearInterval(interval);interval=null;}if(!server.listening){resolve();return;}server.close(error=>error?reject(error):resolve());})});
}
