import { createHash } from "node:crypto";
import { canonicalJson, ontologyId, validateSchema, type OntologyScope, type SchemaVersion, type ValidatedSchema } from "@nexus/ontology";
import { OntologyTransactionError, type JsonValue, type ObjectRecord, type OntologyTransactionPort, type TransactionOperation } from "@nexus/ontology/transaction";
import { GoogleAdsApiError, type GoogleAdsCampaignSnapshot, type GoogleAdsControlMutation, type GoogleAdsMutationReceipt, type GoogleAdsPortfolioSnapshot } from "./google-ads-rest";

const STATE_TYPE = "cortex.bidding_supervisor_state";
const RUN_TYPE = "cortex.bidding_supervisor_run";
const DAY_MS = 86_400_000;
const IDENTIFIER = /^[A-Za-z0-9](?:[A-Za-z0-9._:-]{0,127})$/;
const STATE = Object.freeze({ customerId: "cortex.bidding.state.customer_id", campaignId: "cortex.bidding.state.campaign_id", payload: "cortex.bidding.state.payload", digest: "cortex.bidding.state.digest", updatedAt: "cortex.bidding.state.updated_at" });
const RUN = Object.freeze({ runId: "cortex.bidding.run.run_id", customerId: "cortex.bidding.run.customer_id", campaignId: "cortex.bidding.run.campaign_id", policyDigest: "cortex.bidding.run.policy_digest", status: "cortex.bidding.run.status", payload: "cortex.bidding.run.payload", digest: "cortex.bidding.run.digest", createdAt: "cortex.bidding.run.created_at", updatedAt: "cortex.bidding.run.updated_at" });

export type BiddingSupervisorMode = "ACTIVE" | "OBSERVE_ONLY" | "KILLED";
export type BiddingSupervisorRunStatus = "PREPARED" | "APPLIED" | "NOOP" | "FAILED" | "ROLLED_BACK";
export type BiddingSupervisorDirection = "INCREASE_VOLUME" | "DECREASE_RISK" | "HOLD";
export type BiddingSupervisorActionKind = GoogleAdsControlMutation["kind"];
export type BiddingSupervisorReason = "KILL_SWITCH" | "COOLDOWN" | "CAMPAIGN_NOT_ENABLED" | "INSUFFICIENT_EVIDENCE" | "STALE_BUSINESS_DATA" | "PROFITABILITY_HOLD" | "NO_COMPATIBLE_CONTROL" | "SHARED_BUDGET_BLOCKED" | "OBSERVE_ONLY" | "ACTION_APPLIED" | "ACTION_RECOVERED" | "REMOTE_CONFLICT" | "API_FAILURE" | "ROLLBACK_APPLIED";
const MODES: readonly BiddingSupervisorMode[] = ["ACTIVE", "OBSERVE_ONLY", "KILLED"];
const STATUSES: readonly BiddingSupervisorRunStatus[] = ["PREPARED", "APPLIED", "NOOP", "FAILED", "ROLLED_BACK"];
const DIRECTIONS: readonly BiddingSupervisorDirection[] = ["INCREASE_VOLUME", "DECREASE_RISK", "HOLD"];
const REASONS: readonly BiddingSupervisorReason[] = ["KILL_SWITCH", "COOLDOWN", "CAMPAIGN_NOT_ENABLED", "INSUFFICIENT_EVIDENCE", "STALE_BUSINESS_DATA", "PROFITABILITY_HOLD", "NO_COMPATIBLE_CONTROL", "SHARED_BUDGET_BLOCKED", "OBSERVE_ONLY", "ACTION_APPLIED", "ACTION_RECOVERED", "REMOTE_CONFLICT", "API_FAILURE", "ROLLBACK_APPLIED"];

export interface CreateBiddingSupervisorPolicyInput {
  readonly policyId: string; readonly version: string; readonly observationWindowDays: number; readonly reportingLagDays: number;
  readonly cooldownMs: number; readonly maxBusinessDataAgeMs: number; readonly minimumCostMicros: number; readonly minimumGoogleConversions: number;
  readonly increaseVolumeProfitToSpendRatio: number; readonly decreaseRiskProfitToSpendRatio: number;
  readonly budgetStepFraction: number; readonly targetStepFraction: number; readonly bidBoundStepFraction: number;
  readonly minBudgetMicros: number; readonly maxBudgetMicros: number; readonly minTargetCpaMicros: number; readonly maxTargetCpaMicros: number;
  readonly minTargetRoas: number; readonly maxTargetRoas: number; readonly minPortfolioCpcCeilingMicros: number; readonly maxPortfolioCpcCeilingMicros: number;
  readonly allowSharedBudgets: boolean; readonly managePortfolioBidBounds: boolean; readonly mode?: BiddingSupervisorMode; readonly maxWriteRetries?: number;
}
export interface BiddingSupervisorPolicy extends Omit<Required<CreateBiddingSupervisorPolicyInput>, "mode" | "maxWriteRetries"> { readonly mode: BiddingSupervisorMode; readonly maxWriteRetries: number; readonly digest: string }
export interface BusinessProfitabilityQuery { readonly customerId: string; readonly scopeKind: "CAMPAIGN" | "BIDDING_STRATEGY"; readonly scopeId: string; readonly windowStart: string; readonly windowEnd: string }
export interface BusinessProfitabilitySnapshot extends BusinessProfitabilityQuery { readonly revenueMicros: number; readonly grossProfitBeforeAdSpendMicros: number; readonly qualifiedConversions: number; readonly observedAt: string; readonly sourceId: string }
export interface BusinessProfitabilityProvider { getProfitability(query: BusinessProfitabilityQuery): Promise<BusinessProfitabilitySnapshot> }
export interface GoogleAdsBiddingGateway {
  getCampaignSnapshot(customerId: string, campaignId: string, startMs: number, endMs: number): Promise<GoogleAdsCampaignSnapshot>;
  getPortfolioSnapshot(customerId: string, resourceName: string, startMs: number, endMs: number): Promise<GoogleAdsPortfolioSnapshot>;
  applyMutation(customerId: string, action: GoogleAdsControlMutation): Promise<GoogleAdsMutationReceipt>;
}
export interface BiddingSupervisorRunInput { readonly runId: string; readonly customerId: string; readonly campaignId: string; readonly mode?: BiddingSupervisorMode }
export interface BiddingSupervisorRollbackInput { readonly runId: string; readonly customerId: string; readonly campaignId: string }
export interface BiddingSupervisorEvidence { readonly googleCostMicros: number; readonly googleConversions: number; readonly googleConversionValue: number; readonly businessRevenueMicros: number; readonly businessGrossProfitBeforeAdSpendMicros: number; readonly businessQualifiedConversions: number; readonly profitAfterAdSpendMicros: number; readonly profitToSpendRatio: number; readonly sourceId: string }
export interface BiddingSupervisorResult { readonly runId: string; readonly customerId: string; readonly campaignId: string; readonly status: BiddingSupervisorRunStatus; readonly mode: BiddingSupervisorMode; readonly direction: BiddingSupervisorDirection; readonly reason: BiddingSupervisorReason; readonly windowStart: string; readonly windowEnd: string; readonly action: GoogleAdsControlMutation | null; readonly receipt: GoogleAdsMutationReceipt | null; readonly evidence: BiddingSupervisorEvidence | null; readonly policyDigest: string; readonly digest: string }

interface StatePayload { readonly policyDigest: string; readonly lastRunAt: string | null; readonly lastMutationAt: string | null; readonly lastActionKind: BiddingSupervisorActionKind | null; readonly inFlightRunId: string | null; readonly lastAppliedAction: GoogleAdsControlMutation | null; readonly lastRollbackAt: string | null }
interface StateRecord extends StatePayload { readonly id: string; readonly customerId: string; readonly campaignId: string; readonly digest: string; readonly updatedAt: string; readonly revision: number }
interface RunPayload { readonly mode: BiddingSupervisorMode; readonly direction: BiddingSupervisorDirection; readonly reason: BiddingSupervisorReason; readonly windowStart: string; readonly windowEnd: string; readonly campaignSnapshot: GoogleAdsCampaignSnapshot | null; readonly portfolioSnapshot: GoogleAdsPortfolioSnapshot | null; readonly businessSnapshot: BusinessProfitabilitySnapshot | null; readonly evidence: BiddingSupervisorEvidence | null; readonly action: GoogleAdsControlMutation | null; readonly receipt: GoogleAdsMutationReceipt | null; readonly errorCode: string | null }
interface RunRecord extends RunPayload { readonly id: string; readonly runId: string; readonly customerId: string; readonly campaignId: string; readonly policyDigest: string; readonly status: BiddingSupervisorRunStatus; readonly digest: string; readonly createdAt: string; readonly updatedAt: string; readonly revision: number }
interface PlannedAction { readonly action: GoogleAdsControlMutation; readonly evidence: BiddingSupervisorEvidence; readonly business: BusinessProfitabilitySnapshot; readonly direction: Exclude<BiddingSupervisorDirection, "HOLD"> }
type FinalizeEffect = "NONE" | "APPLY" | "ROLLBACK";

export class BiddingSupervisorError extends Error {
  constructor(public readonly code: "INVALID_INPUT" | "POLICY_VIOLATION" | "CONFLICT" | "INTEGRITY_FAILURE" | "PERSISTENCE_FAILURE" | "REMOTE_FAILURE", message: string) { super(message); this.name = "BiddingSupervisorError"; }
}

function hash(namespace: string, value: unknown): string { return `sha256:${createHash("sha256").update(`${namespace}\n${canonicalJson(value)}`, "utf8").digest("hex")}`; }
function id(value: string, field: string): string { const v = value.trim(); if (!IDENTIFIER.test(v)) throw new BiddingSupervisorError("INVALID_INPUT", `${field} is malformed`); return v; }
function numericId(value: string, field: string): string { const v = value.replaceAll("-", "").trim(); if (!/^\d{5,20}$/.test(v)) throw new BiddingSupervisorError("INVALID_INPUT", `${field} is malformed`); return v; }
function positiveInt(value: number, field: string): number { if (!Number.isSafeInteger(value) || value <= 0) throw new BiddingSupervisorError("INVALID_INPUT", `${field} must be a positive safe integer`); return value; }
function nonNegativeInt(value: number, field: string): number { if (!Number.isSafeInteger(value) || value < 0) throw new BiddingSupervisorError("INVALID_INPUT", `${field} must be a non-negative safe integer`); return value; }
function positiveNumber(value: number, field: string): number { if (!Number.isFinite(value) || value <= 0) throw new BiddingSupervisorError("INVALID_INPUT", `${field} must be finite and positive`); return value; }
function step(value: number, field: string): number { if (!Number.isFinite(value) || value <= 0 || value > 0.25) throw new BiddingSupervisorError("INVALID_INPUT", `${field} must be greater than 0 and at most 0.25`); return value; }
function utc(value: string, field: string): string { const parsed = new Date(value); if (!Number.isFinite(parsed.getTime()) || parsed.toISOString() !== value) throw new BiddingSupervisorError("INTEGRITY_FAILURE", `${field} must be canonical UTC`); return value; }
function isJson(value: unknown): value is JsonValue { if (value === null || typeof value === "string" || typeof value === "boolean") return true; if (typeof value === "number") return Number.isFinite(value); if (Array.isArray(value)) return value.every(isJson); if (!value || typeof value !== "object") return false; return Object.values(value as Record<string, unknown>).every(isJson); }
function json(value: unknown, field: string): JsonValue { if (!isJson(value)) throw new BiddingSupervisorError("INTEGRITY_FAILURE", `${field} is not finite JSON`); return value; }
function obj(value: JsonValue | undefined, field: string): Record<string, JsonValue> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new BiddingSupervisorError("INTEGRITY_FAILURE", `${field} must be an object`); return value as Record<string, JsonValue>; }
function stringProp(record: ObjectRecord, key: string): string { const v = record.properties[key]; if (typeof v !== "string" || !v) throw new BiddingSupervisorError("INTEGRITY_FAILURE", `record ${record.id} has invalid ${key}`); return v; }
function nullableString(value: JsonValue | undefined, field: string): string | null { if (value === undefined || value === null) return null; if (typeof value !== "string") throw new BiddingSupervisorError("INTEGRITY_FAILURE", `${field} must be string or null`); return value; }
function property(idValue: string, name: string, valueKind: "STRING" | "JSON" | "DATETIME", immutable = false) { return { id: idValue, name, valueKind, cardinality: "REQUIRED", unique: false, immutable } as const; }

function schema(scope: OntologyScope): ValidatedSchema {
  const value: SchemaVersion = { version: "cortex-bidding-supervisor-v2", scope,
    properties: [property(STATE.customerId, "BiddingStateCustomerId", "STRING", true), property(STATE.campaignId, "BiddingStateCampaignId", "STRING", true), property(STATE.payload, "BiddingStatePayload", "JSON"), property(STATE.digest, "BiddingStateDigest", "STRING"), property(STATE.updatedAt, "BiddingStateUpdatedAt", "DATETIME"), property(RUN.runId, "BiddingRunId", "STRING", true), property(RUN.customerId, "BiddingRunCustomerId", "STRING", true), property(RUN.campaignId, "BiddingRunCampaignId", "STRING", true), property(RUN.policyDigest, "BiddingRunPolicyDigest", "STRING", true), property(RUN.status, "BiddingRunStatus", "STRING"), property(RUN.payload, "BiddingRunPayload", "JSON"), property(RUN.digest, "BiddingRunDigest", "STRING"), property(RUN.createdAt, "BiddingRunCreatedAt", "DATETIME", true), property(RUN.updatedAt, "BiddingRunUpdatedAt", "DATETIME")],
    interfaces: [], objects: [{ id: STATE_TYPE, name: "CortexBiddingSupervisorState", propertyIds: Object.values(STATE), interfaceIds: [] }, { id: RUN_TYPE, name: "CortexBiddingSupervisorRun", propertyIds: Object.values(RUN), interfaceIds: [] }], relationships: [], actions: [], functions: [], events: [] };
  return validateSchema(value);
}

export function createBiddingSupervisorPolicy(input: CreateBiddingSupervisorPolicyInput): BiddingSupervisorPolicy {
  const policyId = id(input.policyId, "policyId"); const version = id(input.version, "version");
  const observationWindowDays = positiveInt(input.observationWindowDays, "observationWindowDays"); if (observationWindowDays > 90) throw new BiddingSupervisorError("INVALID_INPUT", "observationWindowDays must be at most 90");
  const reportingLagDays = positiveInt(input.reportingLagDays, "reportingLagDays"); if (reportingLagDays > 14) throw new BiddingSupervisorError("INVALID_INPUT", "reportingLagDays must be at most 14");
  const cooldownMs = positiveInt(input.cooldownMs, "cooldownMs"); const maxBusinessDataAgeMs = positiveInt(input.maxBusinessDataAgeMs, "maxBusinessDataAgeMs"); const minimumCostMicros = nonNegativeInt(input.minimumCostMicros, "minimumCostMicros");
  if (!Number.isFinite(input.minimumGoogleConversions) || input.minimumGoogleConversions < 0) throw new BiddingSupervisorError("INVALID_INPUT", "minimumGoogleConversions must be non-negative");
  const increaseVolumeProfitToSpendRatio = positiveNumber(input.increaseVolumeProfitToSpendRatio, "increaseVolumeProfitToSpendRatio"); const decreaseRiskProfitToSpendRatio = positiveNumber(input.decreaseRiskProfitToSpendRatio, "decreaseRiskProfitToSpendRatio"); if (decreaseRiskProfitToSpendRatio >= increaseVolumeProfitToSpendRatio) throw new BiddingSupervisorError("INVALID_INPUT", "decrease-risk threshold must be lower than increase-volume threshold");
  const budgetStepFraction = step(input.budgetStepFraction, "budgetStepFraction"); const targetStepFraction = step(input.targetStepFraction, "targetStepFraction"); const bidBoundStepFraction = step(input.bidBoundStepFraction, "bidBoundStepFraction");
  const minBudgetMicros = positiveInt(input.minBudgetMicros, "minBudgetMicros"); const maxBudgetMicros = positiveInt(input.maxBudgetMicros, "maxBudgetMicros"); if (minBudgetMicros >= maxBudgetMicros) throw new BiddingSupervisorError("INVALID_INPUT", "budget bounds are invalid");
  const minTargetCpaMicros = positiveInt(input.minTargetCpaMicros, "minTargetCpaMicros"); const maxTargetCpaMicros = positiveInt(input.maxTargetCpaMicros, "maxTargetCpaMicros"); if (minTargetCpaMicros >= maxTargetCpaMicros) throw new BiddingSupervisorError("INVALID_INPUT", "target CPA bounds are invalid");
  const minTargetRoas = positiveNumber(input.minTargetRoas, "minTargetRoas"); const maxTargetRoas = positiveNumber(input.maxTargetRoas, "maxTargetRoas"); if (minTargetRoas < 0.01 || maxTargetRoas > 1000 || minTargetRoas >= maxTargetRoas) throw new BiddingSupervisorError("INVALID_INPUT", "target ROAS bounds must fit Google Ads range 0.01..1000");
  const minPortfolioCpcCeilingMicros = positiveInt(input.minPortfolioCpcCeilingMicros, "minPortfolioCpcCeilingMicros"); const maxPortfolioCpcCeilingMicros = positiveInt(input.maxPortfolioCpcCeilingMicros, "maxPortfolioCpcCeilingMicros"); if (minPortfolioCpcCeilingMicros >= maxPortfolioCpcCeilingMicros) throw new BiddingSupervisorError("INVALID_INPUT", "portfolio CPC ceiling bounds are invalid");
  const mode = input.mode ?? "ACTIVE"; if (!MODES.includes(mode)) throw new BiddingSupervisorError("INVALID_INPUT", "mode is invalid");
  const maxWriteRetries = input.maxWriteRetries ?? 3; if (!Number.isInteger(maxWriteRetries) || maxWriteRetries < 0 || maxWriteRetries > 10) throw new BiddingSupervisorError("INVALID_INPUT", "maxWriteRetries must be 0..10");
  const core = { policyId, version, observationWindowDays, reportingLagDays, cooldownMs, maxBusinessDataAgeMs, minimumCostMicros, minimumGoogleConversions: input.minimumGoogleConversions, increaseVolumeProfitToSpendRatio, decreaseRiskProfitToSpendRatio, budgetStepFraction, targetStepFraction, bidBoundStepFraction, minBudgetMicros, maxBudgetMicros, minTargetCpaMicros, maxTargetCpaMicros, minTargetRoas, maxTargetRoas, minPortfolioCpcCeilingMicros, maxPortfolioCpcCeilingMicros, allowSharedBudgets: input.allowSharedBudgets, managePortfolioBidBounds: input.managePortfolioBidBounds, mode, maxWriteRetries };
  return Object.freeze({ ...core, digest: hash("cortex-bidding-policy-v1", core) });
}

function effectiveMode(policy: BiddingSupervisorMode, requested: BiddingSupervisorMode | undefined): BiddingSupervisorMode { const rank: Record<BiddingSupervisorMode, number> = { ACTIVE: 0, OBSERVE_ONLY: 1, KILLED: 2 }; const candidate = requested ?? "ACTIVE"; if (!MODES.includes(candidate)) throw new BiddingSupervisorError("INVALID_INPUT", "requested mode is invalid"); return rank[candidate] > rank[policy] ? candidate : policy; }
function reportWindow(nowMs: number, policy: BiddingSupervisorPolicy) { const date = new Date(nowMs); if (!Number.isFinite(date.getTime())) throw new BiddingSupervisorError("INTEGRITY_FAILURE", "engine clock is invalid"); const today = Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()); const endMs = today - policy.reportingLagDays * DAY_MS; const startMs = endMs - (policy.observationWindowDays - 1) * DAY_MS; const format = (ms: number) => new Date(ms).toISOString().slice(0, 10); return Object.freeze({ startMs, endMs, start: format(startMs), end: format(endMs) }); }
function stateDigest(customerId: string, campaignId: string, payload: StatePayload, updatedAt: string) { return hash("cortex-bidding-state-v2", { customerId, campaignId, payload, updatedAt }); }
function runDigest(runId: string, customerId: string, campaignId: string, policyDigest: string, status: BiddingSupervisorRunStatus, payload: RunPayload, createdAt: string, updatedAt: string) { return hash("cortex-bidding-run-v1", { runId, customerId, campaignId, policyDigest, status, payload, createdAt, updatedAt }); }
function stateProperties(customerId: string, campaignId: string, payload: StatePayload, updatedAt: string): Readonly<Record<string, JsonValue>> { return Object.freeze({ [STATE.customerId]: customerId, [STATE.campaignId]: campaignId, [STATE.payload]: json(payload, "state payload"), [STATE.digest]: stateDigest(customerId, campaignId, payload, updatedAt), [STATE.updatedAt]: updatedAt }); }
function runProperties(runId: string, customerId: string, campaignId: string, policyDigest: string, status: BiddingSupervisorRunStatus, payload: RunPayload, createdAt: string, updatedAt: string): Readonly<Record<string, JsonValue>> { return Object.freeze({ [RUN.runId]: runId, [RUN.customerId]: customerId, [RUN.campaignId]: campaignId, [RUN.policyDigest]: policyDigest, [RUN.status]: status, [RUN.payload]: json(payload, "run payload"), [RUN.digest]: runDigest(runId, customerId, campaignId, policyDigest, status, payload, createdAt, updatedAt), [RUN.createdAt]: createdAt, [RUN.updatedAt]: updatedAt }); }

function parseAction(value: JsonValue | undefined): GoogleAdsControlMutation | null {
  if (value === null || value === undefined) return null; const raw = obj(value, "action"); if (typeof raw.kind !== "string" || typeof raw.resourceName !== "string") throw new BiddingSupervisorError("INTEGRITY_FAILURE", "action identity is invalid");
  const n = (key: string) => { const v = raw[key]; if (typeof v !== "number" || !Number.isFinite(v)) throw new BiddingSupervisorError("INTEGRITY_FAILURE", `action ${key} is invalid`); return v; }; const nn = (key: string) => raw[key] == null ? null : n(key); const resourceName = raw.resourceName;
  if (raw.kind === "CAMPAIGN_BUDGET") return { kind: raw.kind, resourceName, expectedAmountMicros: n("expectedAmountMicros"), nextAmountMicros: n("nextAmountMicros") };
  if (raw.kind === "STANDARD_TARGET_CPA") return { kind: raw.kind, resourceName, expectedTargetCpaMicros: n("expectedTargetCpaMicros"), nextTargetCpaMicros: n("nextTargetCpaMicros") };
  if (raw.kind === "STANDARD_TARGET_ROAS") return { kind: raw.kind, resourceName, expectedTargetRoas: n("expectedTargetRoas"), nextTargetRoas: n("nextTargetRoas") };
  if (raw.kind === "PORTFOLIO_TARGET_CPA" && (raw.strategyType === "TARGET_CPA" || raw.strategyType === "MAXIMIZE_CONVERSIONS")) return { kind: raw.kind, resourceName, strategyType: raw.strategyType, expectedTargetCpaMicros: n("expectedTargetCpaMicros"), nextTargetCpaMicros: n("nextTargetCpaMicros") };
  if (raw.kind === "PORTFOLIO_TARGET_ROAS" && (raw.strategyType === "TARGET_ROAS" || raw.strategyType === "MAXIMIZE_CONVERSION_VALUE")) return { kind: raw.kind, resourceName, strategyType: raw.strategyType, expectedTargetRoas: n("expectedTargetRoas"), nextTargetRoas: n("nextTargetRoas") };
  if (raw.kind === "PORTFOLIO_BID_BOUNDS" && (raw.strategyType === "TARGET_CPA" || raw.strategyType === "MAXIMIZE_CONVERSIONS" || raw.strategyType === "TARGET_ROAS" || raw.strategyType === "MAXIMIZE_CONVERSION_VALUE")) return { kind: raw.kind, resourceName, strategyType: raw.strategyType, expectedCeilingMicros: nn("expectedCeilingMicros"), nextCeilingMicros: nn("nextCeilingMicros"), expectedFloorMicros: nn("expectedFloorMicros"), nextFloorMicros: nn("nextFloorMicros") };
  throw new BiddingSupervisorError("INTEGRITY_FAILURE", "action kind or strategy type is invalid");
}
function parseEvidence(value: JsonValue | undefined): BiddingSupervisorEvidence | null { if (value == null) return null; const raw = obj(value, "evidence"); const n = (key: string) => { const v = raw[key]; if (typeof v !== "number" || !Number.isFinite(v)) throw new BiddingSupervisorError("INTEGRITY_FAILURE", `evidence ${key} is invalid`); return v; }; if (typeof raw.sourceId !== "string") throw new BiddingSupervisorError("INTEGRITY_FAILURE", "evidence sourceId is invalid"); return Object.freeze({ googleCostMicros: n("googleCostMicros"), googleConversions: n("googleConversions"), googleConversionValue: n("googleConversionValue"), businessRevenueMicros: n("businessRevenueMicros"), businessGrossProfitBeforeAdSpendMicros: n("businessGrossProfitBeforeAdSpendMicros"), businessQualifiedConversions: n("businessQualifiedConversions"), profitAfterAdSpendMicros: n("profitAfterAdSpendMicros"), profitToSpendRatio: n("profitToSpendRatio"), sourceId: raw.sourceId }); }
function parseReceipt(value: JsonValue | undefined): GoogleAdsMutationReceipt | null { if (value == null) return null; const raw = obj(value, "receipt"); if (typeof raw.resourceName !== "string" || typeof raw.recoveredAlreadyApplied !== "boolean") throw new BiddingSupervisorError("INTEGRITY_FAILURE", "receipt is invalid"); return Object.freeze({ requestId: nullableString(raw.requestId, "receipt.requestId"), resourceName: raw.resourceName, recoveredAlreadyApplied: raw.recoveredAlreadyApplied }); }

function parseState(record: ObjectRecord): StateRecord {
  if (record.typeId !== STATE_TYPE) throw new BiddingSupervisorError("INTEGRITY_FAILURE", "state record type is invalid"); const customerId = stringProp(record, STATE.customerId); const campaignId = stringProp(record, STATE.campaignId); const raw = obj(record.properties[STATE.payload], "state payload"); const policyDigest = nullableString(raw.policyDigest, "state.policyDigest"); if (!policyDigest) throw new BiddingSupervisorError("INTEGRITY_FAILURE", "state policyDigest is missing");
  const lastActionKind = nullableString(raw.lastActionKind, "state.lastActionKind") as BiddingSupervisorActionKind | null; const validKinds: readonly BiddingSupervisorActionKind[] = ["CAMPAIGN_BUDGET", "STANDARD_TARGET_CPA", "STANDARD_TARGET_ROAS", "PORTFOLIO_TARGET_CPA", "PORTFOLIO_TARGET_ROAS", "PORTFOLIO_BID_BOUNDS"]; if (lastActionKind && !validKinds.includes(lastActionKind)) throw new BiddingSupervisorError("INTEGRITY_FAILURE", "state lastActionKind is invalid");
  const payload: StatePayload = { policyDigest, lastRunAt: nullableString(raw.lastRunAt, "state.lastRunAt"), lastMutationAt: nullableString(raw.lastMutationAt, "state.lastMutationAt"), lastActionKind, inFlightRunId: nullableString(raw.inFlightRunId, "state.inFlightRunId"), lastAppliedAction: parseAction(raw.lastAppliedAction), lastRollbackAt: nullableString(raw.lastRollbackAt, "state.lastRollbackAt") }; for (const value of [payload.lastRunAt, payload.lastMutationAt, payload.lastRollbackAt]) if (value) utc(value, "state timestamp"); const updatedAt = utc(stringProp(record, STATE.updatedAt), "state.updatedAt"); const digest = stringProp(record, STATE.digest); if (digest !== stateDigest(customerId, campaignId, payload, updatedAt)) throw new BiddingSupervisorError("INTEGRITY_FAILURE", "state digest mismatch"); return Object.freeze({ id: record.id, customerId, campaignId, ...payload, digest, updatedAt, revision: record.revision });
}
function parseRun(record: ObjectRecord): RunRecord {
  if (record.typeId !== RUN_TYPE) throw new BiddingSupervisorError("INTEGRITY_FAILURE", "run record type is invalid"); const runId = stringProp(record, RUN.runId); const customerId = stringProp(record, RUN.customerId); const campaignId = stringProp(record, RUN.campaignId); const policyDigest = stringProp(record, RUN.policyDigest); const status = stringProp(record, RUN.status) as BiddingSupervisorRunStatus; if (!STATUSES.includes(status)) throw new BiddingSupervisorError("INTEGRITY_FAILURE", "run status is invalid"); const raw = obj(record.properties[RUN.payload], "run payload"); const mode = raw.mode as BiddingSupervisorMode; const direction = raw.direction as BiddingSupervisorDirection; const reason = raw.reason as BiddingSupervisorReason; if (!MODES.includes(mode) || !DIRECTIONS.includes(direction) || !REASONS.includes(reason) || typeof raw.windowStart !== "string" || typeof raw.windowEnd !== "string") throw new BiddingSupervisorError("INTEGRITY_FAILURE", "run payload enum/window is invalid");
  const payload: RunPayload = { mode, direction, reason, windowStart: raw.windowStart, windowEnd: raw.windowEnd, campaignSnapshot: (raw.campaignSnapshot ?? null) as unknown as GoogleAdsCampaignSnapshot | null, portfolioSnapshot: (raw.portfolioSnapshot ?? null) as unknown as GoogleAdsPortfolioSnapshot | null, businessSnapshot: (raw.businessSnapshot ?? null) as unknown as BusinessProfitabilitySnapshot | null, evidence: parseEvidence(raw.evidence), action: parseAction(raw.action), receipt: parseReceipt(raw.receipt), errorCode: nullableString(raw.errorCode, "run.errorCode") }; const createdAt = utc(stringProp(record, RUN.createdAt), "run.createdAt"); const updatedAt = utc(stringProp(record, RUN.updatedAt), "run.updatedAt"); const digest = stringProp(record, RUN.digest); if (digest !== runDigest(runId, customerId, campaignId, policyDigest, status, payload, createdAt, updatedAt)) throw new BiddingSupervisorError("INTEGRITY_FAILURE", "run digest mismatch"); return Object.freeze({ id: record.id, runId, customerId, campaignId, policyDigest, status, ...payload, digest, createdAt, updatedAt, revision: record.revision });
}
function payload(run: RunRecord): RunPayload { return { mode: run.mode, direction: run.direction, reason: run.reason, windowStart: run.windowStart, windowEnd: run.windowEnd, campaignSnapshot: run.campaignSnapshot, portfolioSnapshot: run.portfolioSnapshot, businessSnapshot: run.businessSnapshot, evidence: run.evidence, action: run.action, receipt: run.receipt, errorCode: run.errorCode }; }
function evidence(google: Pick<GoogleAdsCampaignSnapshot | GoogleAdsPortfolioSnapshot, "costMicros" | "conversions" | "conversionValue">, business: BusinessProfitabilitySnapshot): BiddingSupervisorEvidence { return Object.freeze({ googleCostMicros: google.costMicros, googleConversions: google.conversions, googleConversionValue: google.conversionValue, businessRevenueMicros: business.revenueMicros, businessGrossProfitBeforeAdSpendMicros: business.grossProfitBeforeAdSpendMicros, businessQualifiedConversions: business.qualifiedConversions, profitAfterAdSpendMicros: business.grossProfitBeforeAdSpendMicros - google.costMicros, profitToSpendRatio: google.costMicros > 0 ? business.grossProfitBeforeAdSpendMicros / google.costMicros : 0, sourceId: business.sourceId }); }
function validateBusiness(snapshot: BusinessProfitabilitySnapshot, query: BusinessProfitabilityQuery, nowMs: number, policy: BiddingSupervisorPolicy): "FRESH" | "STALE" { if (snapshot.customerId !== query.customerId || snapshot.scopeKind !== query.scopeKind || snapshot.scopeId !== query.scopeId || snapshot.windowStart !== query.windowStart || snapshot.windowEnd !== query.windowEnd) throw new BiddingSupervisorError("INTEGRITY_FAILURE", "business snapshot scope/window mismatch"); nonNegativeInt(snapshot.revenueMicros, "business revenueMicros"); nonNegativeInt(snapshot.grossProfitBeforeAdSpendMicros, "business grossProfitBeforeAdSpendMicros"); if (!Number.isFinite(snapshot.qualifiedConversions) || snapshot.qualifiedConversions < 0) throw new BiddingSupervisorError("INTEGRITY_FAILURE", "business qualifiedConversions is invalid"); id(snapshot.sourceId, "business sourceId"); const observedAt = utc(snapshot.observedAt, "business observedAt"); const age = nowMs - Date.parse(observedAt); if (age < 0) throw new BiddingSupervisorError("INTEGRITY_FAILURE", "business snapshot cannot be from the future"); return age > policy.maxBusinessDataAgeMs ? "STALE" : "FRESH"; }
function directionFor(value: BiddingSupervisorEvidence, policy: BiddingSupervisorPolicy): BiddingSupervisorDirection { if (value.profitToSpendRatio >= policy.increaseVolumeProfitToSpendRatio) return "INCREASE_VOLUME"; if (value.profitToSpendRatio <= policy.decreaseRiskProfitToSpendRatio) return "DECREASE_RISK"; return "HOLD"; }
function sufficient(value: Pick<GoogleAdsCampaignSnapshot | GoogleAdsPortfolioSnapshot, "costMicros" | "conversions">, policy: BiddingSupervisorPolicy): boolean { return value.costMicros >= policy.minimumCostMicros && value.conversions >= policy.minimumGoogleConversions; }
function boundedInt(current: number, fraction: number, direction: "UP" | "DOWN", min: number, max: number): number { if (!Number.isSafeInteger(current) || current < min || current > max) return current; const delta = Math.floor(current * fraction); if (delta < 1) return current; const next = direction === "UP" ? current + delta : current - delta; return direction === "UP" ? Math.min(max, next) : Math.max(min, next); }
function boundedFloat(current: number, fraction: number, direction: "UP" | "DOWN", min: number, max: number): number { if (!Number.isFinite(current) || current < min || current > max) return current; const raw = direction === "UP" ? current * (1 + fraction) : current * (1 - fraction); return Number((direction === "UP" ? Math.min(max, raw) : Math.max(min, raw)).toFixed(6)); }
function reverse(action: GoogleAdsControlMutation): GoogleAdsControlMutation { if (action.kind === "CAMPAIGN_BUDGET") return { ...action, expectedAmountMicros: action.nextAmountMicros, nextAmountMicros: action.expectedAmountMicros }; if (action.kind === "STANDARD_TARGET_CPA") return { ...action, expectedTargetCpaMicros: action.nextTargetCpaMicros, nextTargetCpaMicros: action.expectedTargetCpaMicros }; if (action.kind === "STANDARD_TARGET_ROAS") return { ...action, expectedTargetRoas: action.nextTargetRoas, nextTargetRoas: action.expectedTargetRoas }; if (action.kind === "PORTFOLIO_TARGET_CPA") return { ...action, expectedTargetCpaMicros: action.nextTargetCpaMicros, nextTargetCpaMicros: action.expectedTargetCpaMicros }; if (action.kind === "PORTFOLIO_TARGET_ROAS") return { ...action, expectedTargetRoas: action.nextTargetRoas, nextTargetRoas: action.expectedTargetRoas }; return { ...action, expectedCeilingMicros: action.nextCeilingMicros, nextCeilingMicros: action.expectedCeilingMicros, expectedFloorMicros: action.nextFloorMicros, nextFloorMicros: action.expectedFloorMicros }; }
function conflict(error: unknown): boolean { return error instanceof OntologyTransactionError && error.code === "CONFLICT"; }

export class PeriodicGoogleAdsBiddingSupervisor {
  readonly schema: ValidatedSchema;
  constructor(private readonly transactions: OntologyTransactionPort, readonly scope: OntologyScope, readonly policy: BiddingSupervisorPolicy, private readonly googleAds: GoogleAdsBiddingGateway, private readonly business: BusinessProfitabilityProvider, private readonly now: () => number = Date.now) { this.schema = schema(scope); }
  private time() { const ms = this.now(); if (!Number.isFinite(ms)) throw new BiddingSupervisorError("INTEGRITY_FAILURE", "engine clock is invalid"); return Object.freeze({ ms, iso: new Date(ms).toISOString() }); }
  private stateId(customerId: string, campaignId: string) { return ontologyId("cortex-bidding-state-v2", { scope: this.scope, customerId, campaignId }); }
  private runId(runId: string, customerId: string, campaignId: string) { return ontologyId("cortex-bidding-run-v2", { scope: this.scope, runId, customerId, campaignId }); }
  private readState(customerId: string, campaignId: string) { const raw = this.transactions.getObject(this.scope, this.stateId(customerId, campaignId)); return raw ? parseState(raw) : undefined; }
  private readRun(runIdValue: string, customerId: string, campaignId: string) { const raw = this.transactions.getObject(this.scope, this.runId(runIdValue, customerId, campaignId)); return raw ? parseRun(raw) : undefined; }
  private result(run: RunRecord): BiddingSupervisorResult { return Object.freeze({ runId: run.runId, customerId: run.customerId, campaignId: run.campaignId, status: run.status, mode: run.mode, direction: run.direction, reason: run.reason, windowStart: run.windowStart, windowEnd: run.windowEnd, action: run.action, receipt: run.receipt, evidence: run.evidence, policyDigest: run.policyDigest, digest: run.digest }); }

  private campaignCandidates(campaign: GoogleAdsCampaignSnapshot, business: BusinessProfitabilitySnapshot, ev: BiddingSupervisorEvidence, direction: Exclude<BiddingSupervisorDirection, "HOLD">): PlannedAction[] {
    const out: PlannedAction[] = []; const increase = direction === "INCREASE_VOLUME";
    if (!campaign.budgetExplicitlyShared || this.policy.allowSharedBudgets) { let next = boundedInt(campaign.budgetAmountMicros, this.policy.budgetStepFraction, increase ? "UP" : "DOWN", this.policy.minBudgetMicros, this.policy.maxBudgetMicros); if (increase && campaign.recommendedBudgetAmountMicros !== null && campaign.recommendedBudgetAmountMicros > campaign.budgetAmountMicros) next = Math.min(next, campaign.recommendedBudgetAmountMicros); if (next !== campaign.budgetAmountMicros) out.push({ action: { kind: "CAMPAIGN_BUDGET", resourceName: campaign.budgetResourceName, expectedAmountMicros: campaign.budgetAmountMicros, nextAmountMicros: next }, evidence: ev, business, direction }); }
    if (!campaign.portfolioBiddingStrategyResourceName && campaign.biddingStrategyType === "MAXIMIZE_CONVERSIONS" && campaign.standardTargetCpaMicros !== null) { const next = boundedInt(campaign.standardTargetCpaMicros, this.policy.targetStepFraction, increase ? "UP" : "DOWN", this.policy.minTargetCpaMicros, this.policy.maxTargetCpaMicros); if (next !== campaign.standardTargetCpaMicros) out.push({ action: { kind: "STANDARD_TARGET_CPA", resourceName: campaign.campaignResourceName, expectedTargetCpaMicros: campaign.standardTargetCpaMicros, nextTargetCpaMicros: next }, evidence: ev, business, direction }); }
    if (!campaign.portfolioBiddingStrategyResourceName && campaign.biddingStrategyType === "MAXIMIZE_CONVERSION_VALUE" && campaign.standardTargetRoas !== null) { const next = boundedFloat(campaign.standardTargetRoas, this.policy.targetStepFraction, increase ? "DOWN" : "UP", this.policy.minTargetRoas, this.policy.maxTargetRoas); if (next !== campaign.standardTargetRoas) out.push({ action: { kind: "STANDARD_TARGET_ROAS", resourceName: campaign.campaignResourceName, expectedTargetRoas: campaign.standardTargetRoas, nextTargetRoas: next }, evidence: ev, business, direction }); }
    return out;
  }
  private portfolioCandidates(portfolio: GoogleAdsPortfolioSnapshot, business: BusinessProfitabilitySnapshot, ev: BiddingSupervisorEvidence, direction: Exclude<BiddingSupervisorDirection, "HOLD">): PlannedAction[] {
    const out: PlannedAction[] = []; const increase = direction === "INCREASE_VOLUME";
    if ((portfolio.type === "TARGET_CPA" || portfolio.type === "MAXIMIZE_CONVERSIONS") && portfolio.targetCpaMicros !== null) { const next = boundedInt(portfolio.targetCpaMicros, this.policy.targetStepFraction, increase ? "UP" : "DOWN", this.policy.minTargetCpaMicros, this.policy.maxTargetCpaMicros); if (next !== portfolio.targetCpaMicros) out.push({ action: { kind: "PORTFOLIO_TARGET_CPA", resourceName: portfolio.resourceName, strategyType: portfolio.type, expectedTargetCpaMicros: portfolio.targetCpaMicros, nextTargetCpaMicros: next }, evidence: ev, business, direction }); }
    if ((portfolio.type === "TARGET_ROAS" || portfolio.type === "MAXIMIZE_CONVERSION_VALUE") && portfolio.targetRoas !== null) { const next = boundedFloat(portfolio.targetRoas, this.policy.targetStepFraction, increase ? "DOWN" : "UP", this.policy.minTargetRoas, this.policy.maxTargetRoas); if (next !== portfolio.targetRoas) out.push({ action: { kind: "PORTFOLIO_TARGET_ROAS", resourceName: portfolio.resourceName, strategyType: portfolio.type, expectedTargetRoas: portfolio.targetRoas, nextTargetRoas: next }, evidence: ev, business, direction }); }
    if (this.policy.managePortfolioBidBounds && portfolio.type !== "OTHER" && portfolio.cpcBidCeilingMicros !== null && (portfolio.cpcBidFloorMicros === null || portfolio.cpcBidFloorMicros <= portfolio.cpcBidCeilingMicros)) { const nextCeiling = boundedInt(portfolio.cpcBidCeilingMicros, this.policy.bidBoundStepFraction, increase ? "UP" : "DOWN", this.policy.minPortfolioCpcCeilingMicros, this.policy.maxPortfolioCpcCeilingMicros); let nextFloor = portfolio.cpcBidFloorMicros; if (increase && nextFloor !== null) nextFloor = boundedInt(nextFloor, this.policy.bidBoundStepFraction, "DOWN", 1, nextCeiling); if (nextFloor !== null && nextFloor > nextCeiling) nextFloor = nextCeiling; if (nextCeiling !== portfolio.cpcBidCeilingMicros || nextFloor !== portfolio.cpcBidFloorMicros) out.push({ action: { kind: "PORTFOLIO_BID_BOUNDS", resourceName: portfolio.resourceName, strategyType: portfolio.type, expectedCeilingMicros: portfolio.cpcBidCeilingMicros, nextCeilingMicros: nextCeiling, expectedFloorMicros: portfolio.cpcBidFloorMicros, nextFloorMicros: nextFloor }, evidence: ev, business, direction }); }
    return out;
  }
  private choose(candidates: readonly PlannedAction[], lastKind: BiddingSupervisorActionKind | null) { if (candidates.length === 0) return null; if (!lastKind) return candidates[0]!; const index = candidates.findIndex((candidate) => candidate.action.kind === lastKind); return index < 0 ? candidates[0]! : candidates[(index + 1) % candidates.length]!; }

  private acquire(runIdValue: string, customerId: string, campaignId: string, planned: RunPayload, nowMs: number, nowIso: string): RunRecord {
    for (let attempt = 0; attempt <= this.policy.maxWriteRetries; attempt += 1) {
      const existing = this.readRun(runIdValue, customerId, campaignId); if (existing) return existing; const state = this.readState(customerId, campaignId);
      if (state?.inFlightRunId && state.inFlightRunId !== runIdValue) { const inFlight = this.readRun(state.inFlightRunId, customerId, campaignId); if (!inFlight) throw new BiddingSupervisorError("INTEGRITY_FAILURE", "state references missing in-flight run"); return inFlight; }
      const cooldown = planned.action !== null && planned.reason !== "ROLLBACK_APPLIED" && state?.lastMutationAt != null && nowMs - Date.parse(state.lastMutationAt) < this.policy.cooldownMs; const runPayload: RunPayload = cooldown ? { ...planned, action: null, reason: "COOLDOWN" } : planned;
      const nextState: StatePayload = { policyDigest: this.policy.digest, lastRunAt: state?.lastRunAt ?? null, lastMutationAt: state?.lastMutationAt ?? null, lastActionKind: state?.lastActionKind ?? null, inFlightRunId: runIdValue, lastAppliedAction: state?.lastAppliedAction ?? null, lastRollbackAt: state?.lastRollbackAt ?? null };
      const operations: TransactionOperation[] = [{ kind: "CREATE_OBJECT", record: { id: this.runId(runIdValue, customerId, campaignId), typeId: RUN_TYPE, scope: this.scope, properties: runProperties(runIdValue, customerId, campaignId, this.policy.digest, "PREPARED", runPayload, nowIso, nowIso) } }, state ? { kind: "UPDATE_OBJECT", id: state.id, expectedRevision: state.revision, properties: stateProperties(customerId, campaignId, nextState, nowIso) } : { kind: "CREATE_OBJECT", record: { id: this.stateId(customerId, campaignId), typeId: STATE_TYPE, scope: this.scope, properties: stateProperties(customerId, campaignId, nextState, nowIso) } }];
      try { this.transactions.transact(this.scope, this.schema, operations); const stored = this.readRun(runIdValue, customerId, campaignId); if (!stored) throw new BiddingSupervisorError("PERSISTENCE_FAILURE", "prepared run unreadable after commit"); return stored; } catch (error) { if (conflict(error) && attempt < this.policy.maxWriteRetries) continue; if (conflict(error)) throw new BiddingSupervisorError("CONFLICT", "run preparation conflicted after retries"); if (error instanceof BiddingSupervisorError) throw error; throw new BiddingSupervisorError("PERSISTENCE_FAILURE", error instanceof Error ? error.message : "run preparation failed"); }
    }
    throw new BiddingSupervisorError("CONFLICT", "run preparation exhausted retries");
  }

  private finalize(run: RunRecord, status: Exclude<BiddingSupervisorRunStatus, "PREPARED">, runPayload: RunPayload, nowIso: string, effect: FinalizeEffect): RunRecord {
    for (let attempt = 0; attempt <= this.policy.maxWriteRetries; attempt += 1) {
      const current = this.readRun(run.runId, run.customerId, run.campaignId); if (!current) throw new BiddingSupervisorError("INTEGRITY_FAILURE", "run disappeared before finalize"); if (current.status !== "PREPARED") return current; const state = this.readState(run.customerId, run.campaignId); if (!state || state.inFlightRunId !== run.runId) throw new BiddingSupervisorError("INTEGRITY_FAILURE", "run no longer owns state lock");
      const nextState: StatePayload = { policyDigest: state.policyDigest, lastRunAt: nowIso, lastMutationAt: effect === "NONE" ? state.lastMutationAt : nowIso, lastActionKind: effect === "APPLY" && runPayload.action ? runPayload.action.kind : state.lastActionKind, inFlightRunId: null, lastAppliedAction: effect === "APPLY" && runPayload.action ? runPayload.action : effect === "ROLLBACK" ? null : state.lastAppliedAction, lastRollbackAt: effect === "ROLLBACK" ? nowIso : state.lastRollbackAt };
      try { this.transactions.transact(this.scope, this.schema, [{ kind: "UPDATE_OBJECT", id: current.id, expectedRevision: current.revision, properties: runProperties(current.runId, current.customerId, current.campaignId, current.policyDigest, status, runPayload, current.createdAt, nowIso) }, { kind: "UPDATE_OBJECT", id: state.id, expectedRevision: state.revision, properties: stateProperties(state.customerId, state.campaignId, nextState, nowIso) }]); const stored = this.readRun(run.runId, run.customerId, run.campaignId); if (!stored) throw new BiddingSupervisorError("PERSISTENCE_FAILURE", "finalized run unreadable after commit"); return stored; } catch (error) { if (conflict(error) && attempt < this.policy.maxWriteRetries) continue; if (conflict(error)) throw new BiddingSupervisorError("CONFLICT", "run finalize conflicted after retries"); if (error instanceof BiddingSupervisorError) throw error; throw new BiddingSupervisorError("PERSISTENCE_FAILURE", error instanceof Error ? error.message : "run finalize failed"); }
    }
    throw new BiddingSupervisorError("CONFLICT", "run finalize exhausted retries");
  }

  private async execute(run: RunRecord, executionMode: BiddingSupervisorMode): Promise<BiddingSupervisorResult> {
    if (run.status !== "PREPARED") return this.result(run); if (!run.action || run.mode !== "ACTIVE") return this.result(this.finalize(run, "NOOP", payload(run), this.time().iso, "NONE")); if (executionMode !== "ACTIVE") throw new BiddingSupervisorError("POLICY_VIOLATION", `${executionMode} freezes the prepared mutation; ACTIVE reconciliation is required before any remote write`); const rollback = run.reason === "ROLLBACK_APPLIED";
    let receipt: GoogleAdsMutationReceipt;
    try { receipt = await this.googleAds.applyMutation(run.customerId, run.action); }
    catch (error) { if (error instanceof GoogleAdsApiError && error.code === "AMBIGUOUS_MUTATION_OUTCOME") throw new BiddingSupervisorError("REMOTE_FAILURE", "Google Ads mutation outcome is ambiguous; run remains PREPARED for preflight recovery"); const reason: BiddingSupervisorReason = error instanceof GoogleAdsApiError && error.code === "REMOTE_CONFLICT" ? "REMOTE_CONFLICT" : "API_FAILURE"; const next: RunPayload = { ...payload(run), reason, receipt: null, errorCode: error instanceof GoogleAdsApiError ? error.code : "UNKNOWN_REMOTE_FAILURE" }; this.finalize(run, "FAILED", next, this.time().iso, "NONE"); throw new BiddingSupervisorError("REMOTE_FAILURE", `${reason}: Google Ads mutation was not certified as applied`); }
    const reason: BiddingSupervisorReason = rollback ? "ROLLBACK_APPLIED" : receipt.recoveredAlreadyApplied ? "ACTION_RECOVERED" : "ACTION_APPLIED"; const next: RunPayload = { ...payload(run), reason, receipt, errorCode: null }; return this.result(this.finalize(run, rollback ? "ROLLED_BACK" : "APPLIED", next, this.time().iso, rollback ? "ROLLBACK" : "APPLY"));
  }

  async supervise(input: BiddingSupervisorRunInput): Promise<BiddingSupervisorResult> {
    const requestedRunId = id(input.runId, "runId"); const customerId = numericId(input.customerId, "customerId"); const campaignId = numericId(input.campaignId, "campaignId"); const mode = effectiveMode(this.policy.mode, input.mode); const existing = this.readRun(requestedRunId, customerId, campaignId); if (existing) return this.execute(existing, mode); const initialState = this.readState(customerId, campaignId); if (initialState?.inFlightRunId) { const inFlight = this.readRun(initialState.inFlightRunId, customerId, campaignId); if (!inFlight) throw new BiddingSupervisorError("INTEGRITY_FAILURE", "state references missing in-flight run"); return this.execute(inFlight, mode); }
    const { ms: nowMs, iso: nowIso } = this.time(); const window = reportWindow(nowMs, this.policy); if (mode === "KILLED") { const runPayload: RunPayload = { mode, direction: "HOLD", reason: "KILL_SWITCH", windowStart: window.start, windowEnd: window.end, campaignSnapshot: null, portfolioSnapshot: null, businessSnapshot: null, evidence: null, action: null, receipt: null, errorCode: null }; return this.execute(this.acquire(requestedRunId, customerId, campaignId, runPayload, nowMs, nowIso), mode); }
    const campaign = await this.googleAds.getCampaignSnapshot(customerId, campaignId, window.startMs, window.endMs); const campaignQuery: BusinessProfitabilityQuery = { customerId, scopeKind: "CAMPAIGN", scopeId: campaignId, windowStart: window.start, windowEnd: window.end }; const campaignBusiness = Object.freeze({ ...(await this.business.getProfitability(campaignQuery)) }); const campaignFresh = validateBusiness(campaignBusiness, campaignQuery, nowMs, this.policy); const campaignEvidence = evidence(campaign, campaignBusiness);
    let portfolio: GoogleAdsPortfolioSnapshot | null = null; let portfolioBusiness: BusinessProfitabilitySnapshot | null = null; let portfolioEvidence: BiddingSupervisorEvidence | null = null; let portfolioFresh: "FRESH" | "STALE" | null = null; if (campaign.portfolioBiddingStrategyResourceName) { portfolio = await this.googleAds.getPortfolioSnapshot(customerId, campaign.portfolioBiddingStrategyResourceName, window.startMs, window.endMs); const query: BusinessProfitabilityQuery = { customerId, scopeKind: "BIDDING_STRATEGY", scopeId: portfolio.strategyId, windowStart: window.start, windowEnd: window.end }; portfolioBusiness = Object.freeze({ ...(await this.business.getProfitability(query)) }); portfolioFresh = validateBusiness(portfolioBusiness, query, nowMs, this.policy); portfolioEvidence = evidence(portfolio, portfolioBusiness); }
    let reason: BiddingSupervisorReason = "NO_COMPATIBLE_CONTROL"; let chosen: PlannedAction | null = null; const latest = this.readState(customerId, campaignId); if (campaign.status !== "ENABLED") reason = "CAMPAIGN_NOT_ENABLED"; else if (latest?.lastMutationAt && nowMs - Date.parse(latest.lastMutationAt) < this.policy.cooldownMs) reason = "COOLDOWN"; else { const candidates: PlannedAction[] = []; let fresh = false; let enough = false; let hold = false; if (campaignFresh === "FRESH") { fresh = true; if (sufficient(campaign, this.policy)) { enough = true; const direction = directionFor(campaignEvidence, this.policy); if (direction === "HOLD") hold = true; else candidates.push(...this.campaignCandidates(campaign, campaignBusiness, campaignEvidence, direction)); } } if (portfolio && portfolioBusiness && portfolioEvidence && portfolioFresh === "FRESH") { fresh = true; if (sufficient(portfolio, this.policy)) { enough = true; const direction = directionFor(portfolioEvidence, this.policy); if (direction === "HOLD") hold = true; else candidates.push(...this.portfolioCandidates(portfolio, portfolioBusiness, portfolioEvidence, direction)); } } chosen = this.choose(candidates, latest?.lastActionKind ?? null); if (chosen) reason = mode === "OBSERVE_ONLY" ? "OBSERVE_ONLY" : "ACTION_APPLIED"; else if (!fresh) reason = "STALE_BUSINESS_DATA"; else if (!enough) reason = "INSUFFICIENT_EVIDENCE"; else if (hold) reason = "PROFITABILITY_HOLD"; else if (campaign.budgetExplicitlyShared && !this.policy.allowSharedBudgets && !campaign.portfolioBiddingStrategyResourceName) reason = "SHARED_BUDGET_BLOCKED"; }
    const runPayload: RunPayload = { mode, direction: chosen?.direction ?? "HOLD", reason, windowStart: window.start, windowEnd: window.end, campaignSnapshot: campaign, portfolioSnapshot: portfolio, businessSnapshot: chosen?.business ?? campaignBusiness, evidence: chosen?.evidence ?? campaignEvidence, action: chosen?.action ?? null, receipt: null, errorCode: null }; return this.execute(this.acquire(requestedRunId, customerId, campaignId, runPayload, nowMs, nowIso), mode);
  }

  async rollbackLastMutation(input: BiddingSupervisorRollbackInput): Promise<BiddingSupervisorResult> {
    const runIdValue = id(input.runId, "runId"); const customerId = numericId(input.customerId, "customerId"); const campaignId = numericId(input.campaignId, "campaignId"); const existing = this.readRun(runIdValue, customerId, campaignId); if (existing) return this.execute(existing, "ACTIVE"); const state = this.readState(customerId, campaignId); if (!state?.lastAppliedAction) throw new BiddingSupervisorError("POLICY_VIOLATION", "no applied action is available for rollback"); if (state.inFlightRunId) { const inFlight = this.readRun(state.inFlightRunId, customerId, campaignId); if (!inFlight) throw new BiddingSupervisorError("INTEGRITY_FAILURE", "state references missing in-flight run"); return this.execute(inFlight, "ACTIVE"); }
    const { ms: nowMs, iso: nowIso } = this.time(); const window = reportWindow(nowMs, this.policy); const runPayload: RunPayload = { mode: "ACTIVE", direction: "HOLD", reason: "ROLLBACK_APPLIED", windowStart: window.start, windowEnd: window.end, campaignSnapshot: null, portfolioSnapshot: null, businessSnapshot: null, evidence: null, action: reverse(state.lastAppliedAction), receipt: null, errorCode: null }; return this.execute(this.acquire(runIdValue, customerId, campaignId, runPayload, nowMs, nowIso), "ACTIVE");
  }
}
