import { createHash } from "node:crypto";
import { canonicalJson, ontologyId, validateSchema, type OntologyScope, type SchemaVersion, type ValidatedSchema } from "@nexus/ontology";
import { OntologyTransactionError, type JsonValue, type ObjectRecord, type OntologyTransactionPort, type TransactionOperation } from "@nexus/ontology/transaction";
import type { BiddingSupervisorMode } from "./index";

const CONTROL_TYPE = "cortex.bidding_runtime_control";
const EVENT_TYPE = "cortex.bidding_runtime_control_event";
const MODES = new Set<BiddingSupervisorMode>(["ACTIVE", "OBSERVE_ONLY", "KILLED"]);
const DIGEST = /^sha256:[a-f0-9]{64}$/u;
const CONTROL = Object.freeze({ policyDigest: "cortex.bidding.control.policy_digest", mode: "cortex.bidding.control.mode", reason: "cortex.bidding.control.reason", changedAt: "cortex.bidding.control.changed_at", logicalRevision: "cortex.bidding.control.logical_revision", digest: "cortex.bidding.control.digest" });
const EVENT = Object.freeze({ policyDigest: "cortex.bidding.control_event.policy_digest", fromMode: "cortex.bidding.control_event.from_mode", toMode: "cortex.bidding.control_event.to_mode", reason: "cortex.bidding.control_event.reason", changedAt: "cortex.bidding.control_event.changed_at", targetRevision: "cortex.bidding.control_event.target_revision", digest: "cortex.bidding.control_event.digest" });

export interface BiddingRuntimeControlState { readonly policyDigest: string; readonly mode: BiddingSupervisorMode; readonly reason: string; readonly changedAt: string | null; readonly revision: number; readonly digest: string }
export interface BiddingRuntimeControlEvent { readonly policyDigest: string; readonly fromMode: BiddingSupervisorMode; readonly toMode: BiddingSupervisorMode; readonly reason: string; readonly changedAt: string; readonly targetRevision: number; readonly digest: string }
export interface SetBiddingRuntimeControlInput { readonly expectedRevision: number; readonly mode: BiddingSupervisorMode; readonly reason: string; readonly changedAt?: string }
export class BiddingRuntimeControlError extends Error { constructor(public readonly code: "INVALID_INPUT" | "CONFLICT" | "INTEGRITY_FAILURE" | "PERSISTENCE_FAILURE" | "POLICY_VIOLATION", message: string) { super(message); this.name = "BiddingRuntimeControlError"; } }

function hash(namespace: string, value: unknown): string { return `sha256:${createHash("sha256").update(`${namespace}\n${canonicalJson(value)}`, "utf8").digest("hex")}`; }
function validMode(value: unknown, code: "INVALID_INPUT" | "INTEGRITY_FAILURE" = "INVALID_INPUT"): BiddingSupervisorMode { if (typeof value !== "string" || !MODES.has(value as BiddingSupervisorMode)) throw new BiddingRuntimeControlError(code, "bidding runtime mode is invalid"); return value as BiddingSupervisorMode; }
function policyDigest(value: string): string { if (typeof value !== "string" || !DIGEST.test(value)) throw new BiddingRuntimeControlError("INVALID_INPUT", "policyDigest is malformed"); return value; }
function reason(value: string, code: "INVALID_INPUT" | "INTEGRITY_FAILURE" = "INVALID_INPUT"): string { if (typeof value !== "string") throw new BiddingRuntimeControlError(code, "reason must be a string"); const normalized = value.normalize("NFKC").trim(); if (normalized.length < 3 || normalized.length > 256) throw new BiddingRuntimeControlError(code, "reason must contain 3..256 characters"); for (const character of normalized) { const point = character.codePointAt(0) ?? 0; if (point < 0x20 || point === 0x7f) throw new BiddingRuntimeControlError(code, "reason contains a control character"); } return normalized; }
function utc(value: string, field: string, code: "INVALID_INPUT" | "INTEGRITY_FAILURE"): string { const parsed = new Date(value); if (!Number.isFinite(parsed.getTime()) || parsed.toISOString() !== value) throw new BiddingRuntimeControlError(code, `${field} must be canonical UTC`); return value; }
function revision(value: number, field: string, code: "INVALID_INPUT" | "INTEGRITY_FAILURE"): number { if (!Number.isSafeInteger(value) || value < 1) throw new BiddingRuntimeControlError(code, `${field} must be a positive safe integer`); return value; }
function property(id: string, name: string, valueKind: "STRING" | "NUMBER" | "DATETIME", immutable = false) { return { id, name, valueKind, cardinality: "REQUIRED", unique: false, immutable } as const; }
function schema(scope: OntologyScope): ValidatedSchema { const value: SchemaVersion = { version: "cortex-bidding-runtime-control-v2", scope, properties: [property(CONTROL.policyDigest, "BiddingControlPolicyDigest", "STRING"), property(CONTROL.mode, "BiddingControlMode", "STRING"), property(CONTROL.reason, "BiddingControlReason", "STRING"), property(CONTROL.changedAt, "BiddingControlChangedAt", "DATETIME"), property(CONTROL.logicalRevision, "BiddingControlLogicalRevision", "NUMBER"), property(CONTROL.digest, "BiddingControlDigest", "STRING"), property(EVENT.policyDigest, "BiddingControlEventPolicyDigest", "STRING", true), property(EVENT.fromMode, "BiddingControlEventFromMode", "STRING", true), property(EVENT.toMode, "BiddingControlEventToMode", "STRING", true), property(EVENT.reason, "BiddingControlEventReason", "STRING", true), property(EVENT.changedAt, "BiddingControlEventChangedAt", "DATETIME", true), property(EVENT.targetRevision, "BiddingControlEventTargetRevision", "NUMBER", true), property(EVENT.digest, "BiddingControlEventDigest", "STRING", true)], interfaces: [], objects: [{ id: CONTROL_TYPE, name: "CortexBiddingRuntimeControl", propertyIds: Object.values(CONTROL), interfaceIds: [] }, { id: EVENT_TYPE, name: "CortexBiddingRuntimeControlEvent", propertyIds: Object.values(EVENT), interfaceIds: [] }], relationships: [], actions: [], functions: [], events: [] }; return validateSchema(value); }
function stringProp(record: ObjectRecord, key: string): string { const value = record.properties[key]; if (typeof value !== "string") throw new BiddingRuntimeControlError("INTEGRITY_FAILURE", `record ${record.id} has invalid ${key}`); return value; }
function numberProp(record: ObjectRecord, key: string): number { const value = record.properties[key]; if (typeof value !== "number" || !Number.isFinite(value)) throw new BiddingRuntimeControlError("INTEGRITY_FAILURE", `record ${record.id} has invalid ${key}`); return value; }
function stateDigest(input: Omit<BiddingRuntimeControlState, "digest">): string { return hash("cortex-bidding-runtime-control-state-v2", input); }
function eventDigest(input: Omit<BiddingRuntimeControlEvent, "digest">): string { return hash("cortex-bidding-runtime-control-event-v2", input); }
function stateProps(input: Omit<BiddingRuntimeControlState, "digest">): Readonly<Record<string, JsonValue>> { return Object.freeze({ [CONTROL.policyDigest]: input.policyDigest, [CONTROL.mode]: input.mode, [CONTROL.reason]: input.reason, [CONTROL.changedAt]: input.changedAt, [CONTROL.logicalRevision]: input.revision, [CONTROL.digest]: stateDigest(input) }); }
function eventProps(input: Omit<BiddingRuntimeControlEvent, "digest">): Readonly<Record<string, JsonValue>> { return Object.freeze({ [EVENT.policyDigest]: input.policyDigest, [EVENT.fromMode]: input.fromMode, [EVENT.toMode]: input.toMode, [EVENT.reason]: input.reason, [EVENT.changedAt]: input.changedAt, [EVENT.targetRevision]: input.targetRevision, [EVENT.digest]: eventDigest(input) }); }
function parseState(record: ObjectRecord): BiddingRuntimeControlState { if (record.typeId !== CONTROL_TYPE) throw new BiddingRuntimeControlError("INTEGRITY_FAILURE", "control record has the wrong type"); const core = { policyDigest: policyDigest(stringProp(record, CONTROL.policyDigest)), mode: validMode(stringProp(record, CONTROL.mode), "INTEGRITY_FAILURE"), reason: reason(stringProp(record, CONTROL.reason), "INTEGRITY_FAILURE"), changedAt: utc(stringProp(record, CONTROL.changedAt), "stored changedAt", "INTEGRITY_FAILURE"), revision: revision(numberProp(record, CONTROL.logicalRevision), "stored revision", "INTEGRITY_FAILURE") }; if (core.revision !== record.revision) throw new BiddingRuntimeControlError("INTEGRITY_FAILURE", "control logical revision does not match transaction revision"); const observed = stringProp(record, CONTROL.digest); if (observed !== stateDigest(core)) throw new BiddingRuntimeControlError("INTEGRITY_FAILURE", "control digest mismatch"); return Object.freeze({ ...core, digest: observed }); }
function parseEvent(record: ObjectRecord): BiddingRuntimeControlEvent { if (record.typeId !== EVENT_TYPE) throw new BiddingRuntimeControlError("INTEGRITY_FAILURE", "control event has the wrong type"); const core = { policyDigest: policyDigest(stringProp(record, EVENT.policyDigest)), fromMode: validMode(stringProp(record, EVENT.fromMode), "INTEGRITY_FAILURE"), toMode: validMode(stringProp(record, EVENT.toMode), "INTEGRITY_FAILURE"), reason: reason(stringProp(record, EVENT.reason), "INTEGRITY_FAILURE"), changedAt: utc(stringProp(record, EVENT.changedAt), "stored changedAt", "INTEGRITY_FAILURE"), targetRevision: revision(numberProp(record, EVENT.targetRevision), "stored targetRevision", "INTEGRITY_FAILURE") }; const observed = stringProp(record, EVENT.digest); if (observed !== eventDigest(core)) throw new BiddingRuntimeControlError("INTEGRITY_FAILURE", "control event digest mismatch"); return Object.freeze({ ...core, digest: observed }); }
function rank(value: BiddingSupervisorMode): number { return value === "ACTIVE" ? 0 : value === "OBSERVE_ONLY" ? 1 : 2; }
function restrictive(left: BiddingSupervisorMode, right: BiddingSupervisorMode): BiddingSupervisorMode { return rank(left) >= rank(right) ? left : right; }
function conflict(error: unknown): boolean { return error instanceof OntologyTransactionError && error.code === "CONFLICT"; }

export class BiddingRuntimeController {
  readonly schema: ValidatedSchema;
  readonly policyDigest: string;
  readonly configuredMode: BiddingSupervisorMode;
  constructor(private readonly transactions: OntologyTransactionPort, readonly scope: OntologyScope, policyDigestValue: string, configuredModeValue: BiddingSupervisorMode, private readonly now: () => number = Date.now) { this.policyDigest = policyDigest(policyDigestValue); this.configuredMode = validMode(configuredModeValue); this.schema = schema(scope); }
  private controlId(): string { return ontologyId("cortex-bidding-runtime-control-v2", { scope: this.scope }); }
  private eventId(targetRevision: number): string { return ontologyId("cortex-bidding-runtime-control-event-v2", { scope: this.scope, targetRevision }); }
  current(): BiddingRuntimeControlState { const raw = this.transactions.getObject(this.scope, this.controlId()); if (!raw) { const core = { policyDigest: this.policyDigest, mode: this.configuredMode, reason: "configured runtime mode", changedAt: null, revision: 0 } as const; return Object.freeze({ ...core, digest: stateDigest(core) }); } return parseState(raw); }
  effectiveMode(): BiddingSupervisorMode { return restrictive(this.current().mode, this.configuredMode); }
  set(input: SetBiddingRuntimeControlInput): BiddingRuntimeControlState { if (!Number.isSafeInteger(input.expectedRevision) || input.expectedRevision < 0) throw new BiddingRuntimeControlError("INVALID_INPUT", "expectedRevision must be a non-negative safe integer"); const nextMode = validMode(input.mode); if (rank(nextMode) < rank(this.configuredMode)) throw new BiddingRuntimeControlError("POLICY_VIOLATION", "runtime control cannot weaken configured mode"); const nextReason = reason(input.reason); const changedAt = input.changedAt === undefined ? new Date(this.now()).toISOString() : utc(input.changedAt, "changedAt", "INVALID_INPUT"); const current = this.current(); if (current.revision !== input.expectedRevision) throw new BiddingRuntimeControlError("CONFLICT", "runtime control revision changed"); if (current.mode === nextMode && current.reason === nextReason && current.policyDigest === this.policyDigest) return current; const nextRevision = current.revision + 1; const nextCore = { policyDigest: this.policyDigest, mode: nextMode, reason: nextReason, changedAt, revision: nextRevision } as const; const eventCore = { policyDigest: this.policyDigest, fromMode: current.mode, toMode: nextMode, reason: nextReason, changedAt, targetRevision: nextRevision } as const; const operations: TransactionOperation[] = [current.revision === 0 ? { kind: "CREATE_OBJECT", record: { id: this.controlId(), typeId: CONTROL_TYPE, scope: this.scope, properties: stateProps(nextCore) } } : { kind: "UPDATE_OBJECT", id: this.controlId(), expectedRevision: current.revision, properties: stateProps(nextCore) }, { kind: "CREATE_OBJECT", record: { id: this.eventId(nextRevision), typeId: EVENT_TYPE, scope: this.scope, properties: eventProps(eventCore) } }]; try { this.transactions.transact(this.scope, this.schema, operations); } catch (error) { if (conflict(error)) throw new BiddingRuntimeControlError("CONFLICT", "runtime control changed concurrently"); if (error instanceof BiddingRuntimeControlError) throw error; throw new BiddingRuntimeControlError("PERSISTENCE_FAILURE", error instanceof Error ? error.message : "runtime control persistence failed"); } return this.current(); }
  history(limit = 32): readonly BiddingRuntimeControlEvent[] { if (!Number.isSafeInteger(limit) || limit < 1 || limit > 256) throw new BiddingRuntimeControlError("INVALID_INPUT", "history limit must be 1..256"); const current = this.current(); if (current.revision === 0) return Object.freeze([]); const start = Math.max(1, current.revision - limit + 1); const events: BiddingRuntimeControlEvent[] = []; for (let value = start; value <= current.revision; value += 1) { const raw = this.transactions.getObject(this.scope, this.eventId(value)); if (!raw) throw new BiddingRuntimeControlError("INTEGRITY_FAILURE", `runtime control history event ${value} is missing`); const event = parseEvent(raw); if (event.targetRevision !== value) throw new BiddingRuntimeControlError("INTEGRITY_FAILURE", `runtime control history event ${value} identity mismatch`); events.push(event); } return Object.freeze(events); }
}
