import type { CreativeDesiredState, CreativeDesiredStateProvider } from "./index";

const MAX_RESPONSE_BYTES=256*1024;
export interface HttpCreativeDesiredStateProviderConfig { readonly endpoint:string; readonly bearerToken:string; readonly timeoutMs?:number; readonly fetchImpl?:typeof fetch }
export class CreativeDesiredStateTransportError extends Error { constructor(readonly code:"INVALID_CONFIG"|"HTTP_ERROR"|"TIMEOUT"|"INVALID_RESPONSE",message:string){super(message);this.name="CreativeDesiredStateTransportError";} }
function endpoint(value:string):string{let url:URL;try{url=new URL(value);}catch{throw new CreativeDesiredStateTransportError("INVALID_CONFIG","desired-state endpoint is invalid");}if(url.protocol!=="https:"||url.username||url.password||url.hash)throw new CreativeDesiredStateTransportError("INVALID_CONFIG","desired-state endpoint must be credential-free https");return url.toString();}
function token(value:string):string{const normalized=value.trim();if(normalized.length<32||normalized.length>4096)throw new CreativeDesiredStateTransportError("INVALID_CONFIG","desired-state token must contain 32..4096 characters");return normalized;}
function timeout(value:number|undefined):number{const resolved=value??10_000;if(!Number.isSafeInteger(resolved)||resolved<1_000||resolved>60_000)throw new CreativeDesiredStateTransportError("INVALID_CONFIG","timeoutMs must be 1000..60000");return resolved;}
async function boundedJson(response:Response):Promise<unknown>{if(response.headers.get("content-type")?.split(";",1)[0]?.trim().toLowerCase()!=="application/json")throw new CreativeDesiredStateTransportError("INVALID_RESPONSE","desired-state response must use application/json");if(!response.body)throw new CreativeDesiredStateTransportError("INVALID_RESPONSE","desired-state response body is missing");const reader=response.body.getReader();const chunks:Uint8Array[]=[];let total=0;try{for(;;){const next=await reader.read();if(next.done)break;total+=next.value.byteLength;if(total>MAX_RESPONSE_BYTES){await reader.cancel();throw new CreativeDesiredStateTransportError("INVALID_RESPONSE",`desired-state response exceeds ${MAX_RESPONSE_BYTES} bytes`);}chunks.push(next.value);}}finally{reader.releaseLock();}const merged=new Uint8Array(total);let offset=0;for(const chunk of chunks){merged.set(chunk,offset);offset+=chunk.byteLength;}try{return JSON.parse(new TextDecoder().decode(merged)) as unknown;}catch{throw new CreativeDesiredStateTransportError("INVALID_RESPONSE","desired-state response contains malformed JSON");}}
export class HttpCreativeDesiredStateProvider implements CreativeDesiredStateProvider {
  private readonly url:string;private readonly token:string;private readonly timeoutMs:number;private readonly fetchImpl:typeof fetch;
  constructor(config:HttpCreativeDesiredStateProviderConfig){this.url=endpoint(config.endpoint);this.token=token(config.bearerToken);this.timeoutMs=timeout(config.timeoutMs);this.fetchImpl=config.fetchImpl??fetch;}
  async getDesiredState(customerId:string):Promise<CreativeDesiredState>{if(!/^\d{5,20}$/u.test(customerId))throw new CreativeDesiredStateTransportError("INVALID_CONFIG","customerId is malformed");const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),this.timeoutMs);try{const response=await this.fetchImpl(this.url,{method:"POST",redirect:"error",cache:"no-store",signal:controller.signal,headers:{authorization:`Bearer ${this.token}`,"content-type":"application/json"},body:JSON.stringify({customerId})});if(!response.ok)throw new CreativeDesiredStateTransportError("HTTP_ERROR",`desired-state endpoint returned HTTP ${response.status}`);const value=await boundedJson(response);if(!value||typeof value!=="object"||Array.isArray(value))throw new CreativeDesiredStateTransportError("INVALID_RESPONSE","desired-state response must be an object");return value as CreativeDesiredState;}catch(error){if(error instanceof CreativeDesiredStateTransportError)throw error;if(error instanceof DOMException&&error.name==="AbortError")throw new CreativeDesiredStateTransportError("TIMEOUT","desired-state endpoint timed out");throw new CreativeDesiredStateTransportError("HTTP_ERROR","desired-state transport failed");}finally{clearTimeout(timer);}}
}
