import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { SqliteOntologyTransactionStore } from "../sqlite-transaction-store";
import type { CreativeDesiredState, CreativeDesiredStateProvider, CreativeMutationReceipt, CreativeSyncAction, GoogleAdsCreativeGateway, ResponsiveSearchAdContent, ResponsiveSearchAdSnapshot } from "./index";
import { createCreativeProductionRuntime, parseCreativeProductionConfig, type CreativeProductionRuntime } from "./production-runtime";

const CUSTOMER="1234567890";const AD=`customers/${CUSTOMER}/ads/3333333333`;const RUN_TOKEN="creative-run-token-000000000000000000000000";const CONTROL_TOKEN="creative-control-token-000000000000000000000";const directories:string[]=[];
afterEach(()=>{for(const directory of directories.splice(0))rmSync(directory,{recursive:true,force:true});});
function content(headline:string):ResponsiveSearchAdContent{return Object.freeze({headlines:Object.freeze([{text:headline,pinnedField:"HEADLINE_1" as const},{text:"Legal strategy",pinnedField:null},{text:"Talk to our team",pinnedField:null}]),descriptions:Object.freeze([{text:"Get clear next steps for your legal matter.",pinnedField:null},{text:"Schedule a consultation with our legal team.",pinnedField:null}]),path1:"legal",path2:"consulta",finalUrls:Object.freeze(["https://example.com/legal"]),finalMobileUrls:Object.freeze([])});}
function config(){return parseCreativeProductionConfig({version:1,scope:{tenantId:"tenant:creative-production",organizationId:"org:creative-production"},intervalMs:60_000,policy:{policyId:"creative-production-v1",version:"v1",maxSourceAgeMs:300_000,maxDesiredResponsiveSearchAds:100,maxDesiredCustomizerValues:500,maxWriteRetries:3,mode:"ACTIVE"},customers:[CUSTOMER]});}
class Source implements CreativeDesiredStateProvider{calls=0;constructor(private readonly now:()=>number){}async getDesiredState():Promise<CreativeDesiredState>{this.calls+=1;return Object.freeze({sourceId:"creative-control-plane",sourceVersion:`version-${this.calls}`,observedAt:new Date(this.now()).toISOString(),customizerAttributes:Object.freeze([]),customizerValues:Object.freeze([]),responsiveSearchAds:Object.freeze([{resourceName:AD,...content("Book your consultation")}])});}}
class Gateway implements GoogleAdsCreativeGateway{mutations=0;rsa:ResponsiveSearchAdSnapshot=Object.freeze({resourceName:AD,adId:"3333333333",adGroupResourceName:`customers/${CUSTOMER}/adGroups/4444444444`,status:"ENABLED",...content("Old headline")});async getCustomizerAttributes(){return Object.freeze([]);}async getCustomizerValue(){return null;}async getResponsiveSearchAd(){return this.rsa;}async applyMutation(_customerId:string,action:CreativeSyncAction):Promise<CreativeMutationReceipt>{this.mutations+=1;if(action.kind!=="UPDATE_RSA")throw new Error("fixture expects RSA mutation");this.rsa=Object.freeze({...this.rsa,...action.desired});return Object.freeze({requestId:`request-${this.mutations}`,resourceName:action.resourceName,recoveredAlreadyApplied:false});}}
async function listen(runtime:CreativeProductionRuntime):Promise<string>{await new Promise<void>((resolve,reject)=>{runtime.server.once("error",reject);runtime.server.listen(0,"127.0.0.1",()=>resolve());});const address=runtime.server.address();if(!address||typeof address==="string")throw new Error("runtime did not expose TCP address");return `http://127.0.0.1:${address.port}`;}
async function api(base:string,path:string,token:string,init:RequestInit={}):Promise<Response>{const headers=new Headers(init.headers);headers.set("authorization",`Bearer ${token}`);if(init.body!==undefined)headers.set("content-type","application/json");return fetch(`${base}${path}`,{...init,headers});}

describe("CORTEX creative production runtime",()=>{
  it("persists kill state, blocks forward writes, and permits explicit rollback across restart",async()=>{const directory=mkdtempSync(join(tmpdir(),"nexus-creative-production-"));directories.push(directory);const dbPath=join(directory,"cortex.sqlite");let now=Date.parse("2026-09-06T01:30:00.000Z");const google=new Gateway();const source=new Source(()=>now);let store=new SqliteOntologyTransactionStore(dbPath);let runtime=createCreativeProductionRuntime({transactions:store,config:config(),googleAds:google,desiredState:source,runToken:RUN_TOKEN,controlToken:CONTROL_TOKEN,now:()=>now});let base=await listen(runtime);
    const first=await runtime.runOnce("MANUAL");expect(first[0]).toMatchObject({status:"APPLIED",reason:"ACTION_APPLIED",action:{kind:"UPDATE_RSA"}});expect(google.mutations).toBe(1);
    const kill=await api(base,"/v1/creative/control",CONTROL_TOKEN,{method:"POST",body:JSON.stringify({expectedRevision:0,mode:"KILLED",reason:"emergency stop for production investigation"})});expect(kill.status).toBe(200);expect(await kill.json()).toMatchObject({state:{mode:"KILLED",revision:1}});
    now+=60_000;const calls=source.calls;const killed=await runtime.runOnce("SCHEDULED");expect(killed[0]).toMatchObject({status:"NOOP",reason:"KILL_SWITCH",mode:"KILLED"});expect(source.calls).toBe(calls);expect(google.mutations).toBe(1);
    await runtime.close();store.close();store=new SqliteOntologyTransactionStore(dbPath);runtime=createCreativeProductionRuntime({transactions:store,config:config(),googleAds:google,desiredState:source,runToken:RUN_TOKEN,controlToken:CONTROL_TOKEN,now:()=>now});base=await listen(runtime);
    const persisted=await api(base,"/v1/creative/control",CONTROL_TOKEN);expect(await persisted.json()).toMatchObject({state:{mode:"KILLED",revision:1},history:[{fromMode:"ACTIVE",toMode:"KILLED",targetRevision:1}]});
    const rollback=await api(base,"/v1/creative/rollback",CONTROL_TOKEN,{method:"POST",body:JSON.stringify({customerId:CUSTOMER,runId:"rollback-001"})});expect(rollback.status).toBe(200);expect(await rollback.json()).toMatchObject({result:{status:"ROLLED_BACK",reason:"ROLLBACK_APPLIED"}});expect(google.mutations).toBe(2);expect(google.rsa.headlines[0]?.text).toBe("Old headline");await runtime.close();store.close();
  });
  it("rejects unknown configuration fields",()=>{expect(()=>parseCreativeProductionConfig({...config(),unexpected:true})).toThrow(/unknown field unexpected/i);});
});
