import { timingSafeEqual } from "node:crypto";
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import type { OntologyScope } from "@nexus/ontology";
import type { OntologyTransactionPort } from "@nexus/ontology/transaction";
import {
  CreativeSyncError,
  NearRealTimeCreativeSynchronizer,
  createCreativeSyncPolicy,
  type CreateCreativeSyncPolicyInput,
  type CreativeDesiredStateProvider,
  type CreativeSyncMode,
  type CreativeSyncPolicy,
  type CreativeSyncResult,
  type GoogleAdsCreativeGateway,
} from "./index";
import { CreativeRuntimeController, CreativeRuntimeControlError } from "./runtime-control";

const MAX_BODY_BYTES = 16_384;
const IDENTIFIER = /^[A-Za-z0-9](?:[A-Za-z0-9._:-]{0,127})$/u;
const CUSTOMER_ID = /^\d{5,20}$/u;
const POLICY_KEYS = new Set(["policyId","version","maxSourceAgeMs","maxDesiredResponsiveSearchAds","maxDesiredCustomizerValues","maxWriteRetries","mode"]);

export interface CreativeProductionConfig { readonly version: 1; readonly scope: OntologyScope; readonly intervalMs: number; readonly policy: CreateCreativeSyncPolicyInput; readonly customers: readonly string[] }
export interface CreativeRuntimeTelemetryEvent { readonly operation: "CYCLE"|"CUSTOMER"|"ROLLBACK"|"CONTROL_READ"|"CONTROL_WRITE"|"HEALTH"; readonly status: "OK"|"FAILED"|"SKIPPED"|"REJECTED"; readonly trigger: "STARTUP"|"SCHEDULED"|"MANUAL"|null; readonly customerId: string|null; readonly mode: CreativeSyncMode|null; readonly reason: string|null; readonly durationMs: number; readonly errorCode: string|null }
export interface CreativeProductionRuntimeOptions { readonly transactions: OntologyTransactionPort; readonly config: CreativeProductionConfig; readonly googleAds: GoogleAdsCreativeGateway; readonly desiredState: CreativeDesiredStateProvider; readonly runToken: string; readonly controlToken: string; readonly now?:()=>number; readonly onTelemetry?:(event:CreativeRuntimeTelemetryEvent)=>void; readonly onTelemetryError?:(error:unknown)=>void }
export interface CreativeProductionRuntime { readonly server: Server; readonly policy: CreativeSyncPolicy; runOnce(trigger:"STARTUP"|"SCHEDULED"|"MANUAL", customerId?:string):Promise<readonly CreativeSyncResult[]>; start(runImmediately?:boolean):void; close():Promise<void> }

class HttpError extends Error { constructor(readonly status:number,readonly code:string){super(code);this.name="CreativeProductionHttpError";} }
function object(value:unknown,label:string):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error(`${label} must be an object`);const proto=Object.getPrototypeOf(value);if(proto!==Object.prototype&&proto!==null)throw new Error(`${label} must be a plain object`);return value as Record<string,unknown>;}
function exact(value:Record<string,unknown>,allowed:ReadonlySet<string>,label:string):void{for(const key of Object.keys(value))if(!allowed.has(key))throw new Error(`${label} contains unknown field ${key}`);}
function id(value:unknown,label:string):string{if(typeof value!=="string"||!IDENTIFIER.test(value.trim()))throw new Error(`${label} is malformed`);return value.trim();}
function customer(value:unknown,label="customerId"):string{if(typeof value!=="string")throw new Error(`${label} must be a string`);const normalized=value.replaceAll("-","").trim();if(!CUSTOMER_ID.test(normalized))throw new Error(`${label} is malformed`);return normalized;}
function scopeFrom(value:unknown):OntologyScope{const raw=object(value,"scope");exact(raw,new Set(["tenantId","organizationId","brandId"]),"scope");const tenantId=id(raw.tenantId,"scope.tenantId");const organizationId=id(raw.organizationId,"scope.organizationId");const brandId=raw.brandId;return Object.freeze({tenantId,organizationId,...(brandId===undefined?{}:{brandId:id(brandId,"scope.brandId")})});}
function policyFrom(value:unknown):CreateCreativeSyncPolicyInput{const raw=object(value,"policy");exact(raw,POLICY_KEYS,"policy");const input=raw as unknown as CreateCreativeSyncPolicyInput;createCreativeSyncPolicy(input);return input;}
export function parseCreativeProductionConfig(value:unknown):CreativeProductionConfig{const raw=object(value,"creative production config");exact(raw,new Set(["version","scope","intervalMs","policy","customers"]),"creative production config");if(raw.version!==1)throw new Error("creative production config version must be 1");if(!Number.isSafeInteger(raw.intervalMs)||(raw.intervalMs as number)<60_000||(raw.intervalMs as number)>86_400_000)throw new Error("intervalMs must be 60000..86400000");if(!Array.isArray(raw.customers)||raw.customers.length<1||raw.customers.length>100)throw new Error("customers must contain 1..100 customer IDs");const customers=Object.freeze(raw.customers.map((entry,index)=>customer(entry,`customers[${index}]`)));if(new Set(customers).size!==customers.length)throw new Error("customers must be unique");return Object.freeze({version:1,scope:scopeFrom(raw.scope),intervalMs:raw.intervalMs as number,policy:policyFrom(raw.policy),customers});}
function token(value:string,label:string):Buffer{if(typeof value!=="string"||value.trim().length<32||value.trim().length>4096)throw new Error(`${label} must contain 32..4096 characters`);return Buffer.from(value.trim(),"utf8");}
function auth(request:IncomingMessage,expected:Buffer):boolean{const raw=request.headers.authorization;if(typeof raw!=="string"||!raw.startsWith("Bearer "))return false;const candidate=Buffer.from(raw.slice(7),"utf8");return candidate.length===expected.length&&timingSafeEqual(candidate,expected);}
async function body(request:IncomingMessage):Promise<Record<string,unknown>>{if(request.headers["content-type"]?.split(";",1)[0]?.trim().toLowerCase()!=="application/json")throw new HttpError(415,"JSON_REQUIRED");let bytes=0;const chunks:Buffer[]=[];for await(const part of request){const chunk=Buffer.isBuffer(part)?part:Buffer.from(part);bytes+=chunk.byteLength;if(bytes>MAX_BODY_BYTES){request.resume();throw new HttpError(413,"BODY_TOO_LARGE");}chunks.push(chunk);}if(!bytes)throw new HttpError(400,"BODY_REQUIRED");let parsed:unknown;try{parsed=JSON.parse(Buffer.concat(chunks).toString("utf8")) as unknown;}catch{throw new HttpError(400,"INVALID_JSON");}try{return object(parsed,"request body");}catch{throw new HttpError(400,"INVALID_BODY");}}
function requestExact(value:Record<string,unknown>,allowed:readonly string[]):void{for(const key of Object.keys(value))if(!allowed.includes(key))throw new HttpError(400,"INVALID_BODY");}
function write(response:ServerResponse,status:number,value:unknown):void{const raw=JSON.stringify(value);response.statusCode=status;response.setHeader("content-type","application/json; charset=utf-8");response.setHeader("cache-control","no-store");response.setHeader("content-length",Buffer.byteLength(raw));response.end(raw);}
function statusFor(error:unknown):number{if(error instanceof HttpError)return error.status;if(error instanceof CreativeRuntimeControlError)return error.code==="CONFLICT"?409:error.code==="PERSISTENCE_FAILURE"||error.code==="INTEGRITY_FAILURE"?503:400;if(error instanceof CreativeSyncError)return error.code==="CONFLICT"?409:error.code==="PERSISTENCE_FAILURE"||error.code==="INTEGRITY_FAILURE"||error.code==="REMOTE_FAILURE"?503:400;return 500;}
function codeFor(error:unknown):string{if(error instanceof HttpError)return error.code;if(error instanceof CreativeRuntimeControlError||error instanceof CreativeSyncError)return error.code;return "UNEXPECTED";}

export function createCreativeProductionRuntime(options:CreativeProductionRuntimeOptions):CreativeProductionRuntime{
  const runToken=token(options.runToken,"runToken");const controlToken=token(options.controlToken,"controlToken");if(runToken.length===controlToken.length&&timingSafeEqual(runToken,controlToken))throw new Error("runToken and controlToken must be distinct");
  const now=options.now??Date.now;const policy=createCreativeSyncPolicy(options.config.policy);const control=new CreativeRuntimeController(options.transactions,options.config.scope,policy.digest,policy.mode,now);let rollbackAuthorized=false;let safetyOperation=false;let cycle:Promise<readonly CreativeSyncResult[]>|null=null;let interval:ReturnType<typeof setInterval>|null=null;
  const emit=(event:CreativeRuntimeTelemetryEvent)=>{try{options.onTelemetry?.(Object.freeze(event));}catch(error){try{options.onTelemetryError?.(error);}catch{/* telemetry is non-authoritative */}}};
  const guarded:GoogleAdsCreativeGateway=Object.freeze({
    getCustomizerAttributes:(customerId)=>options.googleAds.getCustomizerAttributes(customerId),
    getCustomizerValue:(customerId,lookup)=>options.googleAds.getCustomizerValue(customerId,lookup),
    getResponsiveSearchAd:(customerId,resourceName)=>options.googleAds.getResponsiveSearchAd(customerId,resourceName),
    applyMutation:async(customerId,action)=>{const effective=control.effectiveMode();if(!rollbackAuthorized&&effective!=="ACTIVE")throw new CreativeSyncError("POLICY_VIOLATION",`${effective} blocks forward Google Ads creative mutation`);return options.googleAds.applyMutation(customerId,action);},
  });
  const engine=new NearRealTimeCreativeSynchronizer(options.transactions,options.config.scope,policy,guarded,options.desiredState,now);
  const configured=new Set(options.config.customers);
  const runCycle=async(trigger:"STARTUP"|"SCHEDULED"|"MANUAL",only?:string):Promise<readonly CreativeSyncResult[]>=>{
    if(safetyOperation)throw new CreativeSyncError("CONFLICT","rollback safety operation is running");if(cycle)return cycle;
    const selected=only===undefined?options.config.customers:[customer(only)];if(selected.some((entry)=>!configured.has(entry)))throw new CreativeSyncError("POLICY_VIOLATION","customer is not configured for creative synchronization");
    const started=now();const promise=(async()=>{const bucket=Math.floor(now()/options.config.intervalMs);const results:CreativeSyncResult[]=[];let firstError:unknown=null;for(const customerId of selected){const customerStarted=now();const mode=control.effectiveMode();try{const result=await engine.synchronize({runId:`creative-${customerId}-${bucket}`,customerId,mode});results.push(result);emit({operation:"CUSTOMER",status:"OK",trigger,customerId,mode:result.mode,reason:result.reason,durationMs:Math.max(0,now()-customerStarted),errorCode:null});}catch(error){if(firstError===null)firstError=error;emit({operation:"CUSTOMER",status:"FAILED",trigger,customerId,mode,reason:null,durationMs:Math.max(0,now()-customerStarted),errorCode:codeFor(error)});}}if(firstError!==null)throw firstError;return Object.freeze(results);})();cycle=promise;try{const results=await promise;emit({operation:"CYCLE",status:"OK",trigger,customerId:only??null,mode:control.effectiveMode(),reason:null,durationMs:Math.max(0,now()-started),errorCode:null});return results;}catch(error){emit({operation:"CYCLE",status:"FAILED",trigger,customerId:only??null,mode:control.effectiveMode(),reason:null,durationMs:Math.max(0,now()-started),errorCode:codeFor(error)});throw error;}finally{cycle=null;}}
  const rollback=async(customerId:string,runId:string):Promise<CreativeSyncResult>=>{const normalized=customer(customerId);if(!configured.has(normalized))throw new CreativeSyncError("POLICY_VIOLATION","customer is not configured for creative synchronization");if(cycle||safetyOperation)throw new CreativeSyncError("CONFLICT","another creative operation is running");safetyOperation=true;rollbackAuthorized=true;const started=now();try{const result=await engine.rollbackLastMutation({runId:id(runId,"runId"),customerId:normalized});emit({operation:"ROLLBACK",status:"OK",trigger:null,customerId:normalized,mode:control.effectiveMode(),reason:result.reason,durationMs:Math.max(0,now()-started),errorCode:null});return result;}catch(error){emit({operation:"ROLLBACK",status:"FAILED",trigger:null,customerId:normalized,mode:control.effectiveMode(),reason:null,durationMs:Math.max(0,now()-started),errorCode:codeFor(error)});throw error;}finally{rollbackAuthorized=false;safetyOperation=false;}};
  const server=createServer(async(request,response)=>{const started=now();try{const method=request.method??"GET";const url=new URL(request.url??"/","http://cortex.invalid");if(method==="GET"&&url.pathname==="/healthz"){const state=control.current();write(response,200,{ok:true,mode:control.effectiveMode(),revision:state.revision});emit({operation:"HEALTH",status:"OK",trigger:null,customerId:null,mode:control.effectiveMode(),reason:null,durationMs:Math.max(0,now()-started),errorCode:null});return;}
    if(method==="POST"&&url.pathname==="/v1/creative/run"){if(!auth(request,runToken))throw new HttpError(401,"UNAUTHORIZED");const input=await body(request);requestExact(input,["customerId"]);if(input.customerId!==undefined&&typeof input.customerId!=="string")throw new HttpError(400,"INVALID_BODY");const results=await runCycle("MANUAL",input.customerId as string|undefined);write(response,200,{results});return;}
    if(method==="GET"&&url.pathname==="/v1/creative/control"){if(!auth(request,controlToken))throw new HttpError(401,"UNAUTHORIZED");write(response,200,{state:control.current(),effectiveMode:control.effectiveMode(),configuredMode:control.configuredMode,currentPolicyDigest:control.policyDigest,history:control.history(64)});emit({operation:"CONTROL_READ",status:"OK",trigger:null,customerId:null,mode:control.effectiveMode(),reason:null,durationMs:Math.max(0,now()-started),errorCode:null});return;}
    if(method==="POST"&&url.pathname==="/v1/creative/control"){if(!auth(request,controlToken))throw new HttpError(401,"UNAUTHORIZED");const input=await body(request);requestExact(input,["expectedRevision","mode","reason","changedAt"]);if(typeof input.expectedRevision!=="number"||typeof input.mode!=="string"||typeof input.reason!=="string"||(input.changedAt!==undefined&&typeof input.changedAt!=="string"))throw new HttpError(400,"INVALID_BODY");const state=control.set({expectedRevision:input.expectedRevision,mode:input.mode as CreativeSyncMode,reason:input.reason,...(input.changedAt===undefined?{}:{changedAt:input.changedAt})});write(response,200,{state,effectiveMode:control.effectiveMode()});emit({operation:"CONTROL_WRITE",status:"OK",trigger:null,customerId:null,mode:state.mode,reason:state.reason,durationMs:Math.max(0,now()-started),errorCode:null});return;}
    if(method==="POST"&&url.pathname==="/v1/creative/rollback"){if(!auth(request,controlToken))throw new HttpError(401,"UNAUTHORIZED");const input=await body(request);requestExact(input,["customerId","runId"]);if(typeof input.customerId!=="string"||typeof input.runId!=="string")throw new HttpError(400,"INVALID_BODY");const result=await rollback(input.customerId,input.runId);write(response,200,{result});return;}write(response,404,{error:"NOT_FOUND"});
  }catch(error){const status=statusFor(error);if(!response.headersSent&&!response.writableEnded)write(response,status,{error:codeFor(error)});}});
  return Object.freeze({server,policy,runOnce:runCycle,start:(runImmediately=true)=>{if(interval)return;if(runImmediately)void runCycle("STARTUP").catch(()=>undefined);interval=setInterval(()=>{void runCycle("SCHEDULED").catch(()=>undefined);},options.config.intervalMs);interval.unref?.();},close:()=>new Promise<void>((resolve,reject)=>{if(interval){clearInterval(interval);interval=null;}if(!server.listening){resolve();return;}server.close(error=>error?reject(error):resolve());})});
}
