import { createHash } from "node:crypto";
import { canonicalJson, ontologyId, validateSchema, type OntologyScope, type SchemaVersion, type ValidatedSchema } from "@nexus/ontology";
import { OntologyTransactionError, type JsonValue, type ObjectRecord, type OntologyTransactionPort, type TransactionOperation } from "@nexus/ontology/transaction";
import type { CreativeSyncMode } from "./index";

const CONTROL_TYPE = "cortex.creative_runtime_control";
const EVENT_TYPE = "cortex.creative_runtime_control_event";
const MODES = new Set<CreativeSyncMode>(["ACTIVE", "OBSERVE_ONLY", "KILLED"]);
const DIGEST = /^sha256:[a-f0-9]{64}$/u;
const C = Object.freeze({ policyDigest: "cortex.creative.control.policy_digest", mode: "cortex.creative.control.mode", reason: "cortex.creative.control.reason", changedAt: "cortex.creative.control.changed_at", logicalRevision: "cortex.creative.control.logical_revision", digest: "cortex.creative.control.digest" });
const E = Object.freeze({ policyDigest: "cortex.creative.control_event.policy_digest", fromMode: "cortex.creative.control_event.from_mode", toMode: "cortex.creative.control_event.to_mode", reason: "cortex.creative.control_event.reason", changedAt: "cortex.creative.control_event.changed_at", targetRevision: "cortex.creative.control_event.target_revision", digest: "cortex.creative.control_event.digest" });

export interface CreativeRuntimeControlState { readonly policyDigest: string; readonly mode: CreativeSyncMode; readonly reason: string; readonly changedAt: string | null; readonly revision: number; readonly digest: string }
export interface CreativeRuntimeControlEvent { readonly policyDigest: string; readonly fromMode: CreativeSyncMode; readonly toMode: CreativeSyncMode; readonly reason: string; readonly changedAt: string; readonly targetRevision: number; readonly digest: string }
export interface SetCreativeRuntimeControlInput { readonly expectedRevision: number; readonly mode: CreativeSyncMode; readonly reason: string; readonly changedAt?: string }
export class CreativeRuntimeControlError extends Error { constructor(readonly code: "INVALID_INPUT" | "CONFLICT" | "INTEGRITY_FAILURE" | "PERSISTENCE_FAILURE" | "POLICY_VIOLATION", message: string) { super(message); this.name = "CreativeRuntimeControlError"; } }

function hash(namespace: string, value: unknown): string { return `sha256:${createHash("sha256").update(`${namespace}\n${canonicalJson(value)}`, "utf8").digest("hex")}`; }
function digest(value: string, code: "INVALID_INPUT" | "INTEGRITY_FAILURE" = "INVALID_INPUT"): string { if (typeof value !== "string" || !DIGEST.test(value)) throw new CreativeRuntimeControlError(code, "policyDigest is malformed"); return value; }
function mode(value: unknown, code: "INVALID_INPUT" | "INTEGRITY_FAILURE" = "INVALID_INPUT"): CreativeSyncMode { if (typeof value !== "string" || !MODES.has(value as CreativeSyncMode)) throw new CreativeRuntimeControlError(code, "creative runtime mode is invalid"); return value as CreativeSyncMode; }
function reason(value: string, code: "INVALID_INPUT" | "INTEGRITY_FAILURE" = "INVALID_INPUT"): string { if (typeof value !== "string") throw new CreativeRuntimeControlError(code, "reason must be a string"); const normalized = value.normalize("NFKC").trim(); if (normalized.length < 3 || normalized.length > 256) throw new CreativeRuntimeControlError(code, "reason must contain 3..256 characters"); for (const ch of normalized) { const point = ch.codePointAt(0) ?? 0; if (point < 0x20 || point === 0x7f) throw new CreativeRuntimeControlError(code, "reason contains a control character"); } return normalized; }
function utc(value: string, field: string, code: "INVALID_INPUT" | "INTEGRITY_FAILURE"): string { const parsed = new Date(value); if (!Number.isFinite(parsed.getTime()) || parsed.toISOString() !== value) throw new CreativeRuntimeControlError(code, `${field} must be canonical UTC`); return value; }
function revision(value: number, field: string, code: "INVALID_INPUT" | "INTEGRITY_FAILURE"): number { if (!Number.isSafeInteger(value) || value < 1) throw new CreativeRuntimeControlError(code, `${field} must be a positive safe integer`); return value; }
function property(id: string, name: string, valueKind: "STRING" | "NUMBER" | "DATETIME", immutable = false) { return { id, name, valueKind, cardinality: "REQUIRED", unique: false, immutable } as const; }
function schema(scope: OntologyScope): ValidatedSchema { const value: SchemaVersion = { version: "cortex-creative-runtime-control-v1", scope, properties: [property(C.policyDigest,"CreativeControlPolicyDigest","STRING"),property(C.mode,"CreativeControlMode","STRING"),property(C.reason,"CreativeControlReason","STRING"),property(C.changedAt,"CreativeControlChangedAt","DATETIME"),property(C.logicalRevision,"CreativeControlLogicalRevision","NUMBER"),property(C.digest,"CreativeControlDigest","STRING"),property(E.policyDigest,"CreativeControlEventPolicyDigest","STRING",true),property(E.fromMode,"CreativeControlEventFromMode","STRING",true),property(E.toMode,"CreativeControlEventToMode","STRING",true),property(E.reason,"CreativeControlEventReason","STRING",true),property(E.changedAt,"CreativeControlEventChangedAt","DATETIME",true),property(E.targetRevision,"CreativeControlEventTargetRevision","NUMBER",true),property(E.digest,"CreativeControlEventDigest","STRING",true)], interfaces: [], objects: [{ id: CONTROL_TYPE, name: "CortexCreativeRuntimeControl", propertyIds: Object.values(C), interfaceIds: [] }, { id: EVENT_TYPE, name: "CortexCreativeRuntimeControlEvent", propertyIds: Object.values(E), interfaceIds: [] }], relationships: [], actions: [], functions: [], events: [] }; return validateSchema(value); }
function stringProp(record: ObjectRecord, key: string): string { const value = record.properties[key]; if (typeof value !== "string") throw new CreativeRuntimeControlError("INTEGRITY_FAILURE", `record ${record.id} has invalid ${key}`); return value; }
function numberProp(record: ObjectRecord, key: string): number { const value = record.properties[key]; if (typeof value !== "number" || !Number.isSafeInteger(value)) throw new CreativeRuntimeControlError("INTEGRITY_FAILURE", `record ${record.id} has invalid ${key}`); return value; }
function stateDigest(value: Omit<CreativeRuntimeControlState,"digest">): string { return hash("cortex-creative-runtime-control-state-v1", value); }
function eventDigest(value: Omit<CreativeRuntimeControlEvent,"digest">): string { return hash("cortex-creative-runtime-control-event-v1", value); }
function stateProps(value: Omit<CreativeRuntimeControlState,"digest">): Readonly<Record<string,JsonValue>> { return Object.freeze({ [C.policyDigest]:value.policyDigest,[C.mode]:value.mode,[C.reason]:value.reason,[C.changedAt]:value.changedAt,[C.logicalRevision]:value.revision,[C.digest]:stateDigest(value) }); }
function eventProps(value: Omit<CreativeRuntimeControlEvent,"digest">): Readonly<Record<string,JsonValue>> { return Object.freeze({ [E.policyDigest]:value.policyDigest,[E.fromMode]:value.fromMode,[E.toMode]:value.toMode,[E.reason]:value.reason,[E.changedAt]:value.changedAt,[E.targetRevision]:value.targetRevision,[E.digest]:eventDigest(value) }); }
function parseState(record: ObjectRecord): CreativeRuntimeControlState { if (record.typeId!==CONTROL_TYPE) throw new CreativeRuntimeControlError("INTEGRITY_FAILURE","control record type mismatch"); const core={policyDigest:digest(stringProp(record,C.policyDigest),"INTEGRITY_FAILURE"),mode:mode(stringProp(record,C.mode),"INTEGRITY_FAILURE"),reason:reason(stringProp(record,C.reason),"INTEGRITY_FAILURE"),changedAt:utc(stringProp(record,C.changedAt),"stored changedAt","INTEGRITY_FAILURE"),revision:revision(numberProp(record,C.logicalRevision),"stored revision","INTEGRITY_FAILURE")}; if(core.revision!==record.revision) throw new CreativeRuntimeControlError("INTEGRITY_FAILURE","control logical revision does not match transaction revision"); const observed=stringProp(record,C.digest); if(observed!==stateDigest(core)) throw new CreativeRuntimeControlError("INTEGRITY_FAILURE","control digest mismatch"); return Object.freeze({...core,digest:observed}); }
function parseEvent(record: ObjectRecord): CreativeRuntimeControlEvent { if(record.typeId!==EVENT_TYPE) throw new CreativeRuntimeControlError("INTEGRITY_FAILURE","control event type mismatch"); const core={policyDigest:digest(stringProp(record,E.policyDigest),"INTEGRITY_FAILURE"),fromMode:mode(stringProp(record,E.fromMode),"INTEGRITY_FAILURE"),toMode:mode(stringProp(record,E.toMode),"INTEGRITY_FAILURE"),reason:reason(stringProp(record,E.reason),"INTEGRITY_FAILURE"),changedAt:utc(stringProp(record,E.changedAt),"stored changedAt","INTEGRITY_FAILURE"),targetRevision:revision(numberProp(record,E.targetRevision),"stored targetRevision","INTEGRITY_FAILURE")}; const observed=stringProp(record,E.digest); if(observed!==eventDigest(core)) throw new CreativeRuntimeControlError("INTEGRITY_FAILURE","control event digest mismatch"); return Object.freeze({...core,digest:observed}); }
function rank(value: CreativeSyncMode): number { return value === "ACTIVE" ? 0 : value === "OBSERVE_ONLY" ? 1 : 2; }
function restrictive(left: CreativeSyncMode, right: CreativeSyncMode): CreativeSyncMode { return rank(left) >= rank(right) ? left : right; }
function conflict(error: unknown): boolean { return error instanceof OntologyTransactionError && error.code === "CONFLICT"; }

export class CreativeRuntimeController {
  readonly schema: ValidatedSchema;
  readonly policyDigest: string;
  readonly configuredMode: CreativeSyncMode;
  constructor(private readonly transactions: OntologyTransactionPort, readonly scope: OntologyScope, policyDigestValue: string, configuredModeValue: CreativeSyncMode, private readonly now: () => number = Date.now) { this.policyDigest=digest(policyDigestValue); this.configuredMode=mode(configuredModeValue); this.schema=schema(scope); }
  private controlId(): string { return ontologyId("cortex-creative-runtime-control-v1",{scope:this.scope}); }
  private eventId(targetRevision:number): string { return ontologyId("cortex-creative-runtime-control-event-v1",{scope:this.scope,targetRevision}); }
  current(): CreativeRuntimeControlState { const raw=this.transactions.getObject(this.scope,this.controlId()); if(!raw){const core={policyDigest:this.policyDigest,mode:this.configuredMode,reason:"configured runtime mode",changedAt:null,revision:0} as const; return Object.freeze({...core,digest:stateDigest(core)});} return parseState(raw); }
  effectiveMode(): CreativeSyncMode { return restrictive(this.current().mode,this.configuredMode); }
  set(input:SetCreativeRuntimeControlInput):CreativeRuntimeControlState { if(!Number.isSafeInteger(input.expectedRevision)||input.expectedRevision<0) throw new CreativeRuntimeControlError("INVALID_INPUT","expectedRevision must be non-negative"); const nextMode=mode(input.mode); if(rank(nextMode)<rank(this.configuredMode)) throw new CreativeRuntimeControlError("POLICY_VIOLATION","runtime cannot weaken configured mode"); const why=reason(input.reason); const changedAt=input.changedAt===undefined?new Date(this.now()).toISOString():utc(input.changedAt,"changedAt","INVALID_INPUT"); const current=this.current(); if(current.revision!==input.expectedRevision) throw new CreativeRuntimeControlError("CONFLICT","runtime control revision changed"); if(current.mode===nextMode&&current.reason===why&&current.policyDigest===this.policyDigest) return current; const nextRevision=current.revision+1; const nextCore={policyDigest:this.policyDigest,mode:nextMode,reason:why,changedAt,revision:nextRevision} as const; const eventCore={policyDigest:this.policyDigest,fromMode:current.mode,toMode:nextMode,reason:why,changedAt,targetRevision:nextRevision} as const; const operations:TransactionOperation[]=[current.revision===0?{kind:"CREATE_OBJECT",record:{id:this.controlId(),typeId:CONTROL_TYPE,scope:this.scope,properties:stateProps(nextCore)}}:{kind:"UPDATE_OBJECT",id:this.controlId(),expectedRevision:current.revision,properties:stateProps(nextCore)},{kind:"CREATE_OBJECT",record:{id:this.eventId(nextRevision),typeId:EVENT_TYPE,scope:this.scope,properties:eventProps(eventCore)}}]; try{this.transactions.transact(this.scope,this.schema,operations);}catch(error){if(conflict(error)) throw new CreativeRuntimeControlError("CONFLICT","runtime control changed concurrently"); if(error instanceof CreativeRuntimeControlError) throw error; throw new CreativeRuntimeControlError("PERSISTENCE_FAILURE",error instanceof Error?error.message:"control persistence failed");} return this.current(); }
  history(limit=32):readonly CreativeRuntimeControlEvent[]{ if(!Number.isSafeInteger(limit)||limit<1||limit>256) throw new CreativeRuntimeControlError("INVALID_INPUT","history limit must be 1..256"); const current=this.current(); if(current.revision===0) return Object.freeze([]); const events:CreativeRuntimeControlEvent[]=[]; for(let value=Math.max(1,current.revision-limit+1);value<=current.revision;value+=1){const raw=this.transactions.getObject(this.scope,this.eventId(value)); if(!raw) throw new CreativeRuntimeControlError("INTEGRITY_FAILURE",`runtime control history event ${value} is missing`); const event=parseEvent(raw); if(event.targetRevision!==value) throw new CreativeRuntimeControlError("INTEGRITY_FAILURE",`runtime control history event ${value} identity mismatch`); events.push(event);} return Object.freeze(events); }
}
