import type { NexusTheme } from "@nexus/core/foundation/theme";

export const probeTheme: NexusTheme = {
  "space.xs": "0.5rem",
  "space.sm": "1rem",
  "space.md": "1.5rem",
  "space.lg": "3rem",
  "space.xl": "6rem",
  "container.sm": "36rem",
  "container.md": "52rem",
  "container.lg": "72rem",
  "container.xl": "92rem",
  "focus.ring": "#166534",
  "focus.offset": "3px",
  "motion.duration.instant": "0ms",
  "motion.duration.fast": "160ms",
  "motion.duration.base": "360ms",
  "motion.duration.slow": "760ms",
  "motion.easing.standard": "ease",
  "motion.easing.decelerate": "cubic-bezier(0.16,1,0.3,1)",
  "motion.easing.accelerate": "cubic-bezier(0.7,0,0.84,0)",
  "motion.easing.linear": "linear",
  "surface.base": "#e7e8e2",
  "surface.elevated": "#f4f5ef",
  "surface.inverse": "#111310",
  "surface.overlay": "rgba(17,19,16,.2)",
  "content.primary": "#111310",
  "content.secondary": "#4d5349",
  "content.inverse": "#f4f5ef",
  "content.disabled": "#93998f",
  "accent.default": "#166534",
  "accent.emphasis": "#0f4c27",
  "accent.muted": "#9dc8aa",
  "border.subtle": "rgba(17,19,16,.28)",
  "border.strong": "#111310",
  "radius.sm": "0px",
  "radius.md": "0px",
  "radius.lg": "0px",
  "radius.full": "0px",
};
