import { createHash } from "node:crypto";
import { canonicalJson, ontologyId, validateSchema, type OntologyScope, type SchemaVersion, type ValidatedSchema } from "@nexus/ontology";
import { OntologyTransactionError, type JsonValue, type ObjectRecord, type OntologyTransactionPort, type TransactionOperation } from "@nexus/ontology/transaction";

export type AdContextRuntimeMode = "ACTIVE" | "OBSERVE_ONLY" | "KILLED";
export type AdContextObservedChannel = "DIRECT_OR_UNKNOWN" | "PAID_SEARCH" | "PAID_SOCIAL";
export type AdContextObservedReason = "KILL_SWITCH" | "NO_AD_CONTEXT" | "EXACT_RULE_MATCH" | "PAID_SEARCH_SIGNAL" | "PAID_SOCIAL_SIGNAL" | "OBSERVE_ONLY_MATCH" | "MALFORMED_CONTEXT" | "AMBIGUOUS_CONTEXT";

const CONTROL_TYPE = "cortex.ad_context_runtime_control";
const EVENT_TYPE = "cortex.ad_context_runtime_control_event";
const METRICS_TYPE = "cortex.ad_context_daily_metrics";
const IDENTIFIER = /^[A-Za-z0-9](?:[A-Za-z0-9._:-]{0,127})$/u;
const MODES = new Set<AdContextRuntimeMode>(["ACTIVE", "OBSERVE_ONLY", "KILLED"]);
const CHANNELS = new Set<AdContextObservedChannel>(["DIRECT_OR_UNKNOWN", "PAID_SEARCH", "PAID_SOCIAL"]);
const REASONS = new Set<AdContextObservedReason>(["KILL_SWITCH", "NO_AD_CONTEXT", "EXACT_RULE_MATCH", "PAID_SEARCH_SIGNAL", "PAID_SOCIAL_SIGNAL", "OBSERVE_ONLY_MATCH", "MALFORMED_CONTEXT", "AMBIGUOUS_CONTEXT"]);

const C = Object.freeze({ key: "cortex.ad_context.control.key", policyId: "cortex.ad_context.control.policy_id", mode: "cortex.ad_context.control.mode", reason: "cortex.ad_context.control.reason", changedAt: "cortex.ad_context.control.changed_at", logicalRevision: "cortex.ad_context.control.logical_revision", digest: "cortex.ad_context.control.digest" });
const E = Object.freeze({ key: "cortex.ad_context.event.key", policyId: "cortex.ad_context.event.policy_id", fromMode: "cortex.ad_context.event.from_mode", toMode: "cortex.ad_context.event.to_mode", reason: "cortex.ad_context.event.reason", changedAt: "cortex.ad_context.event.changed_at", targetRevision: "cortex.ad_context.event.target_revision", digest: "cortex.ad_context.event.digest" });
const M = Object.freeze({ key: "cortex.ad_context.metrics.key", day: "cortex.ad_context.metrics.day", counters: "cortex.ad_context.metrics.counters", updatedAt: "cortex.ad_context.metrics.updated_at", digest: "cortex.ad_context.metrics.digest" });

export interface AdContextRuntimeControlState { readonly key: string; readonly policyId: string; readonly mode: AdContextRuntimeMode; readonly reason: string; readonly changedAt: string | null; readonly revision: number; readonly digest: string }
export interface AdContextRuntimeControlEvent { readonly key: string; readonly policyId: string; readonly fromMode: AdContextRuntimeMode; readonly toMode: AdContextRuntimeMode; readonly reason: string; readonly changedAt: string; readonly targetRevision: number; readonly digest: string }
export interface SetAdContextRuntimeControlInput { readonly expectedRevision: number; readonly mode: AdContextRuntimeMode; readonly reason: string; readonly changedAt?: string }
export interface AdContextDecisionObservation { readonly policyId: string; readonly mode: AdContextRuntimeMode; readonly channel: AdContextObservedChannel; readonly reason: AdContextObservedReason; readonly applied: boolean; readonly observedAt: string }
export interface AdContextDailyMetrics { readonly day: string; readonly counters: Readonly<Record<string, number>>; readonly updatedAt: string; readonly digest: string; readonly revision: number }

export class AdContextRuntimeControlError extends Error {
  constructor(readonly code: "INVALID_INPUT" | "CONFLICT" | "INTEGRITY_FAILURE" | "PERSISTENCE_FAILURE" | "POLICY_VIOLATION", message: string) { super(message); this.name = "AdContextRuntimeControlError"; }
}

function hash(namespace: string, value: unknown): string { return `sha256:${createHash("sha256").update(`${namespace}\n${canonicalJson(value)}`, "utf8").digest("hex")}`; }
function id(value: string, field: string): string { if (typeof value !== "string" || !IDENTIFIER.test(value.trim())) throw new AdContextRuntimeControlError("INVALID_INPUT", `${field} is malformed`); return value.trim(); }
function mode(value: unknown, code: "INVALID_INPUT" | "INTEGRITY_FAILURE" = "INVALID_INPUT"): AdContextRuntimeMode { if (typeof value !== "string" || !MODES.has(value as AdContextRuntimeMode)) throw new AdContextRuntimeControlError(code, "ad-context mode is invalid"); return value as AdContextRuntimeMode; }
function reason(value: string, code: "INVALID_INPUT" | "INTEGRITY_FAILURE" = "INVALID_INPUT"): string { if (typeof value !== "string") throw new AdContextRuntimeControlError(code, "reason must be a string"); const normalized = value.normalize("NFKC").trim(); if (normalized.length < 3 || normalized.length > 256) throw new AdContextRuntimeControlError(code, "reason must contain 3..256 characters"); for (const ch of normalized) { const point = ch.codePointAt(0) ?? 0; if (point < 0x20 || point === 0x7f) throw new AdContextRuntimeControlError(code, "reason contains a control character"); } return normalized; }
function utc(value: string, field: string, code: "INVALID_INPUT" | "INTEGRITY_FAILURE" = "INVALID_INPUT"): string { const parsed = new Date(value); if (!Number.isFinite(parsed.getTime()) || parsed.toISOString() !== value) throw new AdContextRuntimeControlError(code, `${field} must be canonical UTC`); return value; }
function property(idValue: string, name: string, valueKind: "STRING" | "NUMBER" | "JSON" | "DATETIME", immutable = false) { return { id: idValue, name, valueKind, cardinality: "REQUIRED", unique: false, immutable } as const; }
function schema(scope: OntologyScope): ValidatedSchema { const value: SchemaVersion = { version: "cortex-ad-context-control-v1", scope, properties: [property(C.key,"AdContextControlKey","STRING",true),property(C.policyId,"AdContextControlPolicyId","STRING"),property(C.mode,"AdContextControlMode","STRING"),property(C.reason,"AdContextControlReason","STRING"),property(C.changedAt,"AdContextControlChangedAt","DATETIME"),property(C.logicalRevision,"AdContextControlRevision","NUMBER"),property(C.digest,"AdContextControlDigest","STRING"),property(E.key,"AdContextEventKey","STRING",true),property(E.policyId,"AdContextEventPolicyId","STRING",true),property(E.fromMode,"AdContextEventFromMode","STRING",true),property(E.toMode,"AdContextEventToMode","STRING",true),property(E.reason,"AdContextEventReason","STRING",true),property(E.changedAt,"AdContextEventChangedAt","DATETIME",true),property(E.targetRevision,"AdContextEventRevision","NUMBER",true),property(E.digest,"AdContextEventDigest","STRING",true),property(M.key,"AdContextMetricsKey","STRING",true),property(M.day,"AdContextMetricsDay","STRING",true),property(M.counters,"AdContextMetricsCounters","JSON"),property(M.updatedAt,"AdContextMetricsUpdatedAt","DATETIME"),property(M.digest,"AdContextMetricsDigest","STRING")], interfaces: [], objects: [{ id: CONTROL_TYPE, name: "CortexAdContextRuntimeControl", propertyIds: Object.values(C), interfaceIds: [] }, { id: EVENT_TYPE, name: "CortexAdContextRuntimeControlEvent", propertyIds: Object.values(E), interfaceIds: [] }, { id: METRICS_TYPE, name: "CortexAdContextDailyMetrics", propertyIds: Object.values(M), interfaceIds: [] }], relationships: [], actions: [], functions: [], events: [] }; return validateSchema(value); }
function sp(record: ObjectRecord, key: string): string { const value = record.properties[key]; if (typeof value !== "string") throw new AdContextRuntimeControlError("INTEGRITY_FAILURE", `record ${record.id} has invalid ${key}`); return value; }
function np(record: ObjectRecord, key: string): number { const value = record.properties[key]; if (typeof value !== "number" || !Number.isSafeInteger(value)) throw new AdContextRuntimeControlError("INTEGRITY_FAILURE", `record ${record.id} has invalid ${key}`); return value; }
function controlDigest(value: Omit<AdContextRuntimeControlState,"digest">): string { return hash("cortex-ad-context-control-v1", value); }
function eventDigest(value: Omit<AdContextRuntimeControlEvent,"digest">): string { return hash("cortex-ad-context-control-event-v1", value); }
function rank(value: AdContextRuntimeMode): number { return value === "ACTIVE" ? 0 : value === "OBSERVE_ONLY" ? 1 : 2; }
function restrictive(left: AdContextRuntimeMode, right: AdContextRuntimeMode): AdContextRuntimeMode { return rank(left) >= rank(right) ? left : right; }
function conflict(error: unknown): boolean { return error instanceof OntologyTransactionError && error.code === "CONFLICT"; }

export class AdContextRuntimeController {
  readonly schema: ValidatedSchema;
  readonly key: string;
  readonly policyId: string;
  readonly configuredMode: AdContextRuntimeMode;
  constructor(private readonly transactions: OntologyTransactionPort, readonly scope: OntologyScope, keyValue: string, policyIdValue: string, configuredModeValue: AdContextRuntimeMode, private readonly now: () => number = Date.now) { this.key = id(keyValue,"key"); this.policyId = id(policyIdValue,"policyId"); this.configuredMode = mode(configuredModeValue); this.schema = schema(scope); }
  private controlId(): string { return ontologyId("cortex-ad-context-control-v1", { scope: this.scope, key: this.key }); }
  private eventId(revision: number): string { return ontologyId("cortex-ad-context-control-event-v1", { scope: this.scope, key: this.key, revision }); }
  private metricsId(day: string): string { return ontologyId("cortex-ad-context-metrics-v1", { scope: this.scope, key: this.key, day }); }
  current(): AdContextRuntimeControlState { const raw = this.transactions.getObject(this.scope, this.controlId()); if (!raw) { const core = { key: this.key, policyId: this.policyId, mode: this.configuredMode, reason: "configured runtime mode", changedAt: null, revision: 0 } as const; return Object.freeze({ ...core, digest: controlDigest(core) }); } if (raw.typeId !== CONTROL_TYPE) throw new AdContextRuntimeControlError("INTEGRITY_FAILURE","control record type mismatch"); const core = { key: id(sp(raw,C.key),"stored key"), policyId: id(sp(raw,C.policyId),"stored policyId"), mode: mode(sp(raw,C.mode),"INTEGRITY_FAILURE"), reason: reason(sp(raw,C.reason),"INTEGRITY_FAILURE"), changedAt: utc(sp(raw,C.changedAt),"stored changedAt","INTEGRITY_FAILURE"), revision: np(raw,C.logicalRevision) }; if (core.key !== this.key || core.policyId !== this.policyId || core.revision !== raw.revision) throw new AdContextRuntimeControlError("INTEGRITY_FAILURE","control identity/revision mismatch"); const digest = sp(raw,C.digest); if (digest !== controlDigest(core)) throw new AdContextRuntimeControlError("INTEGRITY_FAILURE","control digest mismatch"); return Object.freeze({ ...core, digest }); }
  effectiveMode(): AdContextRuntimeMode { return restrictive(this.current().mode, this.configuredMode); }
  set(input: SetAdContextRuntimeControlInput): AdContextRuntimeControlState { if (!Number.isSafeInteger(input.expectedRevision) || input.expectedRevision < 0) throw new AdContextRuntimeControlError("INVALID_INPUT","expectedRevision must be non-negative"); const nextMode = mode(input.mode); if (rank(nextMode) < rank(this.configuredMode)) throw new AdContextRuntimeControlError("POLICY_VIOLATION","runtime cannot weaken configured mode"); const why = reason(input.reason); const changedAt = input.changedAt === undefined ? new Date(this.now()).toISOString() : utc(input.changedAt,"changedAt"); const current = this.current(); if (current.revision !== input.expectedRevision) throw new AdContextRuntimeControlError("CONFLICT","runtime control revision changed"); if (current.mode === nextMode && current.reason === why && current.policyId === this.policyId) return current; const revision = current.revision + 1; const core = { key: this.key, policyId: this.policyId, mode: nextMode, reason: why, changedAt, revision } as const; const event = { key: this.key, policyId: this.policyId, fromMode: current.mode, toMode: nextMode, reason: why, changedAt, targetRevision: revision } as const; const controlProps = Object.freeze({ [C.key]: core.key,[C.policyId]:core.policyId,[C.mode]:core.mode,[C.reason]:core.reason,[C.changedAt]:core.changedAt,[C.logicalRevision]:core.revision,[C.digest]:controlDigest(core) }); const eventProps = Object.freeze({ [E.key]:event.key,[E.policyId]:event.policyId,[E.fromMode]:event.fromMode,[E.toMode]:event.toMode,[E.reason]:event.reason,[E.changedAt]:event.changedAt,[E.targetRevision]:event.targetRevision,[E.digest]:eventDigest(event) }); const operations: TransactionOperation[] = [current.revision === 0 ? { kind:"CREATE_OBJECT",record:{ id:this.controlId(),typeId:CONTROL_TYPE,scope:this.scope,properties:controlProps } } : { kind:"UPDATE_OBJECT",id:this.controlId(),expectedRevision:current.revision,properties:controlProps }, { kind:"CREATE_OBJECT",record:{ id:this.eventId(revision),typeId:EVENT_TYPE,scope:this.scope,properties:eventProps } }]; try { this.transactions.transact(this.scope,this.schema,operations); } catch (error) { if (conflict(error)) throw new AdContextRuntimeControlError("CONFLICT","runtime control changed concurrently"); throw new AdContextRuntimeControlError("PERSISTENCE_FAILURE",error instanceof Error ? error.message : "control persistence failed"); } return this.current(); }
  history(limit = 32): readonly AdContextRuntimeControlEvent[] { if (!Number.isSafeInteger(limit) || limit < 1 || limit > 256) throw new AdContextRuntimeControlError("INVALID_INPUT","history limit must be 1..256"); const current = this.current(); const out: AdContextRuntimeControlEvent[] = []; for (let revision = Math.max(1,current.revision-limit+1); revision <= current.revision; revision += 1) { const raw = this.transactions.getObject(this.scope,this.eventId(revision)); if (!raw || raw.typeId !== EVENT_TYPE) throw new AdContextRuntimeControlError("INTEGRITY_FAILURE",`control event ${revision} missing`); const core = { key:id(sp(raw,E.key),"stored key"),policyId:id(sp(raw,E.policyId),"stored policyId"),fromMode:mode(sp(raw,E.fromMode),"INTEGRITY_FAILURE"),toMode:mode(sp(raw,E.toMode),"INTEGRITY_FAILURE"),reason:reason(sp(raw,E.reason),"INTEGRITY_FAILURE"),changedAt:utc(sp(raw,E.changedAt),"stored changedAt","INTEGRITY_FAILURE"),targetRevision:np(raw,E.targetRevision) }; const digest=sp(raw,E.digest); if (core.key!==this.key || core.policyId!==this.policyId || core.targetRevision!==revision || digest!==eventDigest(core)) throw new AdContextRuntimeControlError("INTEGRITY_FAILURE",`control event ${revision} invalid`); out.push(Object.freeze({ ...core,digest })); } return Object.freeze(out); }
  observe(input: AdContextDecisionObservation): AdContextDailyMetrics { this.current(); const observedPolicyId=id(input.policyId,"observation.policyId"); if (observedPolicyId!==this.policyId) throw new AdContextRuntimeControlError("POLICY_VIOLATION","observation policy does not match controller policy"); const observedAt=utc(input.observedAt,"observation.observedAt"); if (!MODES.has(input.mode) || !CHANNELS.has(input.channel) || !REASONS.has(input.reason) || typeof input.applied !== "boolean") throw new AdContextRuntimeControlError("INVALID_INPUT","observation enum is invalid"); const day=observedAt.slice(0,10); const metricKey=`${input.mode}|${input.channel}|${input.reason}|${input.applied ? "1":"0"}`; for (let attempt=0; attempt<5; attempt+=1) { const idValue=this.metricsId(day); const raw=this.transactions.getObject(this.scope,idValue); let counters: Record<string,number>={}; let revision=0; if (raw) { if (raw.typeId!==METRICS_TYPE || sp(raw,M.key)!==this.key || sp(raw,M.day)!==day) throw new AdContextRuntimeControlError("INTEGRITY_FAILURE","metrics identity mismatch"); const stored=raw.properties[M.counters]; if (!stored || typeof stored!=="object" || Array.isArray(stored)) throw new AdContextRuntimeControlError("INTEGRITY_FAILURE","metrics counters invalid"); counters={ ...(stored as Record<string,number>) }; for (const value of Object.values(counters)) if (!Number.isSafeInteger(value) || value<0) throw new AdContextRuntimeControlError("INTEGRITY_FAILURE","metrics counter invalid"); revision=raw.revision; }
      counters[metricKey]=(counters[metricKey] ?? 0)+1; const updatedAt=new Date(this.now()).toISOString(); const core={ day,counters:Object.freeze(counters),updatedAt }; const digest=hash("cortex-ad-context-daily-metrics-v1",{ key:this.key,...core }); const props=Object.freeze({ [M.key]:this.key,[M.day]:day,[M.counters]:core.counters as unknown as JsonValue,[M.updatedAt]:updatedAt,[M.digest]:digest }); try { this.transactions.transact(this.scope,this.schema,[revision===0?{kind:"CREATE_OBJECT",record:{id:idValue,typeId:METRICS_TYPE,scope:this.scope,properties:props}}:{kind:"UPDATE_OBJECT",id:idValue,expectedRevision:revision,properties:props}]); const stored=this.transactions.getObject(this.scope,idValue)!; return Object.freeze({ day,counters:Object.freeze({ ...counters }),updatedAt,digest,revision:stored.revision }); } catch (error) { if (conflict(error)) continue; throw new AdContextRuntimeControlError("PERSISTENCE_FAILURE",error instanceof Error ? error.message : "metrics persistence failed"); } }
    throw new AdContextRuntimeControlError("CONFLICT","metrics remained contended"); }
}
