from __future__ import annotations

from typing import Any, Dict

HTML_ROWS: Dict[str, Dict[str, Any]] = {
    "M851": {"module_id": "M851", "chunk_boundary_count": 10, "valid_chunk_boundary_count": 10},
    "M852": {"module_id": "M852", "utf8_boundary_count": 10, "valid_utf8_boundary_count": 10},
    "M853": {"module_id": "M853", "head_order_edge_count": 10, "respected_head_order_edge_count": 10},
    "M854": {"module_id": "M854", "canonical_tag_count": 1},
    "M855": {"module_id": "M855", "viewport_tag_count": 1},
    "M856": {"module_id": "M856", "charset_offset_bytes": 100, "max_charset_offset_bytes": 1024},
    "M857": {"module_id": "M857", "opened_tag_count": 10, "closed_tag_count": 10},
    "M858": {"module_id": "M858", "closing_tag_count": 10, "orphan_closing_tag_count": 0},
    "M859": {"module_id": "M859", "attribute_count": 10, "quoted_attribute_count": 10},
    "M860": {"module_id": "M860", "escapable_token_count": 10, "escaped_token_count": 10},
    "M861": {"module_id": "M861", "jsonld_block_count": 3, "valid_jsonld_block_count": 3},
    "M862": {"module_id": "M862", "required_jsonld_contexts": ["schema-context"], "observed_jsonld_contexts": ["schema-context"]},
    "M863": {"module_id": "M863", "preload_count": 4, "consumed_preload_count": 4},
    "M864": {"module_id": "M864", "stylesheet_count": 4, "nonblocking_stylesheet_count": 4},
    "M865": {"module_id": "M865", "script_dependency_edge_count": 5, "respected_script_dependency_edge_count": 5},
    "M866": {"module_id": "M866", "responsive_image_count": 5, "srcset_image_count": 5},
    "M867": {"module_id": "M867", "picture_source_count": 5, "media_scoped_source_count": 5},
    "M868": {"module_id": "M868", "lazy_image_count": 5, "noscript_fallback_count": 5},
    "M869": {"module_id": "M869", "interactive_element_count": 5, "aria_named_element_count": 5},
    "M870": {"module_id": "M870", "form_control_count": 5, "bound_label_count": 5},
    "M871": {"module_id": "M871", "heading_transition_count": 5, "valid_heading_transition_count": 5},
    "M872": {"module_id": "M872", "main_landmark_count": 1},
    "M873": {"module_id": "M873", "id_attribute_count": 10, "duplicate_id_count": 0},
    "M874": {"module_id": "M874", "observed_dom_depth": 10, "allowed_dom_depth": 12},
    "M875": {"module_id": "M875", "source_text_bytes": 1000, "visible_text_bytes": 1000},
    "M876": {"module_id": "M876", "expected_terminal_tokens": ["body-close", "html-close"], "observed_terminal_tokens": ["body-close", "html-close"]},
    "M877": {"module_id": "M877", "expected_content_bytes": 1000, "observed_content_bytes": 1000},
    "M878": {"module_id": "M878", "expected_document_digest": "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "observed_document_digest": "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"},
    "M879": {"module_id": "M879", "declared_canonical_href": "/path", "resolved_canonical_href": "/path"},
    "M880": {"module_id": "M880", "hreflang_link_count": 4, "reciprocal_hreflang_link_count": 4},
    "M881": {"module_id": "M881", "title_tag_count": 1},
    "M882": {"module_id": "M882", "description_meta_count": 1},
    "M883": {"module_id": "M883", "robots_meta_count": 1},
    "M884": {"module_id": "M884", "base_href_count": 0},
    "M885": {"module_id": "M885", "form_count": 3, "resolved_form_action_count": 3},
    "M886": {"module_id": "M886", "informative_image_count": 5, "descriptive_alt_count": 5},
    "M887": {"module_id": "M887", "data_table_count": 3, "headered_table_count": 3},
    "M888": {"module_id": "M888", "list_item_count": 8, "contained_list_item_count": 8},
    "M889": {"module_id": "M889", "details_element_count": 2, "summary_element_count": 2},
    "M890": {"module_id": "M890", "template_fragment_count": 2, "closed_template_fragment_count": 2},
    "M891": {"module_id": "M891", "informative_svg_count": 2, "titled_svg_count": 2},
    "M892": {"module_id": "M892", "iframe_count": 2, "titled_iframe_count": 2},
    "M893": {"module_id": "M893", "expected_lang": "es-MX", "actual_lang": "es-MX"},
    "M894": {"module_id": "M894", "expected_dir": "ltr", "actual_dir": "ltr"},
    "M895": {"module_id": "M895", "resource_hint_count": 3, "valid_origin_hint_count": 3},
    "M896": {"module_id": "M896", "modulepreload_count": 3, "consumed_modulepreload_count": 3},
    "M897": {"module_id": "M897", "scripted_content_tokens": ["a", "b"], "noscript_content_tokens": ["a", "b"]},
    "M898": {"module_id": "M898", "comment_count": 3, "closed_comment_count": 3},
    "M899": {"module_id": "M899", "custom_element_count": 3, "valid_custom_element_name_count": 3},
    "M900": {"module_id": "M900", "expected_terminal_token": "html-close", "observed_terminal_token": "html-close"},
}


def html_payload() -> Dict[str, Any]:
    return {"html_stream_records": [dict(HTML_ROWS[module_id]) for module_id in HTML_ROWS]}
