import {createHash,sign,verify,createPrivateKey,createPublicKey} from 'node:crypto';
import {object,array,number,integer,id,unique} from './shared.mjs';
import {vector,matrix,dot,solveLinear,cholesky} from './numerics.mjs';
import {canon} from './finite-tools.mjs';
import {analyzeNetworkErgodicity} from './network-ergodicity.mjs';
import {inferLinearCRF} from './linear-crf.mjs';
const sum=a=>a.reduce((s,v)=>s+v,0),finite=(x,k)=>number(x,k,-1e12,1e12),hash=x=>createHash('sha256').update(canon(x)).digest('hex');
function simplex(p,name,n){const v=vector(p,name,n,n);if(v.some(x=>x<0||x>1)||Math.abs(sum(v)-1)>1e-9)throw new TypeError(`${name} probability sum`);return v;}

// #90: Fisher metric and natural gradient for a supplied logistic statistical manifold.
export function logisticParameterGeometry(input){object(input,'parameter geometry',['features','parameters','gradient','ridge'],['features','parameters']);const features=array(input.features,'features',1,4096).map((r,i)=>vector(r,`feature${i}`,1,16)),d=features[0].length,theta=vector(input.parameters,'parameters',d,d);if(features.some(r=>r.length!==d))throw new TypeError('ragged features');const p=features.map(x=>1/(1+Math.exp(-dot(theta,x)))),fisher=theta.map((_,i)=>theta.map((_,j)=>sum(features.map((x,k)=>p[k]*(1-p[k])*x[i]*x[j]))/features.length)),ridge=number(input.ridge??1e-8,'ridge',1e-12,1);const regular=fisher.map((r,i)=>r.map((v,j)=>v+(i===j?ridge:0)));cholesky(regular);const result={domain:'LOGISTIC_STATISTICAL_PARAMETER_FISHER_GEOMETRY',probabilities:p,fisher,regularizedFisher:regular};if(input.gradient!==undefined){const gradient=vector(input.gradient,'gradient',d,d);result.naturalGradient=solveLinear(regular,gradient);}return result;}

// #91: Ulam finite partition of nonlinear logistic dynamics (empirical ergodicity only).
export function analyzeNonlinearErgodicity(input){object(input,'Ulam logistic',['r','bins','samplesPerBin','steps'],['r','bins','samplesPerBin']);const r=number(input.r,'r',0,4),bins=integer(input.bins,'bins',2,128),samples=integer(input.samplesPerBin,'samplesPerBin',1,4096),steps=integer(input.steps??1000,'steps',1,50000);if(bins*bins*steps>2_000_000)throw new RangeError('Ulam computation budget exceeded');const T=Array.from({length:bins},(_,i)=>{const counts=Array(bins).fill(0);for(let j=0;j<samples;j++){const x=(i+(j+.5)/samples)/bins,v=r*x*(1-x),to=Math.min(bins-1,Math.floor(v*bins));counts[to]++;}return counts.map(v=>v/samples);});let mass=Array(bins).fill(1/bins);for(let t=0;t<steps;t++)mass=Array.from({length:bins},(_,j)=>sum(T.map((row,i)=>mass[i]*row[j])));const graph=analyzeNetworkErgodicity({transition:T,steps:Math.min(steps,5000)});return {domain:'ULAM_FINITE_PARTITION_NONLINEAR_ERGODICITY',stationaryEstimate:mass,partitionTransition:T,ergodicPartition:graph.ergodic,recurrentClasses:graph.recurrentClasses,warning:'finite Ulam approximation cannot prove ergodicity of a continuous chaotic system'};}

// #92: mean-square stochastic Lyapunov for random diagonal discrete systems.
export function stochasticLyapunov(input){object(input,'stochastic Lyapunov',['matrices','probabilities','q'],['matrices','probabilities']);const mats=array(input.matrices,'matrices',1,128),d=array(mats[0],'matrix',1,16).length;const A=mats.map((M,k)=>matrix(M,`A${k}`,d,d)),p=simplex(input.probabilities,'probabilities',A.length),q=input.q===undefined?Array(d).fill(1):vector(input.q,'q',d,d);if(q.some(v=>v<=0))throw new TypeError('positive Lyapunov target required');if(A.some(M=>M.some((row,i)=>row.some((v,j)=>i!==j&&Math.abs(v)>1e-12))))throw new TypeError('diagonal matrices only');const ratios=Array.from({length:d},(_,j)=>sum(A.map((M,k)=>p[k]*M[j][j]**2))),stable=ratios.every(r=>r<1);return {domain:'RANDOM_DIAGONAL_MEAN_SQUARE_LYAPUNOV',meanSquareRates:ratios,meanSquareStable:stable,lyapunovDiagonal:stable?ratios.map((r,i)=>q[i]/(1-r)):null,note:'exact second moments for supplied random diagonal matrices; not nonlinear stochastic stability'};}

// #93: verifier of authenticated, single-term Raft vote and append-only log evidence.
export function verifySignedRaftTranscript(input){object(input,'Raft transcript',['replicas','term','leader','votes','entries','commitIndex','previousHash'],['replicas','term','leader','votes','entries','commitIndex']);const replicas=array(input.replicas,'replicas',3,31).map(r=>{object(r,'replica',['id','publicKey']);id(r.id,'replica id');return r;}),ids=unique(replicas.map(r=>r.id),'replicas'),term=integer(input.term,'term',1,Number.MAX_SAFE_INTEGER),leader=id(input.leader,'leader'),quorum=Math.floor(ids.length/2)+1;if(!ids.includes(leader))throw new TypeError('leader unknown');const keys=new Map(replicas.map(r=>[r.id,r.publicKey]));if(new Set(replicas.map(r=>createPublicKey(r.publicKey).export({format:'der',type:'spki'}).toString('hex'))).size!==replicas.length)throw new TypeError('replicas must have distinct authenticated public keys');const votes=array(input.votes,'votes',0,256);const signedVoters=new Set(),errors=[];for(const v of votes){object(v,'vote',['voter','candidate','term','signature']);if(!keys.has(v.voter)||!keys.has(v.candidate)||v.term!==term||v.candidate!==leader||signedVoters.has(v.voter)){errors.push('invalid or duplicate vote');continue;}const msg={kind:'RAFT_VOTE_V1',term,voter:v.voter,candidate:v.candidate};let ok=false;try{ok=verify(null,Buffer.from(canon(msg)),createPublicKey(keys.get(v.voter)),Buffer.from(v.signature,'base64'));}catch{}if(!ok){errors.push('invalid vote signature');continue;}signedVoters.add(v.voter);}let previous=input.previousHash??'GENESIS',lastTerm=0,lastIndex=0;const entries=array(input.entries,'entries',0,1024);for(const e of entries){object(e,'log entry',['index','term','payload','previousHash','signature']);if(e.index!==lastIndex+1||e.term>term||e.term<lastTerm||e.previousHash!==previous){errors.push('log index, term or previous hash mismatch');break;}const data={kind:'RAFT_LOG_V1',index:e.index,term:e.term,payload:e.payload,previousHash:e.previousHash};let ok=false;try{ok=verify(null,Buffer.from(canon(data)),createPublicKey(keys.get(leader)),Buffer.from(e.signature,'base64'));}catch{}if(!ok){errors.push('log signature invalid');break;}previous=hash(data);lastTerm=e.term;lastIndex=e.index;}const commitIndex=integer(input.commitIndex,'commitIndex',0,1024);if(commitIndex>lastIndex)errors.push('commit index exceeds validated log');if(signedVoters.size<quorum)errors.push('election lacks quorum');return {domain:'AUTHENTICATED_LOCAL_RAFT_TRANSCRIPT_VALIDATION',valid:errors.length===0,errors,quorum,verifiedVotes:signedVoters.size,verifiedEntries:lastIndex,finalLogHash:previous,limitations:'offline transcript only; no distributed Raft state machine, network or crash recovery'};}

// #94: finite categorical Fisher contraction under arbitrary stochastic channels (Chentsov DPI).
export function chentsovFisherContraction(input){object(input,'Chentsov',['p','tangent','channel'],['p','tangent','channel']);const p=vector(input.p,'p',2,128),n=p.length;if(p.some(v=>v<=0)||Math.abs(sum(p)-1)>1e-9)throw new TypeError('strictly positive simplex');const v=vector(input.tangent,'tangent',n,n);if(Math.abs(sum(v))>1e-9)throw new TypeError('tangent must sum to zero');const channel=array(input.channel,'channel',n,n).map((row,i)=>simplex(row,`channel${i}`,row.length)),m=channel[0].length;if(channel.some(row=>row.length!==m))throw new TypeError('channel dimension');const q=Array.from({length:m},(_,j)=>sum(p.map((x,i)=>x*channel[i][j]))),w=Array.from({length:m},(_,j)=>sum(v.map((x,i)=>x*channel[i][j]))),before=sum(p.map((x,i)=>v[i]**2/x)),after=sum(q.map((x,j)=>x===0?0:w[j]**2/x));return {domain:'CHENTSOV_FISHER_MONOTONICITY_FINITE_CHANNEL',fisherBefore:before,fisherAfter:after,contractive:after<=before+1e-9,mappedDistribution:q,mappedTangent:w};}

// #96: scalar square-root Kalman from algebraic factor update (no covariance subtraction).
export function scalarCholeskyKalman(input){object(input,'scalar sqrt Kalman',['F','H','Q','R','initialMean','initialSqrtVariance','observations'],['F','H','Q','R','initialMean','initialSqrtVariance','observations']);const F=finite(input.F,'F'),H=finite(input.H,'H'),Q=number(input.Q,'Q',0,1e9),R=number(input.R,'R',1e-12,1e9),observations=array(input.observations,'observations',1,10000),history=[];let mu=finite(input.initialMean,'initialMean'),sqrt=number(input.initialSqrtVariance,'initialSqrtVariance',1e-12,1e9);for(const raw of observations){mu=F*mu;sqrt=Math.hypot(F*sqrt,Math.sqrt(Q));let gain=0,innovation=null;if(raw!==null){const y=finite(raw,'observation'),s=Math.hypot(H*sqrt,Math.sqrt(R));gain=sqrt**2*H/s**2;innovation=y-H*mu;mu+=gain*innovation;sqrt=sqrt*Math.sqrt(R)/s;}history.push({mean:mu,sqrtVariance:sqrt,innovation,gain});}return {domain:'SCALAR_CHOLESKY_SQUARE_ROOT_KALMAN',history,finalMean:mu,finalSqrtVariance:sqrt};}

// #97: multi-moment entropy projection via damped Newton, with feasibility/convergence disclosed.
export function multiMomentVariationalInference(input){object(input,'multi moment VI',['prior','features','targets','iterations','tolerance'],['prior','features','targets']);const prior=vector(input.prior,'prior',2,128),n=prior.length;if(prior.some(v=>v<=0)||Math.abs(sum(prior)-1)>1e-9)throw new TypeError('positive prior simplex');const f=array(input.features,'features',n,n).map((r,i)=>vector(r,`features${i}`,1,4)),k=f[0].length;if(f.some(r=>r.length!==k))throw new TypeError('ragged features');const target=vector(input.targets,'targets',k,k),iterations=integer(input.iterations??200,'iterations',1,2000),tol=number(input.tolerance??1e-9,'tolerance',1e-13,.01);let lambda=Array(k).fill(0),out,used=0;const evaluate=L=>{const logits=prior.map((p,i)=>Math.log(p)+dot(f[i],L)),mx=Math.max(...logits),v=logits.map(x=>Math.exp(x-mx)),z=sum(v),q=v.map(x=>x/z),mean=Array.from({length:k},(_,j)=>sum(q.map((p,i)=>p*f[i][j])));return {q,mean,error:Math.hypot(...mean.map((v,j)=>v-target[j]))};};for(let iter=0;iter<iterations;iter++){used=iter+1;out=evaluate(lambda);if(out.error<=tol)break;const cov=Array.from({length:k},(_,i)=>Array.from({length:k},(_,j)=>sum(out.q.map((p,s)=>p*(f[s][i]-out.mean[i])*(f[s][j]-out.mean[j])))+(i===j?1e-10:0)));let step;try{step=solveLinear(cov,target.map((v,j)=>v-out.mean[j]));}catch{break;}let rate=1,trial;while(rate>1e-9){trial=evaluate(lambda.map((v,j)=>v+rate*step[j]));if(trial.error<out.error)break;rate*=.5;}if(rate<=1e-9)break;lambda=lambda.map((v,j)=>v+rate*step[j]);out=trial;}out=evaluate(lambda);return {domain:'MULTI_MOMENT_CATEGORICAL_VARIATIONAL_I_PROJECTION',status:out.error<=tol?'CONVERGED':'NOT_CONVERGED',posterior:out.q,moments:out.mean,target,error:out.error,dual:lambda,iterations:used,kl:sum(out.q.map((v,i)=>v*Math.log(v/prior[i]))),note:'constraints supplied, no causal graph inferred'};}

// #98: supercritical Hopf normal form RK4 trajectory and amplitude diagnostics.
export function simulateHopfBifurcation(input){object(input,'Hopf',['mu','omega','initial','dt','steps'],['mu','omega','initial','dt','steps']);const mu=number(input.mu,'mu',-100,100),omega=number(input.omega,'omega',-1000,1000),initial=vector(input.initial,'initial',2,2),dt=number(input.dt,'dt',1e-8,.1),steps=integer(input.steps,'steps',1,100000);let [x,y]=initial;const f=([a,b])=>{const r2=a*a+b*b;return [(mu-r2)*a-omega*b,omega*a+(mu-r2)*b];};const history=[];for(let t=0;t<steps;t++){const v=[x,y],k1=f(v),k2=f(v.map((a,i)=>a+.5*dt*k1[i])),k3=f(v.map((a,i)=>a+.5*dt*k2[i])),k4=f(v.map((a,i)=>a+dt*k3[i]));[x,y]=v.map((a,i)=>a+dt*(k1[i]+2*k2[i]+2*k3[i]+k4[i])/6);if(!Number.isFinite(x+y)||Math.hypot(x,y)>1e20)throw new RangeError('Hopf integration divergent');if(t===0||t===steps-1)history.push({step:t+1,radius:Math.hypot(x,y)});}return {domain:'SUPERCRITICAL_HOPF_NORMAL_FORM_RK4',final:[x,y],radius:Math.hypot(x,y),theoreticalLimitCycleRadius:mu>0?Math.sqrt(mu):null,originStable:mu<0,history};}

// #99: supervised training of global unary biases for a finite linear-chain CRF.
export function trainLinearChainCRF(input){object(input,'CRF training',['sequences','transition','learningRate','steps','l2'],['sequences','transition','learningRate','steps']);const T=array(input.transition,'transition',2,16),k=T.length,transition=matrix(T,'transition',k,k),sequences=array(input.sequences,'sequences',1,512).map((s,i)=>{object(s,`sequence${i}`,['length','labels']);const length=integer(s.length,'length',1,512),labels=array(s.labels,'labels',length,length).map(v=>integer(v,'label',0,k-1));return {length,labels};}),lr=number(input.learningRate,'learningRate',1e-6,1),steps=integer(input.steps,'steps',1,10000),l2=number(input.l2??0,'l2',0,10);let bias=Array(k).fill(0);for(let t=0;t<steps;t++){const gradient=Array(k).fill(0);for(const seq of sequences){const unary=Array.from({length:seq.length},()=>[...bias]),out=inferLinearCRF({unary,transition});for(let s=0;s<seq.length;s++)for(let j=0;j<k;j++)gradient[j]+=(seq.labels[s]===j?1:0)-out.marginals[s][j];}bias=bias.map((v,j)=>v+lr*(gradient[j]/sequences.reduce((s,a)=>s+a.length,0)-l2*v));if(bias.some(v=>!Number.isFinite(v)))throw new RangeError('CRF gradient overflow');}const predictions=sequences.map(seq=>inferLinearCRF({unary:Array.from({length:seq.length},()=>[...bias]),transition}).mapPath);return {domain:'SUPERVISED_FINITE_LINEAR_CHAIN_CRF_BIAS_TRAINING',bias,transition,predictions,scope:'trains state biases with supplied fixed transition; no arbitrary neural feature network'};}

// #100: signature verification of linked state-transition certificates with replay guards.
export function signStateTransition(input,privateKey){object(input,'transition',['before','after','invariants','context','epoch','previousHash'],['before','after','invariants','context','epoch','previousHash']);const before=object(input.before,'before',Object.keys(input.before)),after=object(input.after,'after',Object.keys(input.after)),keys=unique(array(input.invariants,'invariants',1,128).map(v=>id(v,'invariant')),'invariants');id(input.context,'context');integer(input.epoch,'epoch',1,Number.MAX_SAFE_INTEGER);if(typeof input.previousHash!=='string')throw new TypeError('previousHash must be string');for(const key of keys)if(!Object.hasOwn(before,key)||!Object.hasOwn(after,key)||hash(before[key])!==hash(after[key]))throw new TypeError(`invariant changed ${key}`);const statement={kind:'SIGNED_STATE_TRANSITION_V1',beforeHash:hash(before),afterHash:hash(after),invariants:keys,context:input.context,epoch:input.epoch,previousHash:input.previousHash};return {statement,signature:sign(null,Buffer.from(canon(statement)),createPrivateKey(privateKey)).toString('base64'),algorithm:'Ed25519'};}
export function verifySignedTransition(input){object(input,'transition verification',['certificate','publicKey','before','after','context','epoch','previousHash'],['certificate','publicKey','before','after','context','epoch','previousHash']);const cert=object(input.certificate,'certificate',['statement','signature','algorithm']),s=object(cert.statement,'statement',['kind','beforeHash','afterHash','invariants','context','epoch','previousHash']);if(s.kind!=='SIGNED_STATE_TRANSITION_V1'||cert.algorithm!=='Ed25519'||s.context!==input.context||s.epoch!==input.epoch||s.previousHash!==input.previousHash||s.beforeHash!==hash(input.before)||s.afterHash!==hash(input.after)||!Array.isArray(s.invariants)||new Set(s.invariants).size!==s.invariants.length||s.invariants.some(k=>!Object.hasOwn(input.before,k)||!Object.hasOwn(input.after,k)||hash(input.before[k])!==hash(input.after[k])))return {domain:'SIGNED_CHAINED_STATE_TRANSITION',verified:false};let ok=false;try{ok=verify(null,Buffer.from(canon(s)),createPublicKey(input.publicKey),Buffer.from(cert.signature,'base64'));}catch{}return {domain:'SIGNED_CHAINED_STATE_TRANSITION',verified:ok,transitionHash:ok?hash(s):null};}
