import {object,array,number,integer,id,unique} from './shared.mjs';
import {vector,matrix,dot,solveLinear,seeded,normal,cholesky} from './numerics.mjs';
const sum=a=>a.reduce((s,v)=>s+v,0),sigmoid=x=>1/(1+Math.exp(-x)),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function stochastic(row,label,n){const p=vector(row,label,n,n);if(p.some(v=>v<0||v>1)||Math.abs(sum(p)-1)>1e-9)throw new TypeError(`${label} probability sum`);return p;}

// #82: peephole-LSTM forward inference with supplied gates/weights, no learned model claim.
export function inferPeepholeLSTM(input){
 object(input,'peephole LSTM',['sequence','weights','initialHidden','initialCell'],['sequence','weights']);const seq=array(input.sequence,'sequence',1,1000).map((row,i)=>vector(row,`seq${i}`,1,64)),din=seq[0].length;if(seq.some(row=>row.length!==din))throw new TypeError('ragged sequence');
 const W=object(input.weights,'weights',['input','forget','output','candidate','peepholes'],['input','forget','output','candidate','peepholes']),hsize=array(W.peepholes,'peepholes',3,3).length===3?vector(W.peepholes[0],'peepholes input',1,64).length:0;
 const gate=(key)=>{const g=object(W[key],`gate ${key}`,['input','hidden','bias'],['input','hidden','bias']);return {input:matrix(g.input,`${key}.input`,hsize,din),hidden:matrix(g.hidden,`${key}.hidden`,hsize,hsize),bias:vector(g.bias,`${key}.bias`,hsize,hsize)};};
 const gs=Object.fromEntries(['input','forget','output','candidate'].map(k=>[k,gate(k)]));const peepholes=W.peepholes.map((row,i)=>vector(row,`peepholes${i}`,hsize,hsize));let h=input.initialHidden===undefined?Array(hsize).fill(0):vector(input.initialHidden,'initialHidden',hsize,hsize),c=input.initialCell===undefined?Array(hsize).fill(0):vector(input.initialCell,'initialCell',hsize,hsize);const states=[];
 for(const x of seq){const compute=(key,ph)=>gs[key].bias.map((bias,j)=>bias+dot(gs[key].input[j],x)+dot(gs[key].hidden[j],h)+(peepholes[ph]?.[j]??0)*c[j]);const i=compute('input',0).map(sigmoid),f=compute('forget',1).map(sigmoid),g=compute('candidate',-1).map(Math.tanh);c=c.map((v,j)=>f[j]*v+i[j]*g[j]);const o=gs.output.bias.map((bias,j)=>sigmoid(bias+dot(gs.output.input[j],x)+dot(gs.output.hidden[j],h)+peepholes[2][j]*c[j]));h=c.map((v,j)=>o[j]*Math.tanh(v));states.push({hidden:h,cell:c});}
 return {domain:'PEEPHOLE_LSTM_FORWARD_INFERENCE',states,finalHidden:h,finalCell:c,trained:false};
}

// #83: low-rank power-iteration SVD on explicit snapshots, iterative residual checked.
export function streamingTruncatedSVD(input){
 object(input,'truncated SVD',['rows','rank','iterations','seed'],['rows','rank']);const A=array(input.rows,'rows',2,2048).map((r,i)=>vector(r,`row${i}`,2,128)),m=A.length,n=A[0].length;if(A.some(r=>r.length!==n))throw new TypeError('ragged matrix');const k=integer(input.rank,'rank',1,Math.min(m,n)),iterations=integer(input.iterations??300,'iterations',20,2000),rng=seeded(integer(input.seed??17,'seed',0,2**32-1));let R=A.map(row=>[...row]);const components=[];for(let j=0;j<k;j++){let v=Array.from({length:n},()=>rng()-.5),norm=Math.hypot(...v);v=v.map(x=>x/norm);let u=[];for(let t=0;t<iterations;t++){u=R.map(row=>dot(row,v));norm=Math.hypot(...u);if(norm<1e-11)break;u=u.map(x=>x/norm);v=Array.from({length:n},(_,col)=>sum(R.map((row,i)=>row[col]*u[i])));norm=Math.hypot(...v);if(norm<1e-11)break;v=v.map(x=>x/norm);}const av=R.map(row=>dot(row,v)),sigma=Math.hypot(...av);if(sigma<1e-10)break;u=av.map(x=>x/sigma);components.push({singularValue:sigma,left:u,right:v});R=R.map((row,i)=>row.map((x,col)=>x-sigma*u[i]*v[col]));}return {domain:'ITERATIVE_TRUNCATED_SVD',components,frobeniusResidual:Math.sqrt(sum(R.map(row=>dot(row,row)))),rank:components.length,note:'iterative approximation and deflation, not an exact full SVD or out-of-core memory map'};
}

// #84: discounted infinite-horizon MDP with certified Bellman residual bound.
export function solveDiscountedInfiniteMDP(input){
 object(input,'infinite MDP',['transitions','rewards','discount','tolerance','maxIterations'],['transitions','rewards','discount']);const T=array(input.transitions,'transitions',1,256),n=T.length,m=array(T[0],'actions',1,32).length,trans=T.map((actions,s)=>array(actions,`actions${s}`,m,m).map((r,a)=>stochastic(r,`T${s}:${a}`,n))),reward=array(input.rewards,'rewards',n,n).map((r,s)=>vector(r,`reward${s}`,m,m)),gamma=number(input.discount,'discount',0,.999999),tol=number(input.tolerance??1e-9,'tolerance',1e-13,1),max=integer(input.maxIterations??10000,'maxIterations',1,100000);let v=Array(n).fill(0),p=Array(n).fill(0),residual=Infinity,count=0;for(;count<max;count++){const next=v.map((_,s)=>{const qs=Array.from({length:m},(_,a)=>reward[s][a]+gamma*dot(trans[s][a],v));const best=Math.max(...qs);p[s]=qs.indexOf(best);return best;});residual=Math.max(...next.map((x,i)=>Math.abs(x-v[i])));v=next;if(residual<=tol){count++;break;}}const bellman=v.map((_,s)=>{const qs=Array.from({length:m},(_,a)=>reward[s][a]+gamma*dot(trans[s][a],v));const best=Math.max(...qs);p[s]=qs.indexOf(best);return best;});const bound=Math.max(...bellman.map((x,i)=>Math.abs(x-v[i])))/(1-gamma);return {domain:'DISCOUNTED_INFINITE_HORIZON_MDP',values:v,policy:p,iterations:count,converged:bound<=tol/(1-gamma),bellmanErrorBound:bound};
}

// #85: Newton logarithmic barrier for strictly feasible convex quadratic program.
export function solveInteriorPointQP(input){
 object(input,'interior QP',['H','c','A','b','initial','outerIterations','newtonIterations','tolerance'],['H','c','A','b','initial']);const c=vector(input.c,'c',1,12),n=c.length,H=matrix(input.H,'H',n,n),A=array(input.A,'A',1,128).map((r,i)=>vector(r,`A${i}`,n,n)),b=vector(input.b,'b',A.length,A.length),initial=vector(input.initial,'initial',n,n),outer=integer(input.outerIterations??12,'outerIterations',1,30),inner=integer(input.newtonIterations??80,'newtonIterations',1,200),tol=number(input.tolerance??1e-8,'tolerance',1e-12,.1);for(let i=0;i<n;i++)for(let j=0;j<n;j++)if(Math.abs(H[i][j]-H[j][i])>1e-10)throw new TypeError('H not symmetric');cholesky(H);let x=[...initial];const slacks=x=>A.map((row,i)=>b[i]-dot(row,x)),objective=x=>dot(c,x)+.5*dot(x,H.map(row=>dot(row,x)));if(slacks(x).some(v=>v<=0))throw new TypeError('initial must be strictly feasible');let time=1,barrierTime=1,steps=0;
 for(let t=0;t<outer;t++){barrierTime=time;for(let it=0;it<inner;it++){steps++;const s=slacks(x),Hx=H.map(row=>dot(row,x)),g=x.map((_,j)=>time*(Hx[j]+c[j])+sum(A.map((row,i)=>row[j]/s[i]))),B=H.map((r,i)=>r.map((v,j)=>time*v+sum(A.map((row,k)=>row[i]*row[j]/s[k]**2))));let dx;try{dx=solveLinear(B,g.map(v=>-v));}catch{throw new RangeError('barrier Hessian singular; H should be strongly convex');}const decrement=-dot(g,dx);if(decrement/2<tol)break;let rate=1;const f=x=>time*objective(x)-sum(slacks(x).map(v=>Math.log(v)));const old=f(x);while(rate>1e-15){const trial=x.map((v,j)=>v+rate*dx[j]);if(slacks(trial).every(v=>v>0)&&f(trial)<=old+.01*rate*dot(g,dx)){x=trial;break;}rate*=.5;}if(rate<=1e-15)throw new RangeError('interior point line search failed');}if(A.length/time<tol)break;time*=10;}
 const slack=slacks(x),dual=slack.map(v=>1/(barrierTime*v));
 const stationarity=x.map((_,j)=>dot(H[j],x)+c[j]+sum(A.map((row,i)=>row[j]*dual[i])));
 const gap=.5*dot(stationarity,solveLinear(H,stationarity))+dot(dual,slack);
 if(!Number.isFinite(gap))throw new RangeError('QP certificate overflow');
 return {domain:'STRICTLY_FEASIBLE_CONVEX_QP_LOG_BARRIER',status:gap<=tol?'CONVERGED':'ITERATION_LIMIT',solution:x,objective:objective(x),slacks:slack,dualMultipliers:dual,stationarityResidual:Math.hypot(...stationarity),primalDualGap:gap,barrierDualityGapBound:gap,centralPathComplementarity:A.length/barrierTime,newtonSteps:steps,assumptions:'strictly feasible input, symmetric positive definite Hessian; no infeasibility detection'};
}

// #86: Kuramoto oscillator network phase-order integration with explicit adjacency.
export function simulatePhaseSynchronization(input){object(input,'Kuramoto',['phases','frequencies','adjacency','coupling','dt','steps'],['phases','frequencies','adjacency','coupling','dt','steps']);let phi=vector(input.phases,'phases',2,128),n=phi.length,w=vector(input.frequencies,'frequencies',n,n),A=matrix(input.adjacency,'adjacency',n,n);if(A.flat().some(v=>v<0))throw new TypeError('nonnegative adjacency required');const k=number(input.coupling,'coupling',0,1e4),dt=number(input.dt,'dt',1e-9,1),steps=integer(input.steps,'steps',1,100000),history=[];function order(p){const c=sum(p.map(Math.cos))/n,s=sum(p.map(Math.sin))/n;return {strength:Math.hypot(c,s),angle:Math.atan2(s,c)};}history.push(order(phi));for(let t=0;t<steps;t++){const next=phi.map((v,i)=>v+dt*(w[i]+k/n*sum(phi.map((other,j)=>A[i][j]*Math.sin(other-v)))));phi=next.map(v=>((v+Math.PI)%(2*Math.PI)+2*Math.PI)%(2*Math.PI)-Math.PI);if((t+1)%Math.max(1,Math.floor(steps/100))===0)history.push(order(phi));}return {domain:'KURAMOTO_NETWORK_PHASE_SYNCHRONIZATION',phases:phi,order:order(phi),history};}

// #87: exponential Hawkes-process exact event likelihood and compensator on finite interval.
export function evaluateHawkesProcess(input){object(input,'Hawkes',['events','baseline','alpha','beta','horizon'],['events','baseline','alpha','beta','horizon']);const events=array(input.events,'events',0,10000).map((v,i)=>number(v,`event${i}`,0,1e12)),mu=number(input.baseline,'baseline',1e-12,1e9),alpha=number(input.alpha,'alpha',0,1e9),beta=number(input.beta,'beta',1e-12,1e9),T=number(input.horizon,'horizon',1e-12,1e12);if(events.some((v,i)=>v>=T||(i>0&&v<=events[i-1])))throw new TypeError('events must be strictly ordered before horizon');let log=0,shot=0,previous=0;const intensities=[];for(const time of events){shot*=Math.exp(-beta*(time-previous));const intensity=mu+alpha*shot;log+=Math.log(intensity);intensities.push(intensity);shot+=1;previous=time;}const compensator=mu*T+alpha/beta*sum(events.map(t=>1-Math.exp(-beta*(T-t))));return {domain:'EXPONENTIAL_HAWKES_POINT_PROCESS_LIKELIHOOD',logLikelihood:log-compensator,compensator,eventIntensities:intensities,branchingRatio:alpha/beta,stationaryUnderAssumptions:alpha<beta,note:'fixed known kernel, no fit or exogenous covariates'};}

// #88: boundary-constrained finite-horizon mean-field game, best-response fixed point.
export function solveBoundaryMeanFieldGame(input){object(input,'boundary MFG',['transition','cost','initial','horizon','congestion','iterations','relaxation','boundary'],['transition','cost','initial','horizon','congestion','boundary']);const initial=stochastic(input.initial,'initial',2),T=array(input.transition,'transition',2,2).map((byAction,i)=>array(byAction,`T${i}`,2,2).map((row,a)=>stochastic(row,`T${i}:${a}`,2))),cost=array(input.cost,'cost',2,2).map((r,i)=>vector(r,`cost${i}`,2,2)),congestion=vector(input.congestion,'congestion',2,2),boundary=array(input.boundary,'boundary',2,2).map((v,i)=>v===null?null:integer(v,`boundary${i}`,0,1)),horizon=integer(input.horizon,'horizon',1,50),iterations=integer(input.iterations??200,'iterations',1,10000),relaxation=number(input.relaxation??.5,'relaxation',1e-5,1);let trajectory=Array.from({length:horizon+1},()=>initial.slice()),policy=[],error=Infinity;
 for(let iter=0;iter<iterations;iter++){const V=Array.from({length:horizon+1},()=>[0,0]),P=Array.from({length:horizon},()=>[0,0]);for(let t=horizon-1;t>=0;t--)for(let s=0;s<2;s++){if(boundary[s]!==null){P[t][s]=boundary[s];V[t][s]=cost[s][boundary[s]]+congestion[s]*trajectory[t][s]+dot(T[s][boundary[s]],V[t+1]);}else{const vals=[0,1].map(a=>cost[s][a]+congestion[s]*trajectory[t][s]+dot(T[s][a],V[t+1]));P[t][s]=vals.indexOf(Math.min(...vals));V[t][s]=Math.min(...vals);}}const forward=[initial.slice()];for(let t=0;t<horizon;t++)forward.push(Array.from({length:2},(_,j)=>sum(forward[t].map((v,s)=>v*T[s][P[t][s]][j]))));error=Math.max(...forward.map((r,t)=>Math.max(...r.map((v,j)=>Math.abs(v-trajectory[t][j])))));trajectory=trajectory.map((r,t)=>r.map((v,j)=>v*(1-relaxation)+relaxation*forward[t][j]));policy=P;if(error<1e-9)return {domain:'BOUNDARY_CONSTRAINED_FINITE_MEAN_FIELD_GAME',status:'CONVERGED',policy,distribution:forward,error,iterations:iter+1};}
 return {domain:'BOUNDARY_CONSTRAINED_FINITE_MEAN_FIELD_GAME',status:'NOT_CONVERGED',policy,distribution:trajectory,error,iterations};}
