import {object,array,number,integer} from './shared.mjs';
import {vector,matrix,dot,seeded,normal,leastSquares,solveLinear} from './numerics.mjs';
const sum=a=>a.reduce((s,v)=>s+v,0), finite=(v,n)=>number(v,n,-1e12,1e12);
function simplex(a,name){const v=vector(a,name,2,512);if(v.some(x=>x<0||x>1)||Math.abs(sum(v)-1)>1e-9)throw new TypeError(`${name} probability sum`);return v;}
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));

// #71: information divergences, explicit extended-real output for support mismatch.
export function evaluateCrossEntropyKL(input){object(input,'divergence',['p','q','base'],['p','q']);const p=simplex(input.p,'p'),q=simplex(input.q,'q');if(q.length!==p.length)throw new TypeError('dimension mismatch');const base=number(input.base??Math.E,'base',1.0000001,1000),ln=Math.log(base),H=-sum(p.map(v=>v>0?v*Math.log(v):0))/ln;let cross=0,kl=0;for(let i=0;i<p.length;i++)if(p[i]>0){if(q[i]===0){cross=Infinity;kl=Infinity;break;}cross-=p[i]*Math.log(q[i])/ln;kl+=p[i]*Math.log(p[i]/q[i])/ln;}const m=p.map((v,i)=>(v+q[i])/2),js=sum(p.map((v,i)=>v>0?v*Math.log(v/m[i]):0))+sum(q.map((v,i)=>v>0?v*Math.log(v/m[i]):0));return {domain:'FINITE_DISCRETE_INFORMATION_DIVERGENCES',entropy:H,crossEntropy:Number.isFinite(cross)?cross:'Infinity',kl:Number.isFinite(kl)?Math.max(0,kl):'Infinity',jensenShannon:js/(2*ln),base};}

// #72: monotone finite-volume 1D Fokker–Planck, periodic conservative flux.
export function evolveFokkerPlanck(input){object(input,'Fokker Planck',['density','drift','diffusion','dx','dt','steps'],['density','drift','diffusion','dx','dt','steps']);let p=vector(input.density,'density',4,512);const n=p.length,drift=vector(input.drift,'drift',n,n),D=number(input.diffusion,'diffusion',0,100),dx=number(input.dx,'dx',1e-6,1e6),dt=number(input.dt,'dt',1e-9,1e6),steps=integer(input.steps,'steps',1,10000);if(p.some(x=>x<0))throw new TypeError('negative initial density');const initial=sum(p)*dx;if(initial<=0)throw new TypeError('zero density');if(dt*(Math.max(...drift.map(Math.abs))/dx+2*D/dx**2)>1+1e-12)throw new TypeError('Fokker-Planck CFL stability violated');const masses=[initial];for(let t=0;t<steps;t++){const flux=Array.from({length:n},(_,i)=>{const j=(i+1)%n,v=(drift[i]+drift[j])/2;return v*(v>=0?p[i]:p[j])-D*(p[j]-p[i])/dx;});p=p.map((v,i)=>v-dt/dx*(flux[i]-flux[(i+n-1)%n]));if(p.some(v=>v< -1e-10||!Number.isFinite(v)))throw new RangeError('density unstable');p=p.map(v=>Math.max(0,v));masses.push(sum(p)*dx);}return {domain:'PERIODIC_FINITE_VOLUME_FOKKER_PLANCK',density:p,initialMass:initial,finalMass:sum(p)*dx,maxMassDrift:Math.max(...masses.map(v=>Math.abs(v-initial)))};}

// #73: exact Pauli covariance tensor of a physical 2-level quantum density matrix.
export function qubitCoherenceTensor(input){object(input,'qubit density',['density'],['density']);const d=array(input.density,'density',2,2).map((r,i)=>array(r,`row${i}`,2,2).map((z,j)=>{object(z,`entry${i}${j}`,['re','im'],['re','im']);return {re:finite(z.re,'re'),im:finite(z.im,'im')};}));if(Math.abs(d[0][0].im)>1e-12||Math.abs(d[1][1].im)>1e-12||Math.abs(d[0][1].re-d[1][0].re)>1e-12||Math.abs(d[0][1].im+d[1][0].im)>1e-12||Math.abs(d[0][0].re+d[1][1].re-1)>1e-10)throw new TypeError('density not Hermitian trace one');const det=d[0][0].re*d[1][1].re-(d[0][1].re**2+d[0][1].im**2);if(d[0][0].re<0||d[1][1].re<0||det< -1e-10)throw new TypeError('density not positive semidefinite');const bloch=[2*d[0][1].re,-2*d[0][1].im,d[0][0].re-d[1][1].re],purity=(1+dot(bloch,bloch))/2;return {domain:'QUBIT_PAULI_COVARIANCE_TENSOR',bloch,purity,linearEntropy:1-purity,l1Coherence:2*Math.hypot(d[0][1].re,d[0][1].im),covariance:bloch.map((v,i)=>bloch.map((w,j)=>(i===j?1:0)-v*w)),note:'qubit Pauli anticommutator covariance, not a general quantum tensor calculus'};}

// #74: bootstrap particle filter plus explicitly heuristic genetic rejuvenation.
export function particleFilterGenetic(input){object(input,'particle filter',['observations','initialMean','initialStd','processStd','measurementStd','particles','seed','crossover','mutationStd'],['observations','initialMean','initialStd','processStd','measurementStd']);const observations=array(input.observations,'observations',1,1000).map((v,i)=>finite(v,`observation${i}`)),mu=finite(input.initialMean,'initialMean'),std=number(input.initialStd,'initialStd',1e-9,1e6),process=number(input.processStd,'processStd',0,1e6),measurement=number(input.measurementStd,'measurementStd',1e-9,1e6),N=integer(input.particles??512,'particles',32,4096),rng=seeded(integer(input.seed??7,'seed',0,2**32-1)),crossover=number(input.crossover??0,'crossover',0,1),mutation=number(input.mutationStd??0,'mutationStd',0,1e6);let ps=Array.from({length:N},()=>mu+std*normal(rng));const history=[];for(const y of observations){ps=ps.map(x=>x+process*normal(rng));const logw=ps.map(x=>-((x-y)**2)/(2*measurement**2)),mx=Math.max(...logw),w=logw.map(x=>Math.exp(x-mx)),z=sum(w);if(z===0)throw new RangeError('particle weights underflow');const norm=w.map(x=>x/z),effective=1/sum(norm.map(x=>x*x)),cdf=[],step=1/N;let running=0;for(const p of norm){running+=p;cdf.push(running);}let u=rng()/N,idx=0;let next=Array.from({length:N},(_,i)=>{const target=u+i*step;while(idx<N-1&&cdf[idx]<target)idx++;return ps[idx];});if(crossover>0||mutation>0)next=next.map((v,i)=>{if(rng()<crossover)v=(v+next[Math.floor(rng()*N)])/2;return v+mutation*normal(rng);});ps=next;history.push({posteriorMean:sum(ps)/N,posteriorVariance:sum(ps.map(v=>(v-sum(ps)/N)**2))/N,effectiveBeforeResampling:effective});}return {domain:'LINEAR_GAUSSIAN_PARTICLE_FILTER_GENETIC_REJUVENATION',history,finalParticles:ps,seed:input.seed??7,warning:'genetic crossover/mutation alters the Bayesian target unless corrected; set both to zero for bootstrap filtering'};}

// #75: spatiotemporal capsule dynamic-routing forward operator (no learning).
export function spatiotemporalCapsules(input){object(input,'capsules',['capsules','transforms','iterations','times','queryTime','temporalDecay','locations','queryLocation','spatialDecay'],['capsules','transforms']);const caps=array(input.capsules,'capsules',1,64).map((v,i)=>vector(v,`capsule${i}`,1,16));const n=caps.length,d=caps[0].length;if(caps.some(v=>v.length!==d))throw new TypeError('ragged capsules');const transforms=array(input.transforms,'transforms',1,16).map((byInput,j)=>array(byInput,`transform${j}`,n,n).map((M,i)=>matrix(M,`transform${j}:${i}`,d,d)));const m=transforms.length,it=integer(input.iterations??3,'iterations',1,20),times=input.times===undefined?null:vector(input.times,'times',n,n),queryTime=input.queryTime===undefined?null:finite(input.queryTime,'queryTime'),temporalDecay=number(input.temporalDecay??0,'temporalDecay',0,1e6),locations=input.locations===undefined?null:array(input.locations,'locations',n,n).map((v,i)=>vector(v,`location${i}`,2,3)),queryLocation=input.queryLocation===undefined?null:vector(input.queryLocation,'queryLocation',2,3),spatialDecay=number(input.spatialDecay??0,'spatialDecay',0,1e6),votes=transforms.map(byInput=>byInput.map((W,i)=>W.map(row=>dot(row,caps[i]))));if((times===null)!==(queryTime===null)||(locations===null)!==(queryLocation===null))throw new TypeError('time and location metadata require query values');if(locations&&locations.some(v=>v.length!==queryLocation.length))throw new TypeError('location dimension mismatch');if(times&&times.some(v=>v>queryTime))throw new TypeError('future capsule is not causally available');const penalties=caps.map((_,i)=>(times?temporalDecay*(queryTime-times[i]):0)+(locations?spatialDecay*Math.hypot(...locations[i].map((v,j)=>v-queryLocation[j])):0));const logits=Array.from({length:n},()=>Array(m).fill(0));let outputs=[];let coupling=[];for(let t=0;t<it;t++){coupling=logits.map(row=>{const mx=Math.max(...row),e=row.map(x=>Math.exp(x-mx)),z=sum(e);return e.map(x=>x/z);});outputs=Array.from({length:m},(_,j)=>{const v=Array.from({length:d},(_,k)=>sum(votes[j].map((vote,i)=>coupling[i][j]*Math.exp(-penalties[i])*vote[k]))),norm2=dot(v,v);return norm2===0?v:v.map(x=>x*Math.sqrt(norm2)/(1+norm2));});if(t<it-1)for(let i=0;i<n;i++)for(let j=0;j<m;j++)logits[i][j]+=dot(votes[j][i],outputs[j]);}return {domain:'SPATIOTEMPORAL_CAPSULE_ROUTING_FORWARD',outputs,coupling,activation:outputs.map(v=>Math.sqrt(dot(v,v))),temporalSpatialWeights:penalties.map(v=>Math.exp(-v)),trained:false};}

// #76: long-memory self-interacting walk with power-law weighted historical increments.
export function simulateLongMemoryWalk(input){object(input,'memory walk',['steps','alpha','memoryWeight','seed','initial'],['steps','alpha','memoryWeight']);const steps=integer(input.steps,'steps',1,100000),alpha=number(input.alpha,'alpha',0,5),memory=number(input.memoryWeight,'memoryWeight',-1,1),rng=seeded(integer(input.seed??12,'seed',0,2**32-1));let x=finite(input.initial??0,'initial');const positions=[x],increments=[];for(let t=0;t<steps;t++){const lookback=Math.min(128,increments.length),weights=Array.from({length:lookback},(_,i)=>(i+1)**(-alpha)),z=sum(weights),history=z?sum(weights.map((w,i)=>w*increments[increments.length-1-i]))/z:0;const p=clamp((1+memory*history)/2,0,1),step=rng()<p?1:-1;increments.push(step);x+=step;positions.push(x);}return {domain:'POWER_LAW_LONG_MEMORY_RANDOM_WALK',positions,lagExponent:alpha,memoryWeight:memory,seed:input.seed??12};}

// #77: 3D periodic incompressible flow one or more explicit projection steps.
export function simulateNavierStokes3D(input){object(input,'Navier Stokes',['n','velocity','viscosity','dt','dx','steps','pressureIterations'],['n','velocity','viscosity','dt','dx','steps']);const n=integer(input.n,'n',4,12),N=n**3,vel=array(input.velocity,'velocity',N,N).map((row,i)=>vector(row,`velocity${i}`,3,3)),nu=number(input.viscosity,'viscosity',0,100),dt=number(input.dt,'dt',1e-8,100),dx=number(input.dx,'dx',1e-6,100),steps=integer(input.steps,'steps',1,40),iterations=integer(input.pressureIterations??240,'pressureIterations',20,5000);const idx=(x,y,z)=>((z+n)%n*n+(y+n)%n)*n+(x+n)%n;let u=vel.map(v=>[...v]);const history=[];
 const at=(v,x,y,z,j)=>v[idx(x,y,z)][j],grid=N=>Array.from({length:N},()=>Array(3).fill(0));
 const deriv=(v,x,y,z,j,axis)=>(axis===0?at(v,x+1,y,z,j)-at(v,x-1,y,z,j):axis===1?at(v,x,y+1,z,j)-at(v,x,y-1,z,j):at(v,x,y,z+1,j)-at(v,x,y,z-1,j))/(2*dx);
 for(let t=0;t<steps;t++){const maxVel=Math.max(...u.map(v=>Math.hypot(...v)));if(dt*(3*maxVel/dx+6*nu/dx**2)>1)throw new TypeError('Navier-Stokes explicit stability CFL exceeded');const starred=grid(N);for(let z=0;z<n;z++)for(let y=0;y<n;y++)for(let x=0;x<n;x++){const k=idx(x,y,z);for(let j=0;j<3;j++){const adv=sum([0,1,2].map(axis=>u[k][axis]*deriv(u,x,y,z,j,axis))),lap=(at(u,x+1,y,z,j)+at(u,x-1,y,z,j)+at(u,x,y+1,z,j)+at(u,x,y-1,z,j)+at(u,x,y,z+1,j)+at(u,x,y,z-1,j)-6*u[k][j])/dx**2;starred[k][j]=u[k][j]+dt*(nu*lap-adv);}}
 const div=Array(N).fill(0);for(let z=0;z<n;z++)for(let y=0;y<n;y++)for(let x=0;x<n;x++){div[idx(x,y,z)]=((at(starred,x+1,y,z,0)-at(starred,x,y,z,0))+(at(starred,x,y+1,z,1)-at(starred,x,y,z,1))+(at(starred,x,y,z+1,2)-at(starred,x,y,z,2)))/(dx*dt);}
 let pressure=Array(N).fill(0);const rhsMean=sum(div)/N;for(let iter=0;iter<iterations;iter++){const next=pressure.map((_,k)=>{const x=k%n,y=Math.floor(k/n)%n,z=Math.floor(k/n**2);return (pressure[idx(x+1,y,z)]+pressure[idx(x-1,y,z)]+pressure[idx(x,y+1,z)]+pressure[idx(x,y-1,z)]+pressure[idx(x,y,z+1)]+pressure[idx(x,y,z-1)]-dx**2*(div[k]-rhsMean))/6;});pressure=next;}
 u=starred.map((v,k)=>{const x=k%n,y=Math.floor(k/n)%n,z=Math.floor(k/n**2);return v.map((a,j)=>a-dt*(j===0?pressure[idx(x,y,z)]-pressure[idx(x-1,y,z)]:j===1?pressure[idx(x,y,z)]-pressure[idx(x,y-1,z)]:pressure[idx(x,y,z)]-pressure[idx(x,y,z-1)])/(dx));});const rms=Math.sqrt(sum(u.map(v=>dot(v,v)))/N);history.push({step:t+1,rmsVelocity:rms,pressureResidual:Math.sqrt(sum(pressure.map((p,k)=>{const x=k%n,y=Math.floor(k/n)%n,z=Math.floor(k/n**2);const lap=(pressure[idx(x+1,y,z)]+pressure[idx(x-1,y,z)]+pressure[idx(x,y+1,z)]+pressure[idx(x,y-1,z)]+pressure[idx(x,y,z+1)]+pressure[idx(x,y,z-1)]-6*p)/dx**2;return (lap-(div[k]-rhsMean))**2;}))/N)});}
 return {domain:'BOUNDED_PERIODIC_3D_NAVIER_STOKES_FINITE_DIFFERENCE',velocity:u,history,n,limitations:'finite resolution explicit scheme, approximate pressure projection; no global smoothness guarantee'};
}

// #78: DFA1 fluctuation scaling on integrated, centered signal.
export function detrendedFluctuationAnalysis(input){object(input,'DFA',['series','scales'],['series','scales']);const x=vector(input.series,'series',32,200000),mean=sum(x)/x.length;let c=0;const y=x.map(v=>c+=v-mean),scales=array(input.scales,'scales',2,30).map(v=>integer(v,'scale',4,Math.floor(x.length/2)));if(new Set(scales).size!==scales.length)throw new TypeError('duplicate scales');const fluct=scales.map(size=>{let squared=0,count=0;for(const reverse of [false,true])for(let start=0;start+size<=x.length;start+=size){const offset=reverse?x.length-start-size:start;const segment=y.slice(offset,offset+size),meanX=(size-1)/2,ym=sum(segment)/size,den=size*(size**2-1)/12,slope=sum(segment.map((v,i)=>(i-meanX)*(v-ym)))/den;for(let i=0;i<size;i++)squared+=(segment[i]-(ym+slope*(i-meanX)))**2;count+=size;}return {scale:size,fluctuation:Math.sqrt(squared/count)};});if(fluct.some(v=>v.fluctuation<=0))return {domain:'DFA1',fluctuations:fluct,scalingExponent:null,warning:'exact polynomial series has zero fluctuation; exponent undefined'};const lx=fluct.map(v=>Math.log(v.scale)),ly=fluct.map(v=>Math.log(v.fluctuation)),mx=sum(lx)/lx.length,my=sum(ly)/ly.length,den=sum(lx.map(v=>(v-mx)**2));return {domain:'DFA1',fluctuations:fluct,scalingExponent:sum(lx.map((v,i)=>(v-mx)*(ly[i]-my)))/den};}

// #79: quantum-behaved particle swarm algorithm (QPSO); classical, no quantum accelerator.
export function quantumBehavedSwarm(input){object(input,'QPSO',['bounds','target','particles','iterations','seed','beta'],['bounds','target']);const bounds=array(input.bounds,'bounds',1,16).map((b,i)=>{const pair=vector(b,`bound${i}`,2,2);if(pair[0]>=pair[1])throw new TypeError('invalid bound');return pair;}),d=bounds.length,target=vector(input.target,'target',d,d),N=integer(input.particles??32,'particles',3,512),steps=integer(input.iterations??100,'iterations',1,10000),beta=number(input.beta??.75,'beta',0.00001,2),rng=seeded(integer(input.seed??10,'seed',0,2**32-1));let xs=Array.from({length:N},()=>bounds.map(([a,b])=>a+(b-a)*rng())),pb=xs.map(x=>[...x]),score=x=>sum(x.map((v,j)=>(v-target[j])**2)),ps=pb.map(score),best=ps.indexOf(Math.min(...ps)),gb=[...pb[best]];for(let t=0;t<steps;t++){const mb=bounds.map((_,j)=>sum(pb.map(v=>v[j]))/N);xs=xs.map((x,i)=>x.map((v,j)=>{const phi=rng(),center=phi*pb[i][j]+(1-phi)*gb[j],displacement=beta*Math.abs(mb[j]-v)*Math.log(1/Math.max(rng(),1e-15));return clamp(center+(rng()<.5?-1:1)*displacement,...bounds[j]);}));for(let i=0;i<N;i++){const s=score(xs[i]);if(s<ps[i]){ps[i]=s;pb[i]=[...xs[i]];if(s<score(gb))gb=[...xs[i]];}}}return {domain:'CLASSICAL_QUANTUM_BEHAVED_PARTICLE_SWARM',best:gb,objective:score(gb),seed:input.seed??10,globallyOptimalCertified:false};}

// #80: finite grid stochastic HJB solved by monotone Bellman discretization.
export function solveFiniteGridHJB(input){object(input,'HJB',['grid','controls','terminalCosts','runningCosts','drift','diffusion','dt','steps'],['grid','controls','terminalCosts','runningCosts','drift','diffusion','dt','steps']);const grid=vector(input.grid,'grid',3,200),n=grid.length,controls=vector(input.controls,'controls',1,32),terminal=vector(input.terminalCosts,'terminalCosts',n,n),running=matrix(input.runningCosts,'runningCosts',n,controls.length),drift=matrix(input.drift,'drift',n,controls.length),D=number(input.diffusion,'diffusion',0,100),dt=number(input.dt,'dt',1e-9,100),steps=integer(input.steps,'steps',1,1000);const dx=grid[1]-grid[0];if(dx<=0||grid.some((x,i)=>i>0&&Math.abs(x-grid[0]-dx*i)>1e-8))throw new TypeError('uniform increasing grid required');if(dt*(Math.max(...drift.flat().map(Math.abs))/dx+2*D/dx**2)>1+1e-12)throw new TypeError('HJB monotone CFL violated');let values=[...terminal],policies=[];for(let t=steps-1;t>=0;t--){const next=[],actions=[];for(let i=0;i<n;i++){const vals=controls.map((_,a)=>{const vel=drift[i][a],left=dt*(D/dx**2+Math.max(-vel,0)/dx),right=dt*(D/dx**2+Math.max(vel,0)/dx),stay=1-left-right;if(stay< -1e-10)throw new TypeError('HJB invalid transition');return dt*running[i][a]+stay*values[i]+left*values[Math.max(0,i-1)]+right*values[Math.min(n-1,i+1)];});const v=Math.min(...vals);next.push(v);actions.push(vals.indexOf(v));}values=next;policies.unshift(actions);}return {domain:'MONOTONE_FINITE_GRID_STOCHASTIC_HJB',values,policies,grid,controls,assumption:'known bounded scalar diffusion, reflecting boundaries, fixed grid and horizon'};}
