from __future__ import annotations

from typing import Any
from .specs_common import add

_MODES = (
    "traffic_window_record_coverage",
    "traffic_window_equal_duration_integrity",
    "traffic_window_positive_baseline_share",
    "traffic_window_average_retention",
    "traffic_window_growth_share",
    "traffic_window_decline_health",
    "traffic_window_flat_share",
    "traffic_window_severe_decline_health",
    "traffic_window_median_retention",
    "traffic_window_weighted_retention",
    "traffic_window_content_entity_bridge",
    "traffic_window_search_landing_bridge",
    "traffic_window_canonical_bridge",
    "current_visit_concentration_health",
    "baseline_visit_concentration_health",
    "retention_dispersion_health",
    "top_entity_dependency_health",
    "portfolio_floor_retention",
    "lower_quartile_retention",
    "traffic_window_evidence_breadth",
    "traffic_series_record_coverage",
    "traffic_series_minimum_depth_share",
    "traffic_series_nonzero_evidence_share",
    "traffic_series_recent_activity_share",
    "traffic_series_recovery_from_minimum_share",
    "traffic_series_ending_above_start_share",
    "traffic_series_ending_above_median_share",
    "traffic_series_positive_step_share",
    "traffic_series_negative_step_health",
    "traffic_series_stable_step_share",
    "traffic_series_direction_consistency",
    "traffic_series_monotonic_recovery_share",
    "traffic_series_last_quartile_retention",
    "traffic_series_last_quartile_stability",
    "traffic_series_median_step_stability",
    "traffic_series_max_step_shock_health",
    "traffic_series_active_run_health",
    "traffic_series_recovery_latency_health",
    "traffic_series_peak_recapture_share",
    "traffic_series_trough_distance_health",
    "traffic_series_area_retention",
    "traffic_series_recent_weighted_strength",
    "traffic_series_step_sign_balance",
    "traffic_series_turning_point_health",
    "traffic_series_entity_breadth",
    "content_decay_record_coverage",
    "content_decay_equal_window_integrity",
    "content_decay_click_retention",
    "content_decay_impression_retention",
    "content_decay_click_impression_balance",
    "content_decay_ctr_retention",
    "content_decay_severe_click_health",
    "content_decay_severe_impression_health",
    "content_decay_dual_signal_health",
    "content_decay_content_backing",
    "content_decay_search_landing_backing",
    "content_decay_canonical_backing",
    "content_decay_sitemap_backing",
    "content_decay_inlink_backing",
    "content_decay_entity_backing",
    "content_decay_local_identity_backing",
    "decaying_page_current_demand_support",
    "decaying_page_high_intent_support",
    "decaying_page_local_demand_support",
    "decaying_page_service_demand_support",
    "decaying_page_urgency_demand_support",
    "decaying_page_zero_click_opportunity_support",
    "decaying_page_rank_gap_opportunity_support",
    "decaying_page_click_gap_magnitude",
    "decaying_page_impression_gap_magnitude",
    "traffic_window_decay_direction_concordance",
    "traffic_window_search_demand_concordance",
    "traffic_series_decay_direction_concordance",
    "window_and_decay_retention_agreement",
    "click_and_visit_direction_agreement",
    "impression_and_visit_direction_agreement",
    "demand_weighted_decay_review_signal",
    "local_demand_weighted_decay_review_signal",
    "high_intent_decay_review_signal",
    "funnel_weighted_decay_review_signal",
    "recovery_evidence_confidence",
    "preservation_evidence_confidence",
    "structural_review_evidence_confidence",
    "temporal_intervention_evidence_confidence",
    "temporal_evidence_breadth",
    "temporal_conflict_health",
    "temporal_signal_agreement",
    "temporal_resilience_score",
    "temporal_decision_readiness",
    "organic_temporal_observatory_health",
)


def build(rows: list[dict[str, Any]]) -> None:
    for mode in _MODES:
        add(
            rows,
            "ORGANIC_TEMPORAL_OBSERVATORY",
            f"temporal_observatory_{mode}",
            "MULTI",
            "temporal_observatory_metric",
            {"mode": mode},
            "Compute the evidence-constrained organic temporal observatory property "
            + mode.replace("_", " ")
            + " by reconciling existing traffic windows/series, content-decay, Search demand, canonical/content/entity and funnel evidence; measure observed change without causal or ranking forecasts.",
            (),
            500_000,
        )
