from __future__ import annotations

from typing import Any
from .specs_common import add

_CAPABILITIES = (
    ('discovery_canonical_sitemap_presence_health', 'canonical_sitemap_presence', 500000, 'Require canonicalized URLs to participate in supplied sitemap evidence when eligible.'),
    ('discovery_canonical_sitemap_database_parity_health', 'canonical_sitemap_db_parity', 500000, 'Measure supplied sitemap/database presence parity for canonicalized URL records.'),
    ('discovery_canonical_index_eligibility_health', 'canonical_index_eligibility', 700000, 'Measure canonical records that are not explicitly excluded or archived.'),
    ('discovery_canonical_archive_exclusion_consistency', 'canonical_archive_exclusion', 700000, 'Require archived canonical records to be excluded and active records not to be silently excluded.'),
    ('discovery_canonical_internal_inlink_presence_health', 'canonical_inlink_presence', 500000, 'Measure canonical records with at least one observed internal inlink.'),
    ('discovery_canonical_internal_inlink_depth_health', 'canonical_inlink_depth', 700000, 'Measure canonical records with at least three observed internal inlinks.'),
    ('discovery_canonical_integrity_verified_share', 'canonical_integrity', 500000, 'Measure exact canonical integrity verification coverage from supplied records.'),
    ('discovery_canonical_quality_floor_share', 'canonical_quality_floor', 700000, 'Measure canonical records meeting the supplied deterministic quality floor.'),
    ('discovery_canonical_structural_stability_health', 'canonical_structural_stability', 500000, 'Measure canonical records without excessive structural churn in the supplied 24h window.'),
    ('discovery_canonical_activity_health', 'canonical_activity', 500000, 'Measure active canonical records that are neither archived nor excessively inactive.'),
    ('discovery_canonical_query_cluster_presence', 'canonical_query_cluster', 500000, 'Measure canonical records with an explicit query-cluster assignment.'),
    ('discovery_canonical_brand_entity_presence', 'canonical_brand_entity', 500000, 'Measure canonical records with an explicit brand entity.'),
    ('discovery_canonical_entity_inventory_presence', 'canonical_entity_inventory', 500000, 'Measure canonical records with at least one supplied entity.'),
    ('discovery_canonical_schema_signature_presence', 'canonical_schema_signature', 500000, 'Measure canonical records with an explicit schema signature.'),
    ('discovery_canonical_slug_semantic_key_consistency', 'canonical_slug_semantic_consistency', 500000, 'Measure slug/semantic-key consistency after deterministic normalization.'),
    ('discovery_persistence_publication_ready_share', 'persistence_publication_ready', 500000, 'Measure routes explicitly published in the existing persistence-state contract.'),
    ('discovery_persistence_route_query_store_ready_share', 'persistence_route_query_ready', 500000, 'Measure routes whose internal query-store index flag is ready; this is not Google indexation.'),
    ('discovery_persistence_sitemap_hash_parity', 'persistence_sitemap_hash_parity', 500000, 'Measure byte-identity between supplied sitemap and persisted sitemap hashes.'),
    ('discovery_persistence_snapshot_hash_parity', 'persistence_snapshot_hash_parity', 500000, 'Measure persisted snapshot hash parity.'),
    ('discovery_persistence_broken_reference_free_share', 'persistence_broken_refs', 500000, 'Measure routes with no supplied broken references.'),
    ('discovery_persistence_committed_transaction_share', 'persistence_transaction_committed', 500000, 'Measure committed persistence transaction state.'),
    ('discovery_persistence_active_lock_share', 'persistence_lock_active', 500000, 'Measure records carrying the expected active write-lock evidence.'),
    ('discovery_persistence_grounding_match_share', 'persistence_grounding_match', 500000, 'Measure grounding-match evidence coverage.'),
    ('discovery_persistence_grounding_store_ready_share', 'persistence_grounding_indexed', 500000, 'Measure internal grounding-store readiness; this is not a search-engine index claim.'),
    ('discovery_persistence_retry_budget_health', 'persistence_retry_budget', 500000, 'Measure records within a bounded retry budget.'),
    ('discovery_persistence_queue_priority_order_health', 'persistence_queue_priority_order', 500000, 'Measure monotonic consistency between supplied queue priority and queue position.'),
    ('discovery_persistence_known_route_membership', 'persistence_known_route_membership', 700000, 'Measure whether each persisted route is present in its supplied known-route set.'),
    ('discovery_persistence_config_version_presence', 'persistence_config_version', 500000, 'Measure positive persistence configuration-version coverage.'),
    ('discovery_persistence_table_index_health', 'persistence_table_index_health', 500000, 'Measure supplied persistence table index-health evidence.'),
    ('discovery_persistence_update_observation_order_health', 'persistence_update_observation_order', 500000, 'Require updated_at evidence not to occur after its observation timestamp.'),
    ('discovery_gateway_publisher_health_share', 'gateway_health', 500000, 'Measure publisher health evidence.'),
    ('discovery_gateway_status_delivery_health', 'gateway_status_delivery', 700000, 'Measure supplied publisher responses in the successful/redirect HTTP classes.'),
    ('discovery_gateway_fallback_free_share', 'gateway_fallback_free', 500000, 'Measure requests served without fallback.'),
    ('discovery_gateway_target_domain_consistency', 'gateway_target_domain', 500000, 'Measure target-domain/expected-domain parity.'),
    ('discovery_gateway_policy_version_consistency', 'gateway_policy_version', 500000, 'Measure active/expected publisher policy-version parity.'),
    ('discovery_gateway_snapshot_version_consistency', 'gateway_snapshot_version', 500000, 'Measure publisher snapshot-version parity.'),
    ('discovery_gateway_nonempty_response_share', 'gateway_nonempty_response', 500000, 'Measure publisher responses carrying non-zero body bytes.'),
    ('discovery_gateway_redirect_budget_health', 'gateway_redirect_budget', 500000, 'Measure publisher redirect chains within the bounded discovery budget.'),
    ('discovery_gateway_cache_hit_share', 'gateway_cache_hit', 500000, 'Measure cache-hit coverage for supplied publisher evidence.'),
    ('discovery_gateway_compression_presence', 'gateway_compression', 500000, 'Measure response compression-header coverage.'),
    ('discovery_gateway_html_content_type_share', 'gateway_html_content_type', 500000, 'Measure HTML response content-type coverage.'),
    ('discovery_gateway_suite_signature_presence', 'gateway_suite_signature', 500000, 'Measure explicit SEO suite-signature coverage.'),
    ('discovery_gateway_exclusion_reason_free_share', 'gateway_exclusion_reasons', 500000, 'Measure records without supplied exclusion reasons.'),
    ('discovery_gateway_worker_site_identity_health', 'gateway_worker_site_identity', 500000, 'Measure worker-schema site identity parity.'),
    ('discovery_gateway_https_endpoint_share', 'gateway_https_endpoint', 500000, 'Measure HTTPS publisher endpoint coverage.'),
    ('discovery_edge_latency_budget_health', 'cwv_latency_budget', 500000, 'Measure edge response latency against a bounded delivery budget.'),
    ('discovery_edge_client_render_budget_health', 'cwv_client_render_budget', 500000, 'Measure supplied client-render time against a bounded rendering budget.'),
    ('discovery_edge_nonempty_response_share', 'cwv_nonempty_response', 500000, 'Measure non-empty edge responses.'),
    ('discovery_edge_internal_redirect_budget_health', 'cwv_redirect_budget', 500000, 'Measure internal redirect chains within a bounded crawl path.'),
    ('discovery_edge_critical_asset_presence', 'cwv_critical_assets', 500000, 'Measure explicit critical-asset declaration coverage.'),
    ('discovery_edge_compression_delivery_share', 'cwv_compression', 500000, 'Measure compressed delivery coverage.'),
    ('discovery_edge_cache_control_presence', 'cwv_cache_control', 500000, 'Measure cache-control header coverage.'),
    ('discovery_edge_csp_presence', 'cwv_csp', 500000, 'Measure Content-Security-Policy header coverage.'),
    ('discovery_edge_nosniff_presence', 'cwv_nosniff', 500000, 'Measure X-Content-Type-Options nosniff coverage.'),
    ('discovery_edge_referrer_policy_presence', 'cwv_referrer_policy', 500000, 'Measure referrer-policy header coverage.'),
    ('discovery_edge_desktop_mobile_parity', 'cwv_device_parity', 500000, 'Measure exact supplied desktop/mobile render parity.'),
    ('discovery_edge_geo_header_authorization', 'cwv_geo_authorization', 700000, 'Measure authorization of supplied geographic response headers.'),
    ('discovery_edge_transform_budget_health', 'cwv_transform_budget', 500000, 'Measure transformation latency against a bounded edge budget.'),
    ('discovery_edge_asset_budget_health', 'cwv_asset_budget', 500000, 'Measure aggregate critical asset bytes against a deterministic budget.'),
    ('discovery_edge_https_url_share', 'cwv_https_url', 500000, 'Measure HTTPS URL coverage in edge evidence.'),
    ('discovery_policy_robots_expectation_parity', 'policy_robots_parity', 500000, 'Measure robots allow-state parity against the declared expectation.'),
    ('discovery_policy_indexability_expectation_consistency', 'policy_indexability_consistency', 500000, 'Measure index/follow directives against the declared project indexability expectation without asserting Google state.'),
    ('discovery_policy_followability_expectation_consistency', 'policy_followability_consistency', 500000, 'Measure followability directives against the declared expectation.'),
    ('discovery_policy_human_bot_content_parity', 'policy_human_bot_parity', 500000, 'Measure exact supplied human/bot content parity to resist cloaking.'),
    ('discovery_policy_origin_status_contract_health', 'policy_status_contract', 500000, 'Measure supplied response status contracts including explicit maintenance/redirect handling.'),
    ('discovery_policy_authorized_domain_share', 'policy_authorized_domain', 500000, 'Measure target-domain membership in supplied authorized-domain evidence.'),
    ('discovery_policy_html_content_type_share', 'policy_content_type', 500000, 'Measure HTML content-type coverage in policy evidence.'),
    ('discovery_policy_stream_transfer_share', 'policy_stream_transfer', 500000, 'Measure declared streaming transfer-mode coverage.'),
    ('discovery_policy_site_identity_consistency', 'policy_site_identity', 500000, 'Measure site-id/expected-site-id parity.'),
    ('discovery_policy_structured_data_presence', 'policy_jsonld_presence', 500000, 'Measure presence of supplied JSON-LD type evidence.'),
    ('discovery_policy_visible_text_presence', 'policy_visible_text', 500000, 'Measure non-empty visible-text evidence.'),
    ('discovery_policy_heading_presence', 'policy_heading_presence', 500000, 'Measure non-empty heading evidence.'),
    ('discovery_policy_closure_integrity_share', 'policy_closure_integrity', 500000, 'Measure closure integrity checks.'),
    ('discovery_policy_closure_policy_share', 'policy_closure_policy', 500000, 'Measure closure policy checks.'),
    ('discovery_policy_retry_after_contract_health', 'policy_retry_after', 500000, 'Require Retry-After evidence on supplied 503 responses while leaving other statuses unaffected.'),
    ('discovery_intent_to_canonical_keyword_bridge_health', 'cross_intent_canonical_keyword', 500000, 'Measure lexical bridges between supplied search-intent queries and canonical keyword evidence.'),
    ('discovery_intent_to_canonical_cluster_bridge_health', 'cross_intent_canonical_cluster', 500000, 'Measure search-intent silo/query language against canonical query-cluster evidence.'),
    ('discovery_intent_internal_anchor_discovery_health', 'cross_intent_internal_anchor', 500000, 'Measure internal-anchor coverage in supplied search-intent records.'),
    ('discovery_intent_navigation_entity_discovery_health', 'cross_intent_navigation_entity', 500000, 'Measure navigation-entity coverage in search-intent evidence.'),
    ('discovery_intent_same_silo_link_reinforcement_health', 'cross_intent_same_silo_links', 500000, 'Measure same-silo internal-link reinforcement.'),
    ('discovery_demand_to_sitemap_bridge_health', 'cross_demand_sitemap', 500000, 'Measure observed search demand whose matching canonical evidence is sitemap-present.'),
    ('discovery_demand_to_internal_inlink_bridge_health', 'cross_demand_inlinks', 500000, 'Measure observed search demand whose matching canonical record has internal inlinks.'),
    ('discovery_demand_to_content_bridge_health', 'cross_demand_content', 500000, 'Measure observed search landing demand represented in supplied content documents.'),
    ('discovery_zero_click_discovery_readiness_health', 'cross_zero_click_readiness', 500000, 'Measure zero-click demand whose landing content exists and matching canonical evidence remains discoverable.'),
    ('discovery_top10_discovery_readiness_health', 'cross_top10_readiness', 500000, 'Measure top-ten observed demand whose landing content and canonical discovery evidence are both present.'),
    ('discovery_canonical_to_publication_bridge_health', 'cross_canonical_publication', 500000, 'Measure canonical URL paths that have corresponding published persistence routes.'),
    ('discovery_sitemap_to_persistence_bridge_health', 'cross_sitemap_persistence', 500000, 'Measure sitemap-present canonical paths with persistence sitemap-hash evidence.'),
    ('discovery_publisher_to_policy_bridge_health', 'cross_gateway_policy', 500000, 'Measure publisher target domains that are authorized by supplied policy evidence.'),
    ('discovery_edge_to_gateway_delivery_bridge_health', 'cross_cwv_gateway', 500000, 'Measure edge URLs with healthy publisher delivery evidence.'),
    ('discovery_full_stack_discovery_readiness', 'cross_full_stack', 700000, 'Compose canonical, persistence, publisher, edge, and policy readiness without predicting Google crawl or index timing.'),
)

def build(rows: list[dict[str, Any]]) -> None:
    for operation, mode, threshold, purpose in _CAPABILITIES:
        add(rows, 'DISCOVERY_VELOCITY', operation, 'MULTI', 'discovery_velocity_metric',
            {'mode': mode}, purpose, (), threshold)
