from __future__ import annotations

from typing import Any
from .specs_common import add

_MODES = (
    "first_party_evidence_breadth",
    "policy_evidence_breadth",
    "local_identity_source_quorum",
    "local_name_consistency",
    "local_address_consistency",
    "local_phone_consistency",
    "local_coordinate_consistency",
    "content_local_identity_support",
    "verified_service_vocabulary_support",
    "verified_location_vocabulary_support",
    "query_content_support",
    "landing_content_backing",
    "canonical_backing",
    "sitemap_backing",
    "internal_inlink_backing",
    "human_bot_parity",
    "robots_expectation_consistency",
    "indexability_expectation_consistency",
    "redirect_health",
    "http_status_health",
    "content_type_health",
    "canonical_integrity_health",
    "content_exact_duplicate_health",
    "content_near_duplicate_health",
    "thin_content_health",
    "token_repetition_health",
    "keyword_stuffing_health",
    "location_swap_template_health",
    "service_swap_template_health",
    "doorway_cluster_health",
    "unsupported_location_claim_health",
    "unsupported_service_claim_health",
    "fake_review_signal_health",
    "fake_rating_signal_health",
    "false_author_signal_health",
    "structured_data_claim_support",
    "hidden_text_signal_health",
    "cloaking_signal_health",
    "bot_specific_render_signal_health",
    "link_scheme_signal_health",
    "paid_link_signal_health",
    "pbn_signal_health",
    "reciprocal_link_scheme_signal_health",
    "automated_external_link_signal_health",
    "google_scraping_signal_health",
    "automated_query_signal_health",
    "scaled_content_signal_health",
    "abusive_scraping_signal_health",
    "site_reputation_abuse_signal_health",
    "expired_domain_abuse_signal_health",
    "malicious_behavior_signal_health",
    "doorway_signal_health",
    "hidden_link_signal_health",
    "sneaky_redirect_signal_health",
    "review_spam_signal_health",
    "fake_business_signal_health",
    "low_value_generated_content_signal_health",
    "mass_location_page_signal_health",
    "mass_service_location_page_signal_health",
    "local_query_identity_alignment",
    "commercial_query_content_alignment",
    "urgency_query_content_alignment",
    "question_query_content_alignment",
    "brand_query_identity_alignment",
    "nonbrand_demand_content_alignment",
    "high_impression_low_support_health",
    "zero_click_low_support_health",
    "multipage_query_fragmentation_health",
    "query_landing_specialization",
    "high_intent_landing_backing",
    "local_high_intent_landing_backing",
    "content_decay_republish_risk_health",
    "temporal_anomaly_evidence_health",
    "keyword_coverage_provenance_health",
    "attribution_provenance_health",
    "funnel_provenance_health",
    "upstream_receipt_hash_presence",
    "upstream_receipt_hash_integrity",
    "source_id_uniqueness",
    "cross_source_contradiction_health",
    "evidence_quorum_health",
    "verified_term_whitelist_integrity",
    "verified_location_whitelist_integrity",
    "verified_service_whitelist_integrity",
    "fail_closed_policy_evidence_health",
    "no_mutation_contract_health",
    "policy_risk_absence_composite",
    "evidence_provenance_composite",
    "whitehat_compliance_composite",
    "terminal_readiness_health",
)

def build(rows: list[dict[str, Any]]) -> None:
    for mode in _MODES:
        add(
            rows,
            "STRICT_WHITEHAT_COMPLIANCE_KERNEL",
            f"compliance_{mode}",
            "MULTI",
            "compliance_kernel_metric",
            {"mode": mode},
            "Evaluate the evidence-bound strict-white-hat compliance metric "
            + mode.replace("_", " ")
            + " using only existing NEXUS evidence; never mutate a client site, scrape Google, fabricate reviews/locations, or generate doorway content.",
            (),
            500_000,
        )
