from __future__ import annotations

from typing import Any
from .specs_common import add

_MODES = (
    "keyword_universe_evidence_coverage",
    "site_ranked_keyword_share",
    "search_volume_weighted_site_coverage",
    "competitor_only_keyword_health",
    "multi_competitor_gap_health",
    "high_volume_gap_health",
    "low_competition_opportunity_evidence",
    "service_keyword_coverage",
    "location_keyword_coverage",
    "commercial_keyword_coverage",
    "urgency_keyword_coverage",
    "question_keyword_coverage",
    "brand_keyword_coverage",
    "nonbrand_keyword_coverage",
    "service_location_keyword_coverage",
    "commercial_location_keyword_coverage",
    "local_high_intent_keyword_coverage",
    "service_gap_volume_health",
    "location_gap_volume_health",
    "service_location_gap_volume_health",
    "observed_query_keyword_bridge",
    "observed_impression_keyword_bridge",
    "observed_click_keyword_bridge",
    "keyword_to_content_support",
    "keyword_to_canonical_support",
    "keyword_to_entity_support",
    "keyword_to_local_identity_support",
    "keyword_to_intent_record_support",
    "ranked_keyword_content_backing",
    "gap_keyword_evidence_backing",
    "top1_page_demand_concentration_health",
    "top3_page_demand_concentration_health",
    "top5_page_demand_concentration_health",
    "page_coverage_efficiency",
    "query_coverage_efficiency",
    "demand_per_page_balance",
    "click_per_page_balance",
    "minimum_page_marginal_demand_health",
    "minimum_page_marginal_click_health",
    "page_removal_demand_resilience",
    "page_removal_click_resilience",
    "top_page_removal_resilience",
    "top_query_removal_resilience",
    "service_cell_coverage",
    "location_cell_coverage",
    "service_location_cell_coverage",
    "service_cell_balance",
    "location_cell_balance",
    "service_location_cell_balance",
    "cell_orphan_health",
    "cell_single_page_dependency_health",
    "cell_multi_page_fragmentation_health",
    "page_service_specialization",
    "page_location_specialization",
    "page_intent_specialization",
    "page_cell_specialization",
    "portfolio_set_cover_efficiency",
    "demand_weighted_set_cover_efficiency",
    "click_weighted_set_cover_efficiency",
    "greedy_cover_first_page_gain",
    "greedy_cover_first_two_page_gain",
    "greedy_cover_first_three_page_gain",
    "query_redundancy_health",
    "duplicate_query_assignment_health",
    "exclusive_query_share",
    "exclusive_demand_share",
    "cross_page_query_overlap_health",
    "page_jaccard_separation",
    "content_semantic_separation",
    "canonical_cluster_separation",
    "high_intent_page_coverage",
    "local_high_intent_page_coverage",
    "zero_click_page_opportunity_coverage",
    "rank_gap_page_opportunity_coverage",
    "high_impression_low_ctr_page_opportunity_coverage",
    "funnel_backed_page_priority_coverage",
    "funnel_backed_service_priority_coverage",
    "funnel_backed_location_priority_coverage",
    "portfolio_opportunity_diversity",
    "portfolio_risk_diversification",
    "demand_pareto_resilience",
    "click_pareto_resilience",
    "keyword_gap_pareto_focus",
    "service_gap_pareto_focus",
    "location_gap_pareto_focus",
    "portfolio_evidence_breadth",
    "portfolio_decision_confidence",
    "constrained_opportunity_score",
    "portfolio_resilience_score",
    "traffic_portfolio_optimizer_health",
)


def build(rows: list[dict[str, Any]]) -> None:
    for mode in _MODES:
        add(
            rows,
            "LOCAL_TRAFFIC_PORTFOLIO",
            f"traffic_portfolio_{mode}",
            "MULTI",
            "traffic_portfolio_metric",
            {"mode": mode},
            "Compute the evidence-constrained local organic traffic portfolio property "
            + mode.replace("_", " ")
            + " using supplied first-party Search data and existing NEXUS coverage/content/entity/funnel evidence; optimize review allocation without scraping Google, creating pages, or forecasting rank/revenue.",
            (),
            500_000,
        )
