from __future__ import annotations

from typing import Any
from .specs_common import add

_CAPABILITIES = (
    ('topical_intent_label_presence_health', 'intent_label_presence', 500000, 'Measure explicit intent-label coverage in existing search-intent records.'),
    ('topical_transactional_signal_coverage_health', 'transactional_signal_coverage', 500000, 'Measure search-intent records carrying legitimate transactional vocabulary.'),
    ('topical_informational_signal_coverage_health', 'informational_signal_coverage', 500000, 'Measure search-intent records carrying informational/question vocabulary.'),
    ('topical_comparative_signal_coverage_health', 'comparative_signal_coverage', 500000, 'Measure search-intent records carrying comparative vocabulary.'),
    ('topical_query_title_alignment_health', 'query_title_alignment', 500000, 'Measure lexical alignment between observed query and supplied title evidence.'),
    ('topical_meta_description_presence_health', 'meta_description_presence', 500000, 'Measure descriptive metadata presence in supplied search-intent evidence.'),
    ('topical_intent_entity_presence_health', 'intent_entity_presence', 500000, 'Measure explicit entity coverage in search-intent records.'),
    ('topical_image_alt_semantic_presence_health', 'image_alt_presence', 500000, 'Measure non-empty semantic image-alt evidence.'),
    ('topical_internal_anchor_presence_health', 'internal_anchor_presence', 500000, 'Measure internal-anchor evidence coverage.'),
    ('topical_navigation_entity_presence_health', 'navigation_entity_presence', 500000, 'Measure navigation-entity evidence coverage.'),
    ('topical_silo_assignment_presence_health', 'silo_presence', 500000, 'Measure explicit topical silo assignment coverage.'),
    ('topical_internal_link_target_presence_health', 'internal_link_target_presence', 500000, 'Measure internal-link target evidence coverage.'),
    ('topical_content_freshness_window_health', 'intent_freshness', 500000, 'Measure supplied search-intent content age against a bounded review window.'),
    ('topical_niche_assignment_presence_health', 'niche_presence', 500000, 'Measure explicit niche/category assignment coverage.'),
    ('topical_conversion_synonym_evidence_presence', 'conversion_synonym_presence', 500000, 'Measure explicit conversion-synonym evidence without generating manipulative copy.'),
    ('topical_semantic_entity_graph_presence', 'semantic_entity_graph', 700000, 'Measure semantic records containing entity graph evidence.'),
    ('topical_semantic_org_entity_presence', 'semantic_org_entity', 500000, 'Measure organization-entity coverage.'),
    ('topical_semantic_geo_entity_presence', 'semantic_geo_entity', 500000, 'Measure geographic entity coverage.'),
    ('topical_semantic_service_entity_presence', 'semantic_service_entity', 500000, 'Measure service-entity coverage.'),
    ('topical_semantic_event_entity_presence', 'semantic_event_entity', 500000, 'Measure event/process entity coverage.'),
    ('topical_semantic_related_entity_edge_presence', 'semantic_related_edges', 500000, 'Measure entity relation-edge coverage.'),
    ('topical_semantic_entity_salience_health', 'semantic_entity_salience', 500000, 'Measure records containing at least one materially salient entity.'),
    ('topical_semantic_language_consistency_health', 'semantic_language_consistency', 500000, 'Measure semantic locale consistency against project language configuration when supplied.'),
    ('topical_semantic_heading_presence_health', 'semantic_heading_presence', 500000, 'Measure heading evidence coverage in semantic records.'),
    ('topical_semantic_link_anchor_presence_health', 'semantic_link_anchor_presence', 500000, 'Measure semantic link-anchor evidence coverage.'),
    ('topical_semantic_intent_label_presence_health', 'semantic_intent_presence', 500000, 'Measure semantic intent-label evidence coverage.'),
    ('topical_semantic_external_context_presence_health', 'semantic_external_context', 500000, 'Measure external-context identifier coverage for supplied entities.'),
    ('topical_semantic_entity_property_presence_health', 'semantic_entity_properties', 500000, 'Measure entity property evidence coverage.'),
    ('topical_semantic_schema_type_presence_health', 'semantic_schema_types', 500000, 'Measure entity schema-type evidence coverage.'),
    ('topical_semantic_entity_cache_presence_health', 'semantic_entity_cache', 500000, 'Measure supplied entity-cache evidence coverage.'),
    ('topical_service_term_document_coverage_health', 'content_service_coverage', 500000, 'Measure verified service vocabulary coverage across supplied content documents.'),
    ('topical_location_term_document_coverage_health', 'content_location_coverage', 500000, 'Measure verified location vocabulary coverage across supplied content documents.'),
    ('topical_commercial_term_document_coverage_health', 'content_commercial_coverage', 500000, 'Measure commercial vocabulary coverage across supplied content documents.'),
    ('topical_urgency_term_document_coverage_health', 'content_urgency_coverage', 500000, 'Measure urgency vocabulary coverage across supplied content documents.'),
    ('topical_question_term_document_coverage_health', 'content_question_coverage', 500000, 'Measure question/help vocabulary coverage across supplied content documents.'),
    ('topical_brand_term_document_coverage_health', 'content_brand_coverage', 500000, 'Measure brand vocabulary coverage across supplied content documents.'),
    ('topical_service_query_coverage_health', 'query_service_coverage', 500000, 'Measure observed queries carrying verified service vocabulary.'),
    ('topical_location_query_coverage_health', 'query_location_coverage', 500000, 'Measure observed queries carrying verified location vocabulary.'),
    ('topical_commercial_query_coverage_health', 'query_commercial_coverage', 500000, 'Measure observed queries carrying commercial vocabulary.'),
    ('topical_urgency_query_coverage_health', 'query_urgency_coverage', 500000, 'Measure observed queries carrying urgency vocabulary.'),
    ('topical_question_query_coverage_health', 'query_question_coverage', 500000, 'Measure observed queries carrying question/help vocabulary.'),
    ('topical_brand_query_coverage_health', 'query_brand_coverage', 500000, 'Measure observed queries carrying brand vocabulary.'),
    ('topical_longtail_query_support_health', 'query_longtail_support', 500000, 'Measure search demand with at least four query tokens and supplied landing content.'),
    ('topical_service_location_joint_query_health', 'query_service_location_joint', 500000, 'Measure observed queries combining verified service and verified location evidence.'),
    ('topical_commercial_location_joint_query_health', 'query_commercial_location_joint', 500000, 'Measure observed queries combining commercial and location evidence.'),
    ('topical_service_commercial_content_joint_health', 'lattice_service_commercial_content', 500000, 'Measure content documents jointly supporting verified service and commercial vocabulary.'),
    ('topical_service_location_content_joint_health', 'lattice_service_location_content', 500000, 'Measure content documents jointly supporting verified service and verified location vocabulary.'),
    ('topical_service_urgency_content_joint_health', 'lattice_service_urgency_content', 500000, 'Measure content documents jointly supporting service and urgency vocabulary.'),
    ('topical_service_question_content_joint_health', 'lattice_service_question_content', 500000, 'Measure content documents jointly supporting service and question/help vocabulary.'),
    ('topical_brand_service_content_joint_health', 'lattice_brand_service_content', 500000, 'Measure documents jointly supporting brand and verified service evidence.'),
    ('topical_brand_location_content_joint_health', 'lattice_brand_location_content', 500000, 'Measure documents jointly supporting brand and verified location evidence.'),
    ('topical_service_commercial_query_joint_health', 'lattice_service_commercial_query', 500000, 'Measure queries jointly carrying service and commercial intent evidence.'),
    ('topical_service_location_query_joint_health', 'lattice_service_location_query', 500000, 'Measure queries jointly carrying service and location evidence.'),
    ('topical_service_urgency_query_joint_health', 'lattice_service_urgency_query', 500000, 'Measure queries jointly carrying service and urgency evidence.'),
    ('topical_service_question_query_joint_health', 'lattice_service_question_query', 500000, 'Measure queries jointly carrying service and question evidence.'),
    ('topical_brand_service_query_joint_health', 'lattice_brand_service_query', 500000, 'Measure queries jointly carrying brand and service evidence.'),
    ('topical_brand_location_query_joint_health', 'lattice_brand_location_query', 500000, 'Measure queries jointly carrying brand and location evidence.'),
    ('topical_service_location_page_specialization_health', 'lattice_service_location_specialization', 500000, 'Measure service+location queries landing on pages whose content visibly supports both dimensions.'),
    ('topical_service_location_cell_coverage_health', 'lattice_service_location_cells', 500000, 'Measure observed coverage of configured service×location cells.'),
    ('topical_service_location_cell_single_owner_health', 'lattice_service_location_single_owner', 500000, 'Measure whether observed service×location cells resolve to one primary landing page rather than fragmented ownership.'),
    ('topical_content_pair_differentiation_health', 'topology_content_differentiation', 500000, 'Measure pairwise document differentiation using deterministic token Jaccard.'),
    ('topical_content_unique_token_share_health', 'topology_unique_token_share', 500000, "Measure each document's contribution of tokens not present in peer documents."),
    ('topical_page_query_specialization_health', 'topology_page_query_specialization', 500000, 'Measure concentration of each page on coherent query vocabulary.'),
    ('topical_query_page_single_owner_health', 'topology_query_single_owner', 500000, 'Measure single-page ownership of observed queries.'),
    ('topical_page_pair_query_overlap_health', 'topology_page_query_overlap', 500000, 'Measure pairwise query-set overlap among landing pages.'),
    ('topical_query_cluster_breadth_health', 'topology_query_cluster_breadth', 500000, 'Measure breadth of explicit canonical query-cluster evidence.'),
    ('topical_silo_cluster_coherence_health', 'topology_silo_cluster_coherence', 500000, 'Measure search-intent silo vocabulary alignment with canonical query clusters.'),
    ('topical_internal_link_same_silo_health', 'topology_internal_same_silo', 500000, 'Measure same-silo internal-link reinforcement.'),
    ('topical_internal_link_cross_silo_bridge_health', 'topology_internal_cross_silo', 500000, 'Measure existence of deliberate cross-silo bridges without forcing them.'),
    ('topical_navigation_entity_coverage_health', 'topology_navigation_entity_coverage', 500000, 'Measure navigation entities against supplied topical entities.'),
    ('topical_canonical_query_cluster_coverage_health', 'topology_canonical_cluster_coverage', 500000, 'Measure canonical records with query-cluster coverage.'),
    ('topical_canonical_entity_coverage_health', 'topology_canonical_entity_coverage', 500000, 'Measure canonical records carrying entity evidence.'),
    ('topical_topical_gini_balance_health', 'topology_gini_balance', 500000, 'Measure balance of observed query demand across configured service groups.'),
    ('topical_topic_page_pareto_balance_health', 'topology_pareto_balance', 500000, 'Measure how many landing pages are needed to cover eighty percent of observed impressions.'),
    ('topical_mixed_intent_page_review_health', 'topology_mixed_intent_review', 500000, 'Measure pages serving excessive distinct intent families as a human-review signal, not an automatic split.'),
    ('topical_local_name_content_corroboration_health', 'local_name_content_corroboration', 500000, 'Measure business-name corroboration in supplied content.'),
    ('topical_local_address_content_corroboration_health', 'local_address_content_corroboration', 500000, 'Measure business-address corroboration in supplied content.'),
    ('topical_local_phone_content_corroboration_health', 'local_phone_content_corroboration', 500000, 'Measure business-phone corroboration in supplied content.'),
    ('topical_local_service_identity_joint_health', 'local_service_identity_joint', 500000, 'Measure verified service evidence coexisting with corroborated local identity.'),
    ('topical_local_location_identity_joint_health', 'local_location_identity_joint', 500000, 'Measure verified location evidence coexisting with corroborated local identity.'),
    ('topical_local_brand_identity_joint_health', 'local_brand_identity_joint', 500000, 'Measure brand vocabulary coexisting with supplied local identity.'),
    ('topical_local_service_semantic_entity_joint_health', 'local_service_semantic_entity_joint', 500000, 'Measure verified service vocabulary corroborated by semantic SERVICE entities.'),
    ('topical_local_location_semantic_entity_joint_health', 'local_location_semantic_entity_joint', 500000, 'Measure verified location vocabulary corroborated by semantic geographic entities.'),
    ('topical_local_service_query_entity_joint_health', 'local_service_query_entity_joint', 500000, 'Measure service-bearing queries against supplied semantic service entities.'),
    ('topical_local_location_query_entity_joint_health', 'local_location_query_entity_joint', 500000, 'Measure location-bearing queries against supplied semantic geographic entities.'),
    ('topical_verified_service_vocabulary_health', 'verified_service_vocabulary', 500000, 'Require topical service coverage to be grounded in explicitly verified service terms.'),
    ('topical_verified_location_vocabulary_health', 'verified_location_vocabulary', 500000, 'Require topical location coverage to be grounded in explicitly verified location terms.'),
    ('topical_unsupported_service_vocabulary_absence_health', 'unsupported_service_absence', 500000, 'Detect configured service terms that are not in the verified service allowlist.'),
    ('topical_unsupported_location_vocabulary_absence_health', 'unsupported_location_absence', 500000, 'Detect configured location terms that are not in the verified location allowlist.'),
    ('topical_topical_whitehat_value_density_health', 'topical_whitehat_value_density', 700000, 'Compose topical coverage, differentiation, verified-service/location grounding and local identity into a white-hat value-density diagnostic.'),
)

def build(rows: list[dict[str, Any]]) -> None:
    for operation, mode, threshold, purpose in _CAPABILITIES:
        add(rows, 'LOCAL_TOPICAL_LATTICE', operation, 'MULTI', 'topical_lattice_metric',
            {'mode': mode}, purpose, (), threshold)
