from __future__ import annotations

from typing import Any
from .specs_common import add

_MODES = (
    "silo_node_coverage",
    "observed_edge_coverage",
    "self_loop_health",
    "duplicate_edge_health",
    "weak_component_health",
    "largest_component_share",
    "orphan_node_health",
    "source_only_node_health",
    "sink_only_node_health",
    "reciprocal_edge_share",
    "directed_reachability_share",
    "outdegree_balance_health",
    "indegree_balance_health",
    "max_outdegree_concentration_health",
    "max_indegree_concentration_health",
    "edge_density_health",
    "bridge_edge_resilience",
    "articulation_node_resilience",
    "cycle_participation_share",
    "acyclic_dependency_health",
    "median_shortest_path_health",
    "directed_diameter_health",
    "graph_radius_health",
    "eccentricity_balance_health",
    "source_query_support_share",
    "target_query_support_share",
    "source_entity_support_share",
    "target_entity_support_share",
    "anchor_support_share",
    "generic_anchor_health",
    "anchor_vocabulary_diversity",
    "target_silo_content_support_share",
    "cross_silo_link_share",
    "same_silo_link_share",
    "navigation_entity_bridge_share",
    "service_bridge_share",
    "location_bridge_share",
    "urgency_bridge_share",
    "question_bridge_share",
    "commercial_bridge_share",
    "brand_bridge_share",
    "canonical_source_cluster_support",
    "canonical_target_cluster_support",
    "demand_backed_target_share",
    "dead_end_high_demand_health",
    "orphan_high_demand_health",
    "sink_high_demand_health",
    "source_only_high_demand_health",
    "demand_weighted_reachability",
    "click_weighted_reachability",
    "zero_click_weighted_reachability",
    "top10_weighted_reachability",
    "rank_gap_weighted_reachability",
    "silo_demand_gini_health",
    "silo_click_gini_health",
    "queries_per_silo_balance",
    "intents_per_silo_balance",
    "entities_per_silo_balance",
    "anchors_per_silo_balance",
    "component_demand_balance",
    "component_click_balance",
    "bridge_edge_demand_resilience",
    "articulation_demand_resilience",
    "best_bridge_reachability_gain",
    "best_bridge_demand_gain",
    "best_reciprocal_reachability_gain",
    "best_orphan_attach_gain",
    "best_sink_escape_gain",
    "best_component_merge_gain",
    "worst_edge_removal_reachability_resilience",
    "worst_edge_removal_demand_resilience",
    "bridge_redundancy_counterfactual",
    "articulation_redundancy_counterfactual",
    "route_depth_reduction_potential",
    "candidate_target_overload_health",
    "candidate_semantic_support",
    "candidate_shared_entity_support",
    "candidate_query_overlap_support",
    "candidate_canonical_cluster_support",
    "candidate_local_intent_support",
    "candidate_service_intent_support",
    "candidate_commercial_intent_support",
    "candidate_nonbrand_support",
    "candidate_source_canonical_integrity",
    "candidate_target_canonical_integrity",
    "candidate_source_sitemap_backing",
    "candidate_target_sitemap_backing",
    "counterfactual_candidate_evidence_breadth",
    "counterfactual_confidence_index",
    "internal_authority_counterfactual_health",
)


def build(rows: list[dict[str, Any]]) -> None:
    for mode in _MODES:
        add(
            rows,
            "LOCAL_LINK_COUNTERFACTUAL",
            f"counterfactual_{mode}",
            "MULTI",
            "link_counterfactual_metric",
            {"mode": mode},
            "Evaluate the evidence-bound internal-link counterfactual metric "
            + mode.replace("_", " ")
            + " using only existing NEXUS graph/search/content evidence; never create links, claim Google PageRank, or mutate a client site.",
            (),
            500_000,
        )
