from __future__ import annotations

from typing import Any
from .specs_common import add

_MODES = (
    "title_query_token_overlap",
    "title_service_support",
    "title_location_support",
    "title_commercial_support",
    "title_brand_support",
    "meta_query_token_overlap",
    "meta_service_support",
    "meta_location_support",
    "meta_commercial_support",
    "meta_brand_support",
    "heading_query_token_overlap",
    "heading_service_support",
    "heading_location_support",
    "heading_commercial_support",
    "heading_brand_support",
    "image_alt_query_support",
    "image_alt_service_support",
    "image_alt_location_support",
    "internal_anchor_query_support",
    "internal_anchor_service_support",
    "internal_anchor_location_support",
    "navigation_entity_query_support",
    "navigation_entity_brand_support",
    "intent_label_presence",
    "conversion_synonym_presence",
    "title_meta_semantic_agreement",
    "title_heading_semantic_agreement",
    "meta_heading_semantic_agreement",
    "representation_triplet_consistency",
    "intent_record_content_alignment",
    "jsonld_type_presence",
    "jsonld_webpage_presence",
    "jsonld_localbusiness_or_legalservice_presence",
    "jsonld_organization_presence",
    "jsonld_type_diversity",
    "visible_text_presence",
    "heading_presence",
    "human_bot_parity",
    "authorized_domain_alignment",
    "site_identity_alignment",
    "robots_expectation_alignment",
    "index_follow_directive_alignment",
    "html_content_type_alignment",
    "stream_delivery_alignment",
    "retry_after_contract_health",
    "closure_integrity_health",
    "closure_policy_health",
    "schema_type_to_local_identity_support",
    "schema_type_to_semantic_entity_support",
    "schema_type_to_content_support",
    "semantic_entity_presence",
    "semantic_entity_label_content_support",
    "semantic_entity_relation_density",
    "semantic_entity_connectedness",
    "semantic_entity_salience_coverage",
    "semantic_entity_type_diversity",
    "semantic_entity_project_source_share",
    "semantic_entity_property_presence",
    "semantic_entity_schema_type_presence",
    "semantic_heading_entity_support",
    "semantic_link_entity_support",
    "semantic_intent_label_presence",
    "semantic_locale_alignment",
    "semantic_entity_cache_presence",
    "semantic_service_entity_presence",
    "semantic_location_entity_presence",
    "semantic_brand_entity_presence",
    "semantic_event_entity_presence",
    "semantic_entity_query_alignment",
    "semantic_entity_content_alignment",
    "search_landing_intent_record_alignment",
    "search_landing_content_document_alignment",
    "search_query_title_alignment",
    "search_query_meta_alignment",
    "search_query_heading_alignment",
    "search_query_alt_alignment",
    "search_query_anchor_alignment",
    "search_query_navigation_entity_alignment",
    "search_query_semantic_entity_alignment",
    "local_identity_title_alignment",
    "local_identity_meta_alignment",
    "local_identity_heading_alignment",
    "local_identity_semantic_alignment",
    "canonical_landing_alignment",
    "canonical_brand_entity_alignment",
    "canonical_query_cluster_alignment",
    "canonical_schema_signature_presence",
    "representation_evidence_breadth",
    "representation_conflict_health",
    "representation_proof_mesh_health",
)


def build(rows: list[dict[str, Any]]) -> None:
    for mode in _MODES:
        add(
            rows,
            "SEARCH_REPRESENTATION_PROOF",
            f"representation_{mode}",
            "MULTI",
            "representation_proof_metric",
            {"mode": mode},
            "Verify the proof-carrying search-representation property "
            + mode.replace("_", " ")
            + " from existing NEXUS content, intent, entity, canonical and policy evidence without fabricating schema or promising rich results.",
            (),
            500_000,
        )
