from __future__ import annotations

from typing import Any
from .specs_common import add

_MODES = (
    "entity_inventory_health",
    "relation_edge_coverage",
    "weak_component_health",
    "largest_component_share",
    "isolated_entity_health",
    "reciprocal_relation_share",
    "outdegree_balance_health",
    "indegree_balance_health",
    "hub_concentration_health",
    "articulation_resilience",
    "bridge_edge_resilience",
    "cycle_participation_share",
    "directed_reachability_share",
    "two_hop_reachability_share",
    "type_mixing_health",
    "property_completeness",
    "schema_annotation_completeness",
    "project_source_share",
    "salience_coverage",
    "high_salience_relation_support",
    "query_entity_alignment",
    "commercial_query_entity_alignment",
    "service_query_entity_alignment",
    "location_query_entity_alignment",
    "urgency_query_entity_alignment",
    "question_query_entity_alignment",
    "brand_query_entity_alignment",
    "longtail_query_entity_alignment",
    "zero_click_query_entity_support",
    "top10_query_entity_support",
    "rank_gap_query_entity_support",
    "page_entity_breadth_health",
    "query_entity_breadth_health",
    "query_to_entity_specialization",
    "entity_to_query_specialization",
    "query_entity_component_health",
    "impression_weighted_entity_support",
    "click_weighted_entity_support",
    "high_intent_entity_support",
    "local_identity_query_entity_bridge",
    "document_entity_presence",
    "content_label_support",
    "heading_entity_support",
    "link_anchor_entity_support",
    "entity_cache_support",
    "document_entity_breadth_health",
    "entity_document_breadth_health",
    "service_entity_document_coverage",
    "location_entity_document_coverage",
    "brand_entity_document_coverage",
    "event_entity_document_coverage",
    "content_entity_component_health",
    "orphan_entity_content_gap_health",
    "high_salience_content_support",
    "property_token_content_support",
    "relation_pair_content_cooccurrence",
    "relation_pair_heading_support",
    "relation_pair_link_support",
    "document_entity_diversity",
    "entity_content_evidence_breadth",
    "local_name_entity_support",
    "local_location_entity_support",
    "canonical_brand_entity_support",
    "canonical_entity_inventory_support",
    "canonical_schema_signature_backing",
    "jsonld_type_backing",
    "organization_type_support",
    "legalservice_type_support",
    "localbusiness_type_support",
    "entity_schema_property_consistency",
    "local_identity_source_quorum",
    "entity_local_identity_corroboration",
    "canonical_entity_query_cluster_bridge",
    "site_identity_entity_bridge",
    "schema_entity_evidence_breadth",
    "best_missing_bridge_reachability_gain",
    "best_component_merge_gain",
    "hub_overload_health",
    "bridge_redundancy_health",
    "articulation_redundancy_health",
    "salience_weighted_reachability",
    "query_weighted_reachability",
    "demand_weighted_entity_centrality",
    "entity_evidence_breadth",
    "entity_contradiction_health",
    "duplicate_label_health",
    "entity_type_conflict_health",
    "project_source_conflict_health",
    "entity_graph_confidence",
    "entity_proof_graph_health",
)


def build(rows: list[dict[str, Any]]) -> None:
    for mode in _MODES:
        add(
            rows,
            "LOCAL_ENTITY_PROOF_GRAPH",
            f"entity_graph_{mode}",
            "MULTI",
            "entity_proof_graph_metric",
            {"mode": mode},
            "Compute the proof-carrying local entity-knowledge-graph property "
            + mode.replace("_", " ")
            + " from existing NEXUS semantic, search, content, canonical, schema and business evidence; never invent an entity, location, service, review or ranking signal.",
            (),
            500_000,
        )
