from __future__ import annotations

from typing import Any
from .specs_common import add

_MODES = (
    "observed_query_coverage",
    "observed_landing_coverage",
    "impression_evidence_density",
    "click_evidence_density",
    "overall_ctr_health",
    "zero_click_impression_health",
    "top3_impression_share",
    "top10_impression_share",
    "position_11_20_share",
    "position_21_plus_share",
    "weighted_position_health",
    "query_to_page_specialization",
    "multi_page_query_health",
    "landing_query_breadth_health",
    "brand_impression_balance",
    "nonbrand_impression_share",
    "commercial_impression_share",
    "service_impression_share",
    "location_impression_share",
    "urgency_impression_share",
    "longtail_impression_share",
    "question_impression_share",
    "service_location_impression_share",
    "commercial_location_impression_share",
    "urgency_location_impression_share",
    "brand_ctr_health",
    "nonbrand_ctr_health",
    "commercial_ctr_health",
    "service_ctr_health",
    "location_ctr_health",
    "urgency_ctr_health",
    "longtail_ctr_health",
    "question_ctr_health",
    "top10_ctr_health",
    "position_11_20_ctr_health",
    "position_21_plus_ctr_health",
    "demand_canonical_match_share",
    "demand_content_document_match_share",
    "demand_sitemap_backing_share",
    "demand_internal_inlink_backing_share",
    "demand_content_token_support_share",
    "intent_record_query_alignment_share",
    "internal_anchor_query_alignment_share",
    "navigation_entity_query_alignment_share",
    "semantic_entity_query_alignment_share",
    "local_identity_corroborated_demand_share",
    "canonical_entity_corroborated_demand_share",
    "query_cluster_corroborated_demand_share",
    "service_group_coverage",
    "location_group_coverage",
    "service_location_cell_coverage",
    "service_location_zero_click_health",
    "service_location_top10_share",
    "service_location_ctr_health",
    "page_impression_gini_health",
    "page_click_gini_health",
    "query_impression_gini_health",
    "query_click_gini_health",
    "page_hhi_health",
    "query_hhi_health",
    "page_diversity_index",
    "query_diversity_index",
    "page_pareto_20_share_health",
    "click_pareto_20_share_health",
    "position_4_20_opportunity_health",
    "top10_zero_click_opportunity_health",
    "high_impression_low_ctr_health",
    "first_page_underclick_health",
    "rank_gap_11_20_health",
    "deep_gap_21_plus_health",
    "local_high_intent_gap_health",
    "commercial_high_intent_gap_health",
    "urgent_gap_health",
    "longtail_gap_health",
    "question_gap_health",
    "content_supported_zero_click_health",
    "content_unsupported_demand_health",
    "canonical_unbacked_demand_health",
    "no_internal_inlink_demand_health",
    "no_sitemap_demand_health",
    "semantic_mismatch_demand_health",
    "identity_mismatch_local_demand_health",
    "landing_concentration_health",
    "brand_dependency_health",
    "service_coverage_gap_health",
    "location_coverage_gap_health",
    "service_location_gap_health",
    "demand_frontier_composite_health",
    "evidence_breadth_health",
    "decision_readiness_health",
)


def build(rows: list[dict[str, Any]]) -> None:
    for mode in _MODES:
        add(
            rows,
            "LOCAL_DEMAND_FRONTIER",
            f"frontier_{mode}",
            "MULTI",
            "demand_frontier_metric",
            {"mode": mode},
            "Compute the evidence-bound local search demand frontier metric "
            + mode.replace("_", " ")
            + " from first-party NEXUS observations without scraping Google or forecasting rankings/revenue.",
            (),
            500_000,
        )
