import type { NexusTheme } from "@nexus/core/foundation/theme";

export const laPauseTheme: NexusTheme = {
  "space.xs": "0.5rem",
  "space.sm": "0.875rem",
  "space.md": "1.5rem",
  "space.lg": "3rem",
  "space.xl": "6rem",
  "container.sm": "36rem",
  "container.md": "54rem",
  "container.lg": "76rem",
  "container.xl": "94rem",
  "focus.ring": "#0057a8",
  "focus.offset": "3px",
  "motion.duration.instant": "0ms",
  "motion.duration.fast": "160ms",
  "motion.duration.base": "420ms",
  "motion.duration.slow": "900ms",
  "motion.easing.standard": "ease",
  "motion.easing.decelerate": "cubic-bezier(0.16,1,0.3,1)",
  "motion.easing.accelerate": "cubic-bezier(0.7,0,0.84,0)",
  "motion.easing.linear": "linear",
  "surface.base": "#f4f1e9",
  "surface.elevated": "#fffdf7",
  "surface.inverse": "#251a16",
  "surface.overlay": "rgba(37,26,22,.62)",
  "content.primary": "#251a16",
  "content.secondary": "#695950",
  "content.inverse": "#fffdf7",
  "content.disabled": "#a79c95",
  "accent.default": "#a5141c",
  "accent.emphasis": "#790c13",
  "accent.muted": "#e7b8b2",
  "border.subtle": "rgba(37,26,22,.18)",
  "border.strong": "rgba(37,26,22,.62)",
  "radius.sm": "0px",
  "radius.md": "0px",
  "radius.lg": "999px",
  "radius.full": "999px"
};
